const de_data: Record<string, string> = {
  "p1:name": "Holzkamin",
  "p2:name": "Gaskamin",
  "p3:name": "Bioethanol-Kamin",
  "p4:name": "Wasserdampf-Kamin",
  "p7:name": "Elektrokamin",
  "p9:name": "Holografischer Kamin",
  "p6:name": "Kamin-Sonderanfertigung",
  "p88:name": "Outdoor-Feuerstelle",
  "p8:name": "Zubehör",

  "独立式": "Freistehend",
  "嵌入式": "Einbau",
  "壁挂式": "Wandmontage",
  "悬挂式": "Hängend",
  "悬挂/独立/嵌入": "Hängend / freistehend / Einbau",
  "独立/嵌入": "Freistehend / Einbau",
  "附件": "Zubehör",
  "嵌入式 / 批量定制": "Einbau / Serienanpassung",
  "嵌入式 / 自动控制": "Einbau / automatische Steuerung",
  "双面 / 隔断式": "Doppelseitig / Raumteiler",
  "三面观火": "Dreiseitige Sicht",
  "桌面式": "Tischmodell",
  "户外 / 火盆": "Outdoor / Feuerschale",
  "户外 / 火桌": "Outdoor / Feuertisch",
  "岛台式": "Inselmodell",
  "工程长条": "Projekt-Langformat",
  "壁龛嵌入式": "Nischen-Einbau",
  "OEM套件": "OEM-Bausatz",
  "嵌入式 / 长条": "Einbau / Linear",
  "圆形 / 火盆": "Rund / Feuerschale",
  "全景嵌入式": "Panorama-Einbau",
  "嵌入式 / 电视墙": "Einbau / Medienwand",
  "OEM机芯": "OEM-Kernmodul",
  "全息显示": "Holografische Anzeige",
  "投影系统": "Projektionssystem",
  "影像墙": "Flammen-Videowand",
  "壁炉宗师": "Fireplace Master",

  "西班牙": "Spanien",
  "丹麦": "Dänemark",
  "奥地利": "Österreich",
  "瑞士": "Schweiz",
  "荷兰": "Niederlande",
  "中国": "China",

  "p1_71:name": "Lacunza Altea freistehender Holzofen mit Backofen",
  "p1_71:description": "Spanischer Lacunza Altea Holzofen mit Backofen. Klassische Optik mit Heiz- und Kochfunktion.",
  "p1_1:name": "Lacunza Stelar 93 freistehender Holzkamin",
  "p1_1:description": "Spanischer Lacunza Stelar 93 Holzkamin mit eleganter Form und hoher Heizleistung.",
  "p1_45:name": "Lacunza Sara Einbau-Holzkamin",
  "p1_45:description": "Spanischer Lacunza Sara Einbau-Holzkamin für platzsparende Kaminwände.",
  "p1_44:name": "Lacunza Oslo freistehender Holzofen",
  "p1_44:description": "Spanischer Lacunza Oslo Holzofen mit zusätzlicher Kochfunktion.",
  "p1_43:name": "Lacunza Nickel doppelseitiger Einbau-Holzkamin",
  "p1_43:description": "Doppelseitiger Lacunza Nickel Holzkamin mit Feuerblick von beiden Raumseiten.",
  "p1_42:name": "Lacunza K2 800 Einbau-Holzkamin",
  "p1_42:description": "Einbau-Holzkamin Lacunza K2 800 mit breitem Sichtfenster.",
  "p1_41:name": "Lacunza Itaca einseitiger Einbau-Holzkamin",
  "p1_41:description": "Klassischer einseitiger Einbau-Holzkamin für effiziente Raumwärme.",
  "p1_39:name": "Lacunza CM 300R Eck-Holzkamin",
  "p1_39:description": "Freistehender Eck-Holzkamin für platzsparende Kaminlösungen.",
  "p1_38:name": "Lacunza Clasica 7T Holzofen mit Backofen",
  "p1_38:description": "Holzofen im europäischen Landhausstil mit integrierter Backfunktion.",
  "p1_37:name": "Lacunza Atlantic 603 freistehender Holzkamin",
  "p1_37:description": "Freistehender Holzkamin mit markanter Optik und starker Heizleistung.",
  "p1_36:name": "Lacunza Adour 700ST Einbau-Holzkamin",
  "p1_36:description": "Moderner Einbau-Holzkamin mit klarer Linienführung.",
  "p1_61:name": "Rais Q TEE 2C freistehender Holzkamin",
  "p1_61:description": "Dänischer Holzkamin mit nordischem Design und effizienter Verbrennung.",
  "p1_60:name": "Rais Nexo Serie freistehender Holzkamin",
  "p1_60:description": "Freistehender Holzkamin im modernen minimalistischen Stil.",
  "p1_59:name": "Rais Juno L freistehender Holzkamin",
  "p1_59:description": "Zylindrischer Holzkamin mit rundem Sichtfenster.",
  "p1_58:name": "Rais Caro 90 freistehender Holzkamin",
  "p1_58:description": "Eleganter zylindrischer Holzkamin für hochwertige Wohnräume.",
  "p1_28:name": "Rais Viva L Serie freistehender Holzkamin",
  "p1_28:description": "Schlanker freistehender Holzkamin mit lebendigem Flammenbild.",
  "p1_27:name": "Rais Visio 3 dreiseitiger Einbau-Holzkamin",
  "p1_27:description": "Dreiseitiger Einbau-Holzkamin mit 270-Grad-Flammenblick.",
  "p1_26:name": "Rais Q-TEE 2 freistehender Holzkamin",
  "p1_26:description": "Kompakter freistehender Holzkamin mit geometrischem Design.",
  "p1_25:name": "Rais Q-BE Eckblick-Holzkamin",
  "p1_25:description": "Freistehender Holzkamin mit besonderer Eckansicht.",
  "p1_24:name": "Rais Pilar freistehender Holzkamin",
  "p1_24:description": "Säulenförmiger Holzkamin für ruhige, hochwertige Innenräume.",
  "p1_23:name": "Rais Bionic Fire Holzkamin mit Doppelkammer",
  "p1_23:description": "Holzkamin mit innovativer Doppelverbrennungstechnologie.",
  "p1_22:name": "Haas+sohn Treviso Speckstein-Holzkamin",
  "p1_22:description": "Speckstein-Holzkamin mit lang anhaltender Wärmespeicherung.",
  "p1_21:name": "Haas+sohn Kuopio-II Speckstein-Holzkamin",
  "p1_21:description": "Nordisch geprägter Speckstein-Holzkamin mit klassischer Optik.",
  "p1_20:name": "Haas+sohn Ficus-II-RLU freistehender Holzkamin",
  "p1_20:description": "Freistehender Holzkamin mit weicher Linienführung.",
  "p1_2:name": "Haas+sohn Aruba Easy Speckstein-Holzofen",
  "p1_2:description": "Einfach zu bedienender Speckstein-Holzofen mit effizienter Wärmespeicherung.",
  "p1_35:name": "Ruegg Tillia dreiseitiger Einbau-Holzkamin",
  "p1_35:description": "Schweizer Einbau-Holzkamin mit dreiseitigem Feuerblick.",
  "p1_34:name": "Ruegg Rondeo Einbau-Holzkamin mit gebogenem Glas",
  "p1_34:description": "Einbau-Holzkamin mit markantem gebogenem Sichtglas.",
  "p1_33:name": "Ruegg RII Eck-Einbau-Holzkamin",
  "p1_33:description": "Eck-Einbau-Holzkamin für platzsparende Projektlösungen.",
  "p1_18:name": "Ruegg Odeon 270° gebogener Hänge-Holzkamin",
  "p1_18:description": "Hängender Holzkamin mit gebogener Panoramaansicht.",
  "p2_56:name": "Element4 Lucius 140 Einbau-Gaskamin",
  "p2_56:description": "Niederländischer Einbau-Gaskamin mit breiter Sichtfläche und moderner Gastechnik.",
  "p2_55:name": "Element4 Tenore 140 Einbau-Gaskamin",
  "p2_55:description": "Linearer Einbau-Gaskamin für moderne Innenräume.",
  "p2_54:name": "Element4 Summum 100F Einbau-Gaskamin",
  "p2_54:description": "Premium-Einbau-Gaskamin für hochwertige Wohn- und Gewerberäume.",
  "p2_53:name": "Element4 Sky Indoor Serie Gaskamin",
  "p2_53:description": "Gaskaminserie für nahtlose Innenraumlösungen.",
  "p2_31:name": "Element4 Trisore 140 dreiseitiger Gaskamin",
  "p2_31:description": "Dreiseitiger Gaskamin mit großem Panorama-Flammenbild.",
  "p2_29:name": "Element4 Bidore 100 Eck-Gaskamin",
  "p2_29:description": "Eck-Gaskamin mit beidseitigem Feuerblick.",

  "p3_14:name": "Linearer manueller Bioethanol-Brenner für OEM/ODM-Großhandel",
  "p3_14:description": "Einbau-Bioethanol-Brenner für internationale Marken, Importeure und Projektkunden. Länge, Oberfläche, Glasaufsatz, Logo und Exportverpackung können je nach Auftrag angepasst werden.",
  "p3_15:name": "Automatischer Bioethanol-Brenner",
  "p3_15:description": "Automatischer Bioethanol-Brenner mit Zündung, Sensorik und Fernsteuerung für Hotels, Clubs, Villen, Wandnischen und OEM-Projekte.",
  "p3_16:name": "Doppelseitiger Bioethanol-Kamin als Raumteiler",
  "p3_16:description": "Doppelseitiger Ethanol-Kamin mit echter Flamme für Restaurants, Lounges, Wohnräume und gewerbliche Innenräume.",
  "p3_17:name": "Dreiseitiger Bioethanol-Kamin",
  "p3_17:description": "Bioethanol-Kamin mit Flammensicht von drei Seiten, geeignet für freistehende Trennwände, Premium-Wohnräume und Lounge-Projekte.",
  "p3_18:name": "Tisch-Bioethanol-Kamin",
  "p3_18:description": "Kompakter Tischkamin mit echter Ethanolflamme für Musterwohnungen, Apartments, Restaurants und dekorative Rauminszenierung.",
  "p3_19:name": "Freistehender Bioethanol-Kamin",
  "p3_19:description": "Mobiler Ethanol-Kamin ohne Schornsteinbau, geeignet für Wohnzimmer, Lounges, Clubs und bestehende Innenräume.",
  "p3_20:name": "Runde Bioethanol-Feuerschale",
  "p3_20:description": "Runde Feuerschale mit echter Ethanolflamme für Terrassen, Resort-Hotels, Gartenlounges und halboffene Außenbereiche.",
  "p3_21:name": "Outdoor-Bioethanol-Feuertisch",
  "p3_21:description": "Linearer Feuertisch für Terrassen, Dachgärten, Außenbereiche von Hotels und gewerbliche Außensitzbereiche.",
  "p3_22:name": "Bioethanol-Kamin im Stein-Inselmodell",
  "p3_22:description": "Inselkamin mit Stein- oder Sintersteinverkleidung und Ethanol-Brenner für Wohn-, Gastronomie- und Empfangsbereiche.",
  "p3_23:name": "Linearer Bioethanol-Kamin für Hotellobbys",
  "p3_23:description": "Linearer Ethanol-Kamin in Sonderlänge für Hotellobbys, Clubs, Verkaufszentren und repräsentative Empfangsbereiche.",
  "p3_24:name": "Bioethanol-Kamin-Kit für Nischen-Einbau",
  "p3_24:description": "Einbau-Kit für Wandnischen und Medienwände mit Rahmen, Brenner, Glasaufsatz und Montagekonstruktion.",
  "p3_25:name": "OEM-Bioethanol-Brenner-Kit",
  "p3_25:description": "OEM-Brenner-Kit für Marken, Projektpartner und Serienkunden. Fertigung nach Zeichnung, Muster, Verpackung und Exportanforderung.",
  "p3_26:name": "Hängender Bioethanol-Kamin",
  "p3_26:description": "Hängender Ethanol-Kamin für hohe Wohnzimmer, Clubs, Designhotels und individuelle Innenraumkonzepte.",

  "p4_70:name": "Lineares Wasserdampf-Kaminmodul",
  "p4_70:description": "Langes 3D-Wasserdampf-Kaminmodul für Hotellobbys, Clubs, Villen und gewerbliche Medienwände. Länge, Beleuchtung, Wasseranschluss und OEM-Spezifikation sind anpassbar.",
  "p4_61:name": "Linearer 3D-Wasserdampf-Kamin mit Dekor-Holzkohle",
  "p4_61:description": "Linearer 3D-Wasserdampf-Kamin mit dekorativer Holzkohleoptik für Hotels, Villen, Clubs und gewerbliche Projekte. Geeignet für Serienbestellungen und OEM/ODM-Anpassung.",
  "p4_69:name": "Doppelseitiger Wasserdampf-Kamin als Raumteiler",
  "p4_69:description": "Raumteiler-Kamin mit Wasserdampf-Flammeneffekt auf beiden Seiten für Restaurants, Clubs, Verkaufszentren und offene Raumkonzepte.",
  "p4_68:name": "Panorama-Wasserdampf-Kamin nach Maß",
  "p4_68:description": "Panorama-Kamin mit breiter Wassernebel-Flamme für Hotels, Wohnprojekte und großformatige gewerbliche Medienwände.",
  "p4_67:name": "Dreiseitiger Wasserdampf-Kamin nach Maß",
  "p4_67:description": "Dreiseitiger Wasserdampf-Kamin mit 270-Grad-Sicht für freistehende Trennwände und repräsentative Gewerbeflächen.",
  "p4_66:name": "Runde Wasserdampf-Feuerschale",
  "p4_66:description": "Runde 3D-Wasserdampf-Feuerschale für Clubs, Showrooms, halboffene Terrassen und dekorative Installationen.",
  "p4_65:name": "Hängender Wasserdampf-Kamin",
  "p4_65:description": "Hängender Wasserdampf-Kamin für hohe Wohnräume, Clubs, Hotels und zentrale Inszenierungen in Gewerbeflächen.",
  "p4_64:name": "Wasserdampf-Kamin als Raumteiler",
  "p4_64:description": "Raumteiler-Kamin mit Wasserdampf-Flammeneffekt für eine leichte Zonierung von Innenräumen. Größe, Struktur und Wartungszugang werden projektbezogen angepasst.",
  "p4_63:name": "Design-Wasserdampf-Kamin „Auge der Sonne“",
  "p4_63:description": "Runder dekorativer Wasserdampf-Kamin für Ausstellungsräume, Clubs und Hotellobbys als visueller Mittelpunkt.",
  "p4_62:name": "Einseitiger Wasserdampf-Kamin nach Maß",
  "p4_62:description": "Einseitiger Wasserdampf-Kamin für Wand- und Medienwandlösungen in Wohn-, Hotel- und Gewerbeprojekten.",
  "p4_11:name": "Intelligenter 3D-Wasserdampf-Kamin nach Maß",
  "p4_11:description": "3D-Wasserdampf-Kamin mit LED, Luftführung und Steuerungssystem für sichere Flammenoptik ohne offene Flamme.",

  "p6_49:name": "Kompletter Kamin-Sonderanfertigungsservice",
  "p6_49:description": "Planung und Fertigung kundenspezifischer Kaminlösungen für mehrere Produktkategorien.",
  "p7_6:name": "Linearer Einbau-Elektrokamin",
  "p7_6:description": "Linearer Einbau-Elektrokamin für TV-Wände, Hotelzimmer, Musterwohnungen und Gewerbeflächen. Maße, Flammeneffekt, Struktur und OEM-Ausführung sind anpassbar.",
  "p7_7:name": "Panorama-Elektrokamin",
  "p7_7:description": "Breiter Elektrokamin für große Medienwände und Hotelsuiten. Flammenfarbe, Heizfunktion und Abmessungen können projektbezogen angepasst werden.",
  "p7_8:name": "Freistehender Elektrokamin-Ofen",
  "p7_8:description": "Steckerfertiger Elektrokamin ohne Schornstein für Apartments, Schlafzimmer, Arbeitszimmer, Gästehäuser und bestehende Innenräume.",
  "p7_9:name": "OEM-Elektrokamin-Kernmodul",
  "p7_9:description": "Elektrokamin-Kernmodul für Marken und Projektpartner. Größe, Gehäuse, Flammendisplay, Steuerplatine und Verpackung sind OEM-fähig.",
  "嵌入式 / 长条批发": "Einbau / linearer Großhandel",
  "转角 / 双面观火": "Ecke / zweiseitige Sicht",
  "四面观火": "Vierseitige Sicht",
  "圆形 / 定制": "Rund / Sondermaß",
  "半圆 / 定制": "Halbrund / Sondermaß",
  "三角形 / 定制": "Dreieck / Sondermaß",
  "拱形 / 定制": "Bogen / Sondermaß",
  "p7_10:name": "Linearer Einbau-Elektrokamin für Großhandel",
  "p7_10:description": "Linearer Einbau-Elektrokamin mit Größen von 500 bis 3000 mm für Medienwände, Hotelzimmer, Musterwohnungen, Showrooms und Projektbestellungen. Heizung, Sound, Schutzklappe, Rahmen, Farbe und OEM/ODM sind optional.",
  "p7_11:name": "Linker L-förmiger zweiseitiger Elektrokamin",
  "p7_11:description": "Linker Eck-Elektrokamin mit zweiseitigem Flammenblick für Medienwand-Ecken, Wandabschlüsse und gewerbliche Blickpunkte. Preis nach Front- und Seitenlänge.",
  "p7_12:name": "Rechter L-förmiger zweiseitiger Elektrokamin",
  "p7_12:description": "Rechter Eck-Elektrokamin mit zweiseitigem Flammenblick für rechte Eckinstallationen, Projektwände und kundenspezifische Innenräume.",
  "p7_13:name": "Dreiseitiger Elektrokamin",
  "p7_13:description": "Dreiseitiger Elektrokamin mit 270-Grad-Flammenblick für wandnahe Installationen, Hotelsuiten und gewerbliche Präsentationsflächen.",
  "p7_14:name": "Dreiseitiger Elektrokamin Typ B",
  "p7_14:description": "Dreiseitiger Elektrokamin Typ B für lange Sichtseiten und räumliche Zonierung. Großhandelspreis nach kombinierter Seitenlänge.",
  "p7_15:name": "Vierseitiger Elektrokamin",
  "p7_15:description": "Vierseitiger Elektrokamin für Inseltheken, Arbeitsplatten und zentrale Ausstellungsflächen mit Flammenblick aus vier Richtungen.",
  "p7_16:name": "Runder Elektrokamin",
  "p7_16:description": "Runder Elektrokamin mit 500-700 mm Durchmesser für Showrooms, Hotellounges und kundenspezifische Dekorstrukturen.",
  "p7_17:name": "Unterer halbrunder Elektrokamin",
  "p7_17:description": "Unterer halbrunder Elektrokamin für gebogene Wände, Sonderpaneele und Projektanpassungen von 500 bis 700 mm.",
  "p7_18:name": "Oberer halbrunder Elektrokamin",
  "p7_18:description": "Oberer halbrunder Elektrokamin für Bogenformen, Rundungen und Sonderwände mit Größen-, Farb- und Funktionsoptionen.",
  "p7_19:name": "Dreieckiger Elektrokamin",
  "p7_19:description": "Dreieckiger Elektrokamin für designorientierte Innenräume, Displays und spezielle Wandformen mit Seitenlängen von 500 bis 700 mm.",
  "p7_20:name": "Bogenförmiger Elektrokamin",
  "p7_20:description": "Bogenförmiger Elektrokamin für europäische, hochwertige und gewerbliche Innenräume mit 2DN500-2DN600 Standardgrößen und Projektanpassung.",
  "p88_51:name": "Outdoor-Feuerstelle nach Maß",
  "p88_51:description": "Outdoor-Feuerstelle für Garten, Terrasse und gewerbliche Außenbereiche mit anpassbarem Design.",
  "p8_52:name": "Kamin-Werkzeugsatz",
  "p8_52:description": "Hochwertiger Werkzeugsatz und Zubehör für Kaminprojekte.",
  "p9_1:name": "Holografisches Kamin-Anzeigemodul",
  "p9_1:description": "Holografisches Flammenmodul für Showrooms, Hotellobbys, Schaufenster, Clubs und immersive Raumkonzepte.",
  "p9_2:name": "Projektions-Kaminsystem",
  "p9_2:description": "Projektionssystem für Heimkino, Ausstellungen, Schaufenster und immersive Raumkonzepte mit großformatigen Flammen- und Themenvideos.",
  "p9_3:name": "Immersive Flammen-Videowand",
  "p9_3:description": "Modulare Flammen-Videowand für Marken-Showrooms, Hotellobbys, Bühnenhintergründe und Gewerbeflächen.",
};

export default de_data;
