const de_data: Record<string, string> = {
  "p1:name": "Holzkamin",
  "p2:name": "Gaskamin",
  "p3:name": "Alkoholkamin",
  "p4:name": "Nebelkamin",
  "p7:name": "Elektrokamin",
  "p6:name": "Kundenspezifischer Kamin",
  "p88:name": "Außenfeuerstelle",
  "p8:name": "Zubehör",
  "独立式": "Freistehend",
  "嵌入式": "Einbaugerät",
  "壁挂式": "Wandmontiert",
  "悬挂式": "Hängend",
  "悬挂/独立/嵌入": "Hängend / Freistehend / Einbau",
  "独立/嵌入": "Freistehend / Einbau",
  "附件": "Zubehör",
  "西班牙": "Spanien",
  "丹麦": "Dänemark",
  "奥地利": "Österreich",
  "瑞士": "Schweiz",
  "荷兰": "Niederlande",
  "中国": "China",
  "p1_71:name": "Lacunza Altea Freistehender Holzofen mit Backofen",
  "p1_71:description": "Spanischer Lacunza Altea freistehender Holzofen mit Backofen, vereint Kochen und Heizen in einem klassischen Design.",
  "p1_1:name": "Lacunza Stelar 93 Freistehender Holzkamin",
  "p1_1:description": "Spanischer Lacunza Stelar 93 freistehender Holzkamin, elegantes Design mit hervorragender Heizeffizienz.",
  "p1_45:name": "Lacunza Sara Einbau-Holzkamin",
  "p1_45:description": "Spanischer Lacunza Sara Einbau-Holzkamin, platzsparendes minimalistisches Design.",
  "p1_44:name": "Lacunza Oslo Freistehender Holzofen",
  "p1_44:description": "Spanischer Lacunza Oslo freistehender Holzofen mit Kochfunktion.",
  "p1_43:name": "Lacunza Nickel Doppelseitiger Einbau-Holzkamin",
  "p1_43:description": "Spanischer Lacunza Nickel doppelseitiger Einbau-Holzkamin, beidseitige Glasscheiben für Feuerblick von beiden Seiten.",
  "p1_42:name": "Lacunza K2 800 Einbau-Holzkamin",
  "p1_42:description": "Spanischer Lacunza K2 800 Einbau-Holzkamin mit großer Aussichtsfläche.",
  "p1_41:name": "Lacunza Itaca Einbau-Holzkamin",
  "p1_41:description": "Spanischer Lacunza Itaca einseitiger Einbau-Holzkamin, klassisches Design mit effizienter Heizung.",
  "p1_39:name": "Lacunza CM 300R Eck-Freistehender Holzkamin",
  "p1_39:description": "Spanischer Lacunza CM 300R Eck-freistehender Holzkamin, entwickelt für Eckinstallation.",
  "p1_38:name": "Lacunza Clasica 7T Holzofen mit Backofen",
  "p1_38:description": "Spanischer Lacunza Clasica 7T Holzofen mit Backofen, europäischer Landhausstil.",
  "p1_37:name": "Lacunza Atlantic 603 Freistehender Holzkamin",
  "p1_37:description": "Spanischer Lacunza Atlantic 603 freistehender Holzkamin, elegante Optik mit leistungsstarker Heizung.",
  "p1_36:name": "Lacunza Adour 700ST Einbau-Holzkamin",
  "p1_36:description": "Spanischer Lacunza Adour 700ST Einbau-Holzkamin, klare Linien, modernes Design.",
  "p1_61:name": "Rais Q TEE 2C Freistehender Holzkamin",
  "p1_61:description": "Dänischer Rais Q TEE 2C freistehender Holzkamin, nordisch-minimalistisches Design, hocheffiziente Verbrennung.",
  "p1_60:name": "Rais Nexo Serie Freistehender Holzkamin",
  "p1_60:description": "Dänischer Rais Nexo Serie freistehender Holzkamin, moderner minimalistischer Stil.",
  "p1_59:name": "Rais Juno L Freistehender Holzkamin",
  "p1_59:description": "Dänischer Rais Juno L freistehender Holzkamin mit rundem Sichtfenster, einzigartiges Design.",
  "p1_58:name": "Rais Caro 90 Freistehender Holzkamin",
  "p1_58:description": "Dänischer Rais Caro 90 freistehender Holzkamin, elegante zylindrische Form.",
  "p1_28:name": "Rais Viva L Serie Freistehender Holzkamin",
  "p1_28:description": "Dänischer Rais Viva L Serie freistehender Holzkamin, dynamischer Flammeneffekt.",
  "p1_27:name": "Rais Visio 3 Dreiseitiger Einbau-Holzkamin",
  "p1_27:description": "Dänischer Rais Visio 3 dreiseitiger Einbau-Holzkamin, 270° Panoramablick auf die Flammen.",
  "p1_26:name": "Rais Q-TEE 2 Freistehender Holzkamin",
  "p1_26:description": "Dänischer Rais Q-TEE 2 freistehender Holzkamin, geometrisches künstlerisches Design.",
  "p1_25:name": "Rais Q-BE Eckblick Freistehender Holzkamin",
  "p1_25:description": "Dänischer Rais Q-BE Eckblick freistehender Holzkamin, innovatives Winkeldesign.",
  "p1_24:name": "Rais Pilar Freistehender Holzkamin",
  "p1_24:description": "Dänischer Rais Pilar freistehender Holzkamin, säulenförmiges Design, schlicht und elegant.",
  "p1_23:name": "Rais Bionic Fire Doppelkammer-Holzkamin",
  "p1_23:description": "Dänischer Rais Bionic Fire Doppelkammer-Holzkamin, innovative Doppelverbrennungstechnologie.",
  "p1_22:name": "Haas+sohn Treviso Speckstein-Holzkamin",
  "p1_22:description": "Österreichischer Haas+sohn Treviso Speckstein-Holzkamin, Speckstein-Wärmespeicher für langanhaltende Wärme.",
  "p1_21:name": "Haas+sohn Kuopio-II Speckstein-Holzkamin",
  "p1_21:description": "Österreichischer Haas+sohn Kuopio-II Speckstein-Holzkamin, klassische nordische Speckstein-Handwerkskunst.",
  "p1_20:name": "Haas+sohn Ficus-II-RLU Freistehender Holzkamin",
  "p1_20:description": "Österreichischer Haas+sohn Ficus-II-RLU freistehender Holzkamin, elegantes geschwungenes Design.",
  "p1_2:name": "Haas+sohn Aruba Easy Speckstein-Holzofen",
  "p1_2:description": "Österreichischer Haas+sohn Aruba Easy Speckstein-Holzofen, einfache Bedienung, effiziente Wärmespeicherung.",
  "p1_35:name": "Ruegg Tillia Dreiseitiger Einbau-Holzkamin",
  "p1_35:description": "Schweizer Ruegg Tillia dreiseitiger Einbau-Holzkamin, Schweizer Präzisionsqualität.",
  "p1_34:name": "Ruegg Rondeo Einbau-Holzkamin mit gebogenem Glas",
  "p1_34:description": "Schweizer Ruegg Rondeo Einbau-Holzkamin mit gebogenem Glas, einzigartiges Design.",
  "p1_33:name": "Ruegg RII Eck-Einbau-Holzkamin",
  "p1_33:description": "Schweizer Ruegg RII Eck-Einbau-Holzkamin, platzsparendes Eckdesign.",
  "p1_18:name": "Ruegg Odeon 270° Gebogener Hänge-Holzkamin",
  "p1_18:description": "Schweizer Ruegg Odeon 270° gebogener Hänge-Holzkamin, künstlerisches Hängedesign mit Panoramablick.",
  "p2_56:name": "Element4 Lucius 140 Einbau-Gaskamin",
  "p2_56:description": "Niederländischer Element4 Lucius 140 Einbau-Gaskamin, große Sichtfläche, moderne Gasttechnologie.",
  "p2_55:name": "Element4 Tenore 140 Einbau-Gaskamin",
  "p2_55:description": "Niederländischer Element4 Tenore 140 Einbau-Gaskamin, lineares minimalistisches Design.",
  "p2_54:name": "Element4 Summum 100F Einbau-Gaskamin",
  "p2_54:description": "Niederländischer Element4 Summum 100F Einbau-Gaskamin, Premium-Gaskamin-Erlebnis.",
  "p2_53:name": "Element4 Sky Indoor Serie Gaskamin",
  "p2_53:description": "Niederländischer Element4 Sky Indoor Serie Gaskamin, nahtloses Innen- und Außendesign.",
  "p2_31:name": "Element4 Trisore 140 Dreiseitiger Gaskamin",
  "p2_31:description": "Niederländischer Element4 Trisore 140 dreiseitiger Einbau-Gaskamin, Panorama-Flammenblick.",
  "p2_29:name": "Element4 Bidore 100 Eck-Gaskamin",
  "p2_29:description": "Niederländischer Element4 Bidore 100 Eck-Einbau-Gaskamin, beidseitiger Eckblick.",
  "p3_14:name": "Alkoholkamin (Anpassbar)",
  "p3_14:description": "Bioethanol-Kamin, Größe und Aussehen anpassbar, umweltfreundlich.",
  "p4_70:name": "Wandmontierter geteilter Nebelkamin (Anpassbar)",
  "p4_70:description": "3D-Nebelkamin mit wandmontiertem geteiltem Design, anpassbare Flammeneffekte.",
  "p4_69:name": "Doppelseitiger Nebelkamin (Anpassbar)",
  "p4_69:description": "Doppelseitiger Nebelkamin, ideal für Raumteilerinstallation.",
  "p4_68:name": "Panorama-Nebelkamin (Anpassbar)",
  "p4_68:description": "Panorama-Nebelkamin mit extremer Breitbild-Flammenansicht.",
  "p4_67:name": "Dreiseitiger Nebelkamin (Anpassbar)",
  "p4_67:description": "Dreiseitiger Nebelkamin mit 270° Flammenblicken.",
  "p4_66:name": "Runder Nebelkamin (Anpassbar)",
  "p4_66:description": "Runder Nebelkamin mit einzigartigem kreisförmigem Design.",
  "p4_65:name": "UFO Hänge-Nebelkamin (Anpassbar)",
  "p4_65:description": "UFO-förmiger Hänge-Nebelkamin mit futuristischem Design.",
  "p4_64:name": "Raumteiler-Bildschirm-Nebelkamin (Anpassbar)",
  "p4_64:description": "Nebelkamin, der auch als Raumteiler oder Bildschirm dient.",
  "p4_62:name": "Einseitiger Nebelkamin (Anpassbar)",
  "p4_62:description": "Einseitiger Nebelkamin, klassisches Design für Wandinstallation.",
  "p4_11:name": "Intelligenter 3D-Nebelkamin (Anpassbar)",
  "p4_11:description": "Intelligenter 3D-Nebelkamin mit intelligenter Steuerung und 3D-Flammeneffekten.",
  "p6_49:name": "Kompletter Kundenspezifischer Kaminservice",
  "p6_49:description": "Rundum-Service für kundenspezifische Kaminplanung und -installation für alle Kategorien.",
  "p7_6:name": "Elektrokamin (Anpassbar)",
  "p7_6:description": "Elektrokamin mit realistischen Flammeneffekten, anpassbare Größe, einfache Installation.",
  "p88_51:name": "Außenfeuerstelle (Anpassbar)",
  "p88_51:description": "Außenfeuerstelle für Garten und Terrasse, anpassbare Designs.",
  "p8_52:name": "Kamin-Werkzeugsatz",
  "p8_52:description": "Dänischer Rais Kamin-Werkzeugsatz, hochwertiges Zubehör.",
};

export default de_data;
