const en: Record<string, string> = {
  // Installation types
  "独立式": "Freestanding",
  "嵌入式": "Built-in",
  "壁挂式": "Wall-mounted",
  "悬挂式": "Suspended",
  "悬挂/独立/嵌入": "Suspended / Freestanding / Built-in",
  "独立/嵌入": "Freestanding / Built-in",
  "附件": "Accessories",

  // Countries
  "西班牙": "Spain",
  "丹麦": "Denmark",
  "奥地利": "Austria",
  "瑞士": "Switzerland",
  "荷兰": "Netherlands",
  "中国": "China",
  "嵌入式 / 长条批发": "Built-in / linear wholesale",
  "转角 / 双面观火": "Corner / two-sided view",
  "四面观火": "Four-sided view",
  "圆形 / 定制": "Round / custom",
  "半圆 / 定制": "Half-round / custom",
  "三角形 / 定制": "Triangle / custom",
  "拱形 / 定制": "Arch / custom",
  "p7_10:name": "Linear Built-In Electric Fireplace Wholesale Series",
  "p7_10:description": "Linear built-in electric fireplace wholesale series covering 500-3000 mm standard sizes for media walls, hotel rooms, show flats, showrooms, and project procurement. Heating, sound, guard door, frame, color, and OEM/ODM options are available.",
  "p7_11:name": "Left-Corner Two-Sided Electric Fireplace",
  "p7_11:description": "Left-corner two-sided electric fireplace for corner media walls, wall returns, and commercial feature corners. Pricing is based on the front and side length combination.",
  "p7_12:name": "Right-Corner Two-Sided Electric Fireplace",
  "p7_12:description": "Right-corner two-sided electric fireplace for right-hand corner installation, feature-wall returns, and custom project interiors with configurable dimensions and controls.",
  "p7_13:name": "Three-Sided Electric Fireplace",
  "p7_13:description": "Three-sided electric fireplace for wall-side non-recessed installation, feature displays, hotel suites, and commercial spaces with front and two-side flame viewing.",
  "p7_14:name": "Three-Sided B Electric Fireplace",
  "p7_14:description": "Three-sided B electric fireplace for long-side display and two-direction spatial division. Wholesale pricing is calculated by multi-side length combination.",
  "p7_15:name": "Four-Sided Electric Fireplace",
  "p7_15:description": "Four-sided electric fireplace for island counters, tabletops, and central display positions where flame effects need to be visible from all four sides.",
  "p7_16:name": "Round Electric Fireplace",
  "p7_16:description": "Round electric fireplace with 500-700 mm diameter options for interior displays, brand showrooms, hotel lounge areas, and custom decorative structures.",
  "p7_17:name": "Lower Half-Round Electric Fireplace",
  "p7_17:description": "Lower half-round electric fireplace for curved walls, shaped decorative panels, and custom project interiors, available from 500 to 700 mm.",
  "p7_18:name": "Upper Half-Round Electric Fireplace",
  "p7_18:description": "Upper half-round electric fireplace for arched, curved, and shaped feature-wall projects with configurable size, color, and functions.",
  "p7_19:name": "Triangle Electric Fireplace",
  "p7_19:description": "Triangle electric fireplace for design-focused interiors, display installations, and special wall structures with 500-700 mm side-length wholesale specifications.",
  "p7_20:name": "Arch Electric Fireplace",
  "p7_20:description": "Arch electric fireplace for European-style, luxury, and commercial display interiors, with 2DN500-2DN600 standard sizes and project customization support.",
  "嵌入式 / 语音控制": "Built-in / voice control",
  "嵌入式 / 音乐播放": "Built-in / music playback",
  "嵌入式 / 户外防水": "Built-in / outdoor waterproof",
  "圆形 / 仿真木柴": "Round / decorative logs",
  "独立式 / 半球装饰": "Freestanding / hemisphere decorative",
  "p4_71:name": "Voice-Control Linear Built-In 3D Mist Fireplace",
  "p4_71:description": "Voice-control linear built-in 3D water vapor fireplace for hotels, villas, clubs, showrooms, and commercial feature walls. Length, lighting, packing, and OEM/ODM details can be customized for wholesale projects.",
  "p4_72:name": "Music Playback Linear Built-In 3D Mist Fireplace",
  "p4_72:description": "Music playback linear built-in 3D mist fireplace for show flats, hotel suites, clubs, and display spaces where atmosphere and flame presentation matter.",
  "p4_73:name": "Outdoor Waterproof Linear Built-In 3D Mist Fireplace",
  "p4_73:description": "Outdoor waterproof linear built-in 3D mist fireplace for patios, terraces, hotel outdoor seating, commercial lounge areas, and semi-outdoor projects.",
  "p4_74:name": "Round Built-In 3D Mist Fireplace with Decorative Logs",
  "p4_74:description": "Round built-in 3D mist fireplace with decorative logs for clubs, showrooms, hotel lounge areas, and decorative project installations.",
  "p4_75:name": "Freestanding Hemisphere Decorative Mist Fireplace",
  "p4_75:description": "Freestanding hemisphere decorative 3D mist fireplace for hotel lobbies, clubs, showrooms, commercial spaces, and interior display areas without chimney work.",
};

export default en;
