const es_data: Record<string, string> = {
  "p1:name": "Chimenea de Leña",
  "p2:name": "Chimenea de Gas",
  "p3:name": "Chimenea de Alcohol",
  "p4:name": "Chimenea de Niebla",
  "p7:name": "Chimenea Eléctrica",
  "p9:name": "Chimenea Holográfica",
  "p6:name": "Chimenea Personalizada",
  "p88:name": "Fuego Exterior",
  "p8:name": "Accesorios",
  "独立式": "Independiente",
  "嵌入式": "Empotrable",
  "壁挂式": "De pared",
  "悬挂式": "Colgante",
  "悬挂/独立/嵌入": "Colgante / Independiente / Empotrable",
  "独立/嵌入": "Independiente / Empotrable",
  "附件": "Accesorios",
  "西班牙": "España",
  "丹麦": "Dinamarca",
  "奥地利": "Austria",
  "瑞士": "Suiza",
  "荷兰": "Países Bajos",
  "中国": "China",
  "p1_71:name": "Lacunza Altea Estufa de Leña Autónoma con Horno",
  "p1_71:description": "Estufa de leña autónoma española Lacunza Altea con horno, combinando cocina y calefacción.",
  "p1_1:name": "Lacunza Stelar 93 Chimenea de Leña Autónoma",
  "p1_1:description": "Chimenea de leña autónoma española Lacunza Stelar 93, diseño elegante.",
  "p1_45:name": "Lacunza Sara Chimenea de Leña Empotrable",
  "p1_45:description": "Chimenea de leña empotrable española Lacunza Sara, diseño minimalista.",
  "p1_44:name": "Lacunza Oslo Estufa de Leña Autónoma",
  "p1_44:description": "Estufa de leña autónoma española Lacunza Oslo con función de cocina.",
  "p1_43:name": "Lacunza Nickel Chimenea de Leña Empotrable Doble Cara",
  "p1_43:description": "Chimenea de leña empotrable doble cara española Lacunza Nickel.",
  "p1_42:name": "Lacunza K2 800 Chimenea de Leña Empotrable",
  "p1_42:description": "Chimenea de leña empotrable española Lacunza K2 800 con gran ventanal.",
  "p1_41:name": "Lacunza Itaca Chimenea de Leña Empotrable",
  "p1_41:description": "Chimenea de leña empotrable simple cara española Lacunza Itaca.",
  "p1_39:name": "Lacunza CM 300R Chimenea de Leña Autónoma de Esquina",
  "p1_39:description": "Chimenea de leña autónoma de esquina española Lacunza CM 300R.",
  "p1_38:name": "Lacunza Clasica 7T Estufa de Leña con Horno",
  "p1_38:description": "Estufa de leña española Lacunza Clasica 7T con horno, estilo campestre europeo.",
  "p1_37:name": "Lacunza Atlantic 603 Chimenea de Leña Autónoma",
  "p1_37:description": "Chimenea de leña autónoma española Lacunza Atlantic 603, aspecto imponente.",
  "p1_36:name": "Lacunza Adour 700ST Chimenea de Leña Empotrable",
  "p1_36:description": "Chimenea de leña empotrable española Lacunza Adour 700ST, líneas limpias.",
  "p1_61:name": "Rais Q TEE 2C Chimenea de Leña Autónoma",
  "p1_61:description": "Chimenea de leña autónoma danesa Rais Q TEE 2C, diseño nórdico minimalista.",
  "p1_60:name": "Rais Nexo Serie Chimenea de Leña Autónoma",
  "p1_60:description": "Chimenea de leña autónoma danesa Rais Nexo serie, estilo minimalista moderno.",
  "p1_59:name": "Rais Juno L Chimenea de Leña Autónoma",
  "p1_59:description": "Chimenea de leña autónoma danesa Rais Juno L con ventana circular.",
  "p1_58:name": "Rais Caro 90 Chimenea de Leña Autónoma",
  "p1_58:description": "Chimenea de leña autónoma danesa Rais Caro 90, forma cilíndrica elegante.",
  "p1_28:name": "Rais Viva L Serie Chimenea de Leña Autónoma",
  "p1_28:description": "Chimenea de leña autónoma danesa Rais Viva L serie, efecto dinámico.",
  "p1_27:name": "Rais Visio 3 Chimenea de Leña Empotrable Tres Caras",
  "p1_27:description": "Chimenea de leña empotrable tres caras danesa Rais Visio 3, vista 270°.",
  "p1_26:name": "Rais Q-TEE 2 Chimenea de Leña Autónoma",
  "p1_26:description": "Chimenea de leña autónoma danesa Rais Q-TEE 2, diseño geométrico.",
  "p1_25:name": "Rais Q-BE Chimenea de Leña Autónoma Vista Angular",
  "p1_25:description": "Chimenea de leña autónoma danesa Rais Q-BE vista angular, diseño innovador.",
  "p1_24:name": "Rais Pilar Chimenea de Leña Autónoma",
  "p1_24:description": "Chimenea de leña autónoma danesa Rais Pilar, diseño columnar.",
  "p1_23:name": "Rais Bionic Fire Chimenea de Leña Doble Cámara",
  "p1_23:description": "Chimenea de leña danesa Rais Bionic Fire de doble cámara, tecnología innovadora.",
  "p1_22:name": "Haas+sohn Treviso Chimenea de Leña de Esteatita",
  "p1_22:description": "Chimenea de leña de esteatita austriaca Haas+sohn Treviso, calor duradero.",
  "p1_21:name": "Haas+sohn Kuopio-II Chimenea de Leña de Esteatita",
  "p1_21:description": "Chimenea de leña de esteatita austriaca Haas+sohn Kuopio-II.",
  "p1_20:name": "Haas+sohn Ficus-II-RLU Chimenea de Leña Autónoma",
  "p1_20:description": "Chimenea de leña autónoma austriaca Haas+sohn Ficus-II-RLU, diseño curvo.",
  "p1_2:name": "Haas+sohn Aruba Easy Estufa de Leña de Esteatita",
  "p1_2:description": "Estufa de leña de esteatita austriaca Haas+sohn Aruba Easy.",
  "p1_35:name": "Ruegg Tillia Chimenea de Leña Empotrable Tres Caras",
  "p1_35:description": "Chimenea de leña empotrable tres caras suiza Ruegg Tillia, precisión suiza.",
  "p1_34:name": "Ruegg Rondeo Chimenea de Leña Empotrable Curva",
  "p1_34:description": "Chimenea de leña empotrable suiza Ruegg Rondeo con vidrio curvo único.",
  "p1_33:name": "Ruegg RII Chimenea de Leña Empotrable de Esquina",
  "p1_33:description": "Chimenea de leña empotrable de esquina suiza Ruegg RII.",
  "p1_18:name": "Ruegg Odeon 270° Chimenea de Leña Suspendida Curva",
  "p1_18:description": "Chimenea de leña suspendida curva suiza Ruegg Odeon 270°, diseño artístico.",
  "p2_56:name": "Element4 Lucius 140 Chimenea de Gas Empotrable",
  "p2_56:description": "Chimenea de gas empotrable neerlandesa Element4 Lucius 140.",
  "p2_55:name": "Element4 Tenore 140 Chimenea de Gas Empotrable",
  "p2_55:description": "Chimenea de gas empotrable neerlandesa Element4 Tenore 140, diseño minimalista.",
  "p2_54:name": "Element4 Summum 100F Chimenea de Gas Empotrable",
  "p2_54:description": "Chimenea de gas empotrable neerlandesa Element4 Summum 100F, experiencia premium.",
  "p2_53:name": "Element4 Sky Serie Interior Chimenea de Gas",
  "p2_53:description": "Chimenea de gas interior neerlandesa Element4 Sky, diseño integrado.",
  "p2_31:name": "Element4 Trisore 140 Chimenea de Gas Tres Caras",
  "p2_31:description": "Chimenea de gas tres caras neerlandesa Element4 Trisore 140, vista panorámica.",
  "p2_29:name": "Element4 Bidore 100 Chimenea de Gas de Esquina",
  "p2_29:description": "Chimenea de gas de esquina neerlandesa Element4 Bidore 100.",
  "p3_14:name": "Chimenea de Alcohol (Personalizable)",
  "p3_14:description": "Chimenea de bioetanol, tamaño y apariencia personalizables, ecológica.",
  "p4_70:name": "Chimenea de Niebla Montada Dividida (Personalizable)",
  "p4_70:description": "Chimenea de niebla 3D montada dividida, efectos personalizables.",
  "p4_61:name": "Chimenea lineal 3D de vapor con troncos de carbón decorativos",
  "p4_61:description": "Chimenea lineal de vapor de agua 3D con efecto de carbón decorativo para hoteles, villas, clubes y proyectos comerciales al por mayor u OEM/ODM.",
  "p4_69:name": "Chimenea de Niebla Doble Cara (Personalizable)",
  "p4_69:description": "Chimenea de niebla doble cara, ideal para división de ambientes.",
  "p4_68:name": "Chimenea de Niebla Panorámica (Personalizable)",
  "p4_68:description": "Chimenea de niebla panorámica ultra ancha.",
  "p4_67:name": "Chimenea de Niebla Tres Caras (Personalizable)",
  "p4_67:description": "Chimenea de niebla tres caras con vista 270°.",
  "p4_66:name": "Chimenea de Niebla Redonda (Personalizable)",
  "p4_66:description": "Chimenea de niebla redonda de diseño circular único.",
  "p4_65:name": "Chimenea de Niebla Colgante OVNI (Personalizable)",
  "p4_65:description": "Chimenea de niebla colgante en forma de OVNI.",
  "p4_64:name": "Chimenea de Niebla Divisoria (Personalizable)",
  "p4_64:description": "Chimenea de niebla que funciona como divisor o pantalla.",
  "p4_62:name": "Chimenea de Niebla Simple Cara (Personalizable)",
  "p4_62:description": "Chimenea de niebla simple cara, diseño clásico.",
  "p4_11:name": "Chimenea de Niebla 3D Inteligente (Personalizable)",
  "p4_11:description": "Chimenea de niebla 3D inteligente con control inteligente.",
  "嵌入式 / 语音控制": "Empotrada / control por voz",
  "嵌入式 / 音乐播放": "Empotrada / música",
  "嵌入式 / 户外防水": "Empotrada / exterior impermeable",
  "圆形 / 仿真木柴": "Redonda / leños decorativos",
  "独立式 / 半球装饰": "Independiente / hemisférica",
  "p4_71:name": "Chimenea lineal 3D de vapor de agua con control por voz",
  "p4_71:description": "Chimenea lineal empotrada 3D de vapor de agua con control por voz para hoteles, villas, clubes, showrooms y paredes comerciales. Longitud, iluminación, embalaje y OEM/ODM personalizables.",
  "p4_72:name": "Chimenea lineal 3D de vapor de agua con música",
  "p4_72:description": "Chimenea lineal empotrada 3D de vapor de agua con reproducción musical para pisos piloto, suites de hotel, clubes y espacios de exhibición.",
  "p4_73:name": "Chimenea lineal 3D de vapor de agua impermeable para exterior",
  "p4_73:description": "Chimenea lineal 3D de vapor de agua impermeable para terrazas, zonas exteriores de hotel, lounges comerciales y proyectos semi-exteriores.",
  "p4_74:name": "Chimenea redonda empotrada 3D de vapor de agua con leños decorativos",
  "p4_74:description": "Chimenea redonda empotrada 3D de vapor de agua con leños decorativos para clubes, showrooms, lounges de hotel e instalaciones decorativas.",
  "p4_75:name": "Chimenea decorativa hemisférica independiente de vapor de agua",
  "p4_75:description": "Chimenea decorativa hemisférica independiente 3D de vapor de agua para lobbies de hotel, clubes, showrooms y espacios comerciales sin chimenea.",
  "p6_49:name": "Servicio Completo de Chimenea Personalizada",
  "p6_49:description": "Servicio integral de diseño e instalación de chimeneas personalizadas.",
  "p7_6:name": "Chimenea Eléctrica (Personalizable)",
  "p7_6:description": "Chimenea eléctrica con efectos de llama realistas.",
  "嵌入式 / 长条批发": "Empotrada / lineal mayorista",
  "转角 / 双面观火": "Esquina / dos caras",
  "四面观火": "Vista de cuatro caras",
  "圆形 / 定制": "Redonda / personalizada",
  "半圆 / 定制": "Semirredonda / personalizada",
  "三角形 / 定制": "Triangular / personalizada",
  "拱形 / 定制": "Arqueada / personalizada",
  "p7_10:name": "Chimenea eléctrica lineal empotrada para mayoristas",
  "p7_10:description": "Chimenea eléctrica lineal empotrada de 500 a 3000 mm para paredes de TV, hoteles, pisos piloto, showrooms y proyectos en lote. Calefacción, sonido, puerta protectora, marco, color y OEM/ODM opcionales.",
  "p7_11:name": "Chimenea eléctrica en L izquierda de dos caras",
  "p7_11:description": "Chimenea eléctrica de esquina izquierda con vista de llama por dos lados para esquinas de pared multimedia y espacios comerciales. Precio según largo frontal y lateral.",
  "p7_12:name": "Chimenea eléctrica en L derecha de dos caras",
  "p7_12:description": "Chimenea eléctrica de esquina derecha con vista de llama por dos lados para instalaciones de esquina y proyectos personalizados.",
  "p7_13:name": "Chimenea eléctrica de tres caras",
  "p7_13:description": "Chimenea eléctrica de tres caras con vista de llama de 270 grados para instalaciones junto a pared, suites de hotel y espacios comerciales.",
  "p7_14:name": "Chimenea eléctrica de tres caras tipo B",
  "p7_14:description": "Chimenea eléctrica de tres caras tipo B para lados largos visibles y división espacial. Precio mayorista según longitudes combinadas.",
  "p7_15:name": "Chimenea eléctrica de cuatro caras",
  "p7_15:description": "Chimenea eléctrica de cuatro caras para islas, encimeras y zonas centrales con efecto de llama visible desde todos los lados.",
  "p7_16:name": "Chimenea eléctrica redonda",
  "p7_16:description": "Chimenea eléctrica redonda con diámetros de 500-700 mm para showrooms, lounges de hotel y estructuras decorativas personalizadas.",
  "p7_17:name": "Chimenea eléctrica semirredonda inferior",
  "p7_17:description": "Chimenea eléctrica semirredonda inferior para paredes curvas, paneles especiales y proyectos personalizados de 500 a 700 mm.",
  "p7_18:name": "Chimenea eléctrica semirredonda superior",
  "p7_18:description": "Chimenea eléctrica semirredonda superior para arcos, curvas y paredes especiales con opciones de medida, color y función.",
  "p7_19:name": "Chimenea eléctrica triangular",
  "p7_19:description": "Chimenea eléctrica triangular para interiores de diseño, instalaciones de exhibición y paredes especiales con lados de 500 a 700 mm.",
  "p7_20:name": "Chimenea eléctrica arqueada",
  "p7_20:description": "Chimenea eléctrica arqueada para espacios europeos, premium y comerciales con tamaños 2DN500-2DN600 y personalización de proyecto.",
  "p88_51:name": "Fuego Exterior (Personalizable)",
  "p88_51:description": "Fuego exterior para jardín y patio, diseños personalizables.",
  "p8_52:name": "Juego de Herramientas de Chimenea",
  "p8_52:description": "Juego de herramientas de chimenea danés Rais, accesorios de alta calidad.",
  "燃木壁炉": "Chimenea de leña",
  "悬挂式 / 烟囱款": "Suspendida / con chimenea",
  "装饰 / 落地款": "Decorativa / independiente",
  "球形 / 装饰款": "Esférica / decorativa",
  "p1_72:name": "Chimenea de leña suspendida tipo platillo",
  "p1_72:description": "Chimenea de leña suspendida tipo platillo para villas, lodges, clubes y lounges comerciales. Incluye chimenea estándar de 2 m; brida, color, secciones, embalaje y detalles OEM/ODM se confirman por proyecto.",
  "p3_27:name": "Chimenea de etanol suspendida tipo platillo",
  "p3_27:description": "Chimenea de bioetanol suspendida tipo platillo para villas, hoteles, clubes, pisos piloto y proyectos decorativos comerciales con datos mayoristas y embalaje de exportación.",
  "p4_76:name": "Chimenea 3D de vapor de agua suspendida tipo platillo",
  "p4_76:description": "Chimenea 3D de vapor de agua suspendida para lobbies de hotel, clubes, villas y espacios interiores que necesitan ambiente de llama sin fuego abierto.",
  "p3_28:name": "Chimenea decorativa independiente de etanol",
  "p3_28:description": "Chimenea decorativa independiente de etanol para salones de villa, lounges de hotel, clubes, restaurantes y showrooms con tallas mayoristas y datos de embalaje.",
  "p4_77:name": "Chimenea decorativa independiente 3D de vapor de agua",
  "p4_77:description": "Chimenea decorativa independiente 3D de vapor de agua para hoteles, clubes, showrooms y proyectos residenciales donde se prefiere evitar llama abierta.",
  "p3_29:name": "Chimenea decorativa esférica de etanol",
  "p3_29:description": "Chimenea decorativa esférica de etanol para villas, hoteles, restaurantes, clubes y showrooms, con varios diámetros para suministro mayorista.",
};

export default es_data;
