const es_data: Record<string, string> = {
  "p1:name": "Chimenea de Leña",
  "p2:name": "Chimenea de Gas",
  "p3:name": "Chimenea de Alcohol",
  "p4:name": "Chimenea de Niebla",
  "p7:name": "Chimenea Eléctrica",
  "p6:name": "Chimenea Personalizada",
  "p88:name": "Fuego Exterior",
  "p8:name": "Accesorios",
  "独立式": "Independiente",
  "嵌入式": "Empotrable",
  "壁挂式": "De pared",
  "悬挂式": "Colgante",
  "悬挂/独立/嵌入": "Colgante / Independiente / Empotrable",
  "独立/嵌入": "Independiente / Empotrable",
  "附件": "Accesorios",
  "西班牙": "España",
  "丹麦": "Dinamarca",
  "奥地利": "Austria",
  "瑞士": "Suiza",
  "荷兰": "Países Bajos",
  "中国": "China",
  "p1_71:name": "Lacunza Altea Estufa de Leña Autónoma con Horno",
  "p1_71:description": "Estufa de leña autónoma española Lacunza Altea con horno, combinando cocina y calefacción.",
  "p1_1:name": "Lacunza Stelar 93 Chimenea de Leña Autónoma",
  "p1_1:description": "Chimenea de leña autónoma española Lacunza Stelar 93, diseño elegante.",
  "p1_45:name": "Lacunza Sara Chimenea de Leña Empotrable",
  "p1_45:description": "Chimenea de leña empotrable española Lacunza Sara, diseño minimalista.",
  "p1_44:name": "Lacunza Oslo Estufa de Leña Autónoma",
  "p1_44:description": "Estufa de leña autónoma española Lacunza Oslo con función de cocina.",
  "p1_43:name": "Lacunza Nickel Chimenea de Leña Empotrable Doble Cara",
  "p1_43:description": "Chimenea de leña empotrable doble cara española Lacunza Nickel.",
  "p1_42:name": "Lacunza K2 800 Chimenea de Leña Empotrable",
  "p1_42:description": "Chimenea de leña empotrable española Lacunza K2 800 con gran ventanal.",
  "p1_41:name": "Lacunza Itaca Chimenea de Leña Empotrable",
  "p1_41:description": "Chimenea de leña empotrable simple cara española Lacunza Itaca.",
  "p1_39:name": "Lacunza CM 300R Chimenea de Leña Autónoma de Esquina",
  "p1_39:description": "Chimenea de leña autónoma de esquina española Lacunza CM 300R.",
  "p1_38:name": "Lacunza Clasica 7T Estufa de Leña con Horno",
  "p1_38:description": "Estufa de leña española Lacunza Clasica 7T con horno, estilo campestre europeo.",
  "p1_37:name": "Lacunza Atlantic 603 Chimenea de Leña Autónoma",
  "p1_37:description": "Chimenea de leña autónoma española Lacunza Atlantic 603, aspecto imponente.",
  "p1_36:name": "Lacunza Adour 700ST Chimenea de Leña Empotrable",
  "p1_36:description": "Chimenea de leña empotrable española Lacunza Adour 700ST, líneas limpias.",
  "p1_61:name": "Rais Q TEE 2C Chimenea de Leña Autónoma",
  "p1_61:description": "Chimenea de leña autónoma danesa Rais Q TEE 2C, diseño nórdico minimalista.",
  "p1_60:name": "Rais Nexo Serie Chimenea de Leña Autónoma",
  "p1_60:description": "Chimenea de leña autónoma danesa Rais Nexo serie, estilo minimalista moderno.",
  "p1_59:name": "Rais Juno L Chimenea de Leña Autónoma",
  "p1_59:description": "Chimenea de leña autónoma danesa Rais Juno L con ventana circular.",
  "p1_58:name": "Rais Caro 90 Chimenea de Leña Autónoma",
  "p1_58:description": "Chimenea de leña autónoma danesa Rais Caro 90, forma cilíndrica elegante.",
  "p1_28:name": "Rais Viva L Serie Chimenea de Leña Autónoma",
  "p1_28:description": "Chimenea de leña autónoma danesa Rais Viva L serie, efecto dinámico.",
  "p1_27:name": "Rais Visio 3 Chimenea de Leña Empotrable Tres Caras",
  "p1_27:description": "Chimenea de leña empotrable tres caras danesa Rais Visio 3, vista 270°.",
  "p1_26:name": "Rais Q-TEE 2 Chimenea de Leña Autónoma",
  "p1_26:description": "Chimenea de leña autónoma danesa Rais Q-TEE 2, diseño geométrico.",
  "p1_25:name": "Rais Q-BE Chimenea de Leña Autónoma Vista Angular",
  "p1_25:description": "Chimenea de leña autónoma danesa Rais Q-BE vista angular, diseño innovador.",
  "p1_24:name": "Rais Pilar Chimenea de Leña Autónoma",
  "p1_24:description": "Chimenea de leña autónoma danesa Rais Pilar, diseño columnar.",
  "p1_23:name": "Rais Bionic Fire Chimenea de Leña Doble Cámara",
  "p1_23:description": "Chimenea de leña danesa Rais Bionic Fire de doble cámara, tecnología innovadora.",
  "p1_22:name": "Haas+sohn Treviso Chimenea de Leña de Esteatita",
  "p1_22:description": "Chimenea de leña de esteatita austriaca Haas+sohn Treviso, calor duradero.",
  "p1_21:name": "Haas+sohn Kuopio-II Chimenea de Leña de Esteatita",
  "p1_21:description": "Chimenea de leña de esteatita austriaca Haas+sohn Kuopio-II.",
  "p1_20:name": "Haas+sohn Ficus-II-RLU Chimenea de Leña Autónoma",
  "p1_20:description": "Chimenea de leña autónoma austriaca Haas+sohn Ficus-II-RLU, diseño curvo.",
  "p1_2:name": "Haas+sohn Aruba Easy Estufa de Leña de Esteatita",
  "p1_2:description": "Estufa de leña de esteatita austriaca Haas+sohn Aruba Easy.",
  "p1_35:name": "Ruegg Tillia Chimenea de Leña Empotrable Tres Caras",
  "p1_35:description": "Chimenea de leña empotrable tres caras suiza Ruegg Tillia, precisión suiza.",
  "p1_34:name": "Ruegg Rondeo Chimenea de Leña Empotrable Curva",
  "p1_34:description": "Chimenea de leña empotrable suiza Ruegg Rondeo con vidrio curvo único.",
  "p1_33:name": "Ruegg RII Chimenea de Leña Empotrable de Esquina",
  "p1_33:description": "Chimenea de leña empotrable de esquina suiza Ruegg RII.",
  "p1_18:name": "Ruegg Odeon 270° Chimenea de Leña Suspendida Curva",
  "p1_18:description": "Chimenea de leña suspendida curva suiza Ruegg Odeon 270°, diseño artístico.",
  "p2_56:name": "Element4 Lucius 140 Chimenea de Gas Empotrable",
  "p2_56:description": "Chimenea de gas empotrable neerlandesa Element4 Lucius 140.",
  "p2_55:name": "Element4 Tenore 140 Chimenea de Gas Empotrable",
  "p2_55:description": "Chimenea de gas empotrable neerlandesa Element4 Tenore 140, diseño minimalista.",
  "p2_54:name": "Element4 Summum 100F Chimenea de Gas Empotrable",
  "p2_54:description": "Chimenea de gas empotrable neerlandesa Element4 Summum 100F, experiencia premium.",
  "p2_53:name": "Element4 Sky Serie Interior Chimenea de Gas",
  "p2_53:description": "Chimenea de gas interior neerlandesa Element4 Sky, diseño integrado.",
  "p2_31:name": "Element4 Trisore 140 Chimenea de Gas Tres Caras",
  "p2_31:description": "Chimenea de gas tres caras neerlandesa Element4 Trisore 140, vista panorámica.",
  "p2_29:name": "Element4 Bidore 100 Chimenea de Gas de Esquina",
  "p2_29:description": "Chimenea de gas de esquina neerlandesa Element4 Bidore 100.",
  "p3_14:name": "Chimenea de Alcohol (Personalizable)",
  "p3_14:description": "Chimenea de bioetanol, tamaño y apariencia personalizables, ecológica.",
  "p4_70:name": "Chimenea de Niebla Montada Dividida (Personalizable)",
  "p4_70:description": "Chimenea de niebla 3D montada dividida, efectos personalizables.",
  "p4_69:name": "Chimenea de Niebla Doble Cara (Personalizable)",
  "p4_69:description": "Chimenea de niebla doble cara, ideal para división de ambientes.",
  "p4_68:name": "Chimenea de Niebla Panorámica (Personalizable)",
  "p4_68:description": "Chimenea de niebla panorámica ultra ancha.",
  "p4_67:name": "Chimenea de Niebla Tres Caras (Personalizable)",
  "p4_67:description": "Chimenea de niebla tres caras con vista 270°.",
  "p4_66:name": "Chimenea de Niebla Redonda (Personalizable)",
  "p4_66:description": "Chimenea de niebla redonda de diseño circular único.",
  "p4_65:name": "Chimenea de Niebla Colgante OVNI (Personalizable)",
  "p4_65:description": "Chimenea de niebla colgante en forma de OVNI.",
  "p4_64:name": "Chimenea de Niebla Divisoria (Personalizable)",
  "p4_64:description": "Chimenea de niebla que funciona como divisor o pantalla.",
  "p4_62:name": "Chimenea de Niebla Simple Cara (Personalizable)",
  "p4_62:description": "Chimenea de niebla simple cara, diseño clásico.",
  "p4_11:name": "Chimenea de Niebla 3D Inteligente (Personalizable)",
  "p4_11:description": "Chimenea de niebla 3D inteligente con control inteligente.",
  "p6_49:name": "Servicio Completo de Chimenea Personalizada",
  "p6_49:description": "Servicio integral de diseño e instalación de chimeneas personalizadas.",
  "p7_6:name": "Chimenea Eléctrica (Personalizable)",
  "p7_6:description": "Chimenea eléctrica con efectos de llama realistas.",
  "p88_51:name": "Fuego Exterior (Personalizable)",
  "p88_51:description": "Fuego exterior para jardín y patio, diseños personalizables.",
  "p8_52:name": "Juego de Herramientas de Chimenea",
  "p8_52:description": "Juego de herramientas de chimenea danés Rais, accesorios de alta calidad.",
};

export default es_data;
