const fr_data: Record<string, string> = {
  "p1:name": "Cheminée à Bois",
  "p2:name": "Cheminée à Gaz",
  "p3:name": "Cheminée à Alcool",
  "p4:name": "Cheminée à Brume",
  "p7:name": "Cheminée Électrique",
  "p9:name": "Cheminée Holographique",
  "p6:name": "Cheminée Sur Mesure",
  "p88:name": "Foyer Extérieur",
  "p8:name": "Accessoires",
  "独立式": "Autonome",
  "嵌入式": "Encastrable",
  "壁挂式": "Mural",
  "悬挂式": "Suspendu",
  "悬挂/独立/嵌入": "Suspendu / Autonome / Encastrable",
  "独立/嵌入": "Autonome / Encastrable",
  "附件": "Accessoires",
  "西班牙": "Espagne",
  "丹麦": "Danemark",
  "奥地利": "Autriche",
  "瑞士": "Suisse",
  "荷兰": "Pays-Bas",
  "中国": "Chine",
  "p1_71:name": "Lacunza Altea Poêle à Bois Autonome avec Four",
  "p1_71:description": "Poêle à bois autonome espagnol Lacunza Altea avec four, alliant cuisine et chauffage dans un design classique.",
  "p1_1:name": "Lacunza Stelar 93 Cheminée à Bois Autonome",
  "p1_1:description": "Cheminée à bois autonome espagnole Lacunza Stelar 93, design élégant avec une excellente efficacité de chauffage.",
  "p1_45:name": "Lacunza Sara Cheminée à Bois Encastrable",
  "p1_45:description": "Cheminée à bois encastrable espagnole Lacunza Sara, design minimaliste gain de place.",
  "p1_44:name": "Lacunza Oslo Poêle à Bois Autonome",
  "p1_44:description": "Poêle à bois autonome espagnol Lacunza Oslo avec fonction de cuisson.",
  "p1_43:name": "Lacunza Nickel Cheminée à Bois Encastrable Double Face",
  "p1_43:description": "Cheminée à bois encastrable double face espagnole Lacunza Nickel, vitres des deux côtés.",
  "p1_42:name": "Lacunza K2 800 Cheminée à Bois Encastrable",
  "p1_42:description": "Cheminée à bois encastrable espagnole Lacunza K2 800 avec grande vitre.",
  "p1_41:name": "Lacunza Itaca Cheminée à Bois Encastrable",
  "p1_41:description": "Cheminée à bois encastrable simple face espagnole Lacunza Itaca, design classique.",
  "p1_39:name": "Lacunza CM 300R Cheminée à Bois Autonome d'Angle",
  "p1_39:description": "Cheminée à bois autonome d'angle espagnole Lacunza CM 300R, conçue pour installation en angle.",
  "p1_38:name": "Lacunza Clasica 7T Poêle à Bois avec Four",
  "p1_38:description": "Poêle à bois espagnol Lacunza Clasica 7T avec four, style champêtre européen.",
  "p1_37:name": "Lacunza Atlantic 603 Cheminée à Bois Autonome",
  "p1_37:description": "Cheminée à bois autonome espagnole Lacunza Atlantic 603, aspect imposant avec chauffage puissant.",
  "p1_36:name": "Lacunza Adour 700ST Cheminée à Bois Encastrable",
  "p1_36:description": "Cheminée à bois encastrable espagnole Lacunza Adour 700ST, lignes épurées, design moderne.",
  "p1_61:name": "Rais Q TEE 2C Cheminée à Bois Autonome",
  "p1_61:description": "Cheminée à bois autonome danoise Rais Q TEE 2C, design minimaliste nordique.",
  "p1_60:name": "Rais Nexo Série Cheminée à Bois Autonome",
  "p1_60:description": "Cheminée à bois autonome danoise Rais Nexo série, style moderne minimaliste.",
  "p1_59:name": "Rais Juno L Cheminée à Bois Autonome",
  "p1_59:description": "Cheminée à bois autonome danoise Rais Juno L avec fenêtre ronde.",
  "p1_58:name": "Rais Caro 90 Cheminée à Bois Autonome",
  "p1_58:description": "Cheminée à bois autonome danoise Rais Caro 90, forme cylindrique élégante.",
  "p1_28:name": "Rais Viva L Série Cheminée à Bois Autonome",
  "p1_28:description": "Cheminée à bois autonome danoise Rais Viva L série, effet de flamme dynamique.",
  "p1_27:name": "Rais Visio 3 Cheminée à Bois Encastrable Trois Faces",
  "p1_27:description": "Cheminée à bois encastrable trois faces danoise Rais Visio 3, vue panoramique 270°.",
  "p1_26:name": "Rais Q-TEE 2 Cheminée à Bois Autonome",
  "p1_26:description": "Cheminée à bois autonome danoise Rais Q-TEE 2, design géométrique artistique.",
  "p1_25:name": "Rais Q-BE Cheminée à Bois Autonome Vue d'Angle",
  "p1_25:description": "Cheminée à bois autonome danoise Rais Q-BE vue d'angle, design angulaire innovant.",
  "p1_24:name": "Rais Pilar Cheminée à Bois Autonome",
  "p1_24:description": "Cheminée à bois autonome danoise Rais Pilar, design en colonne, simple et élégant.",
  "p1_23:name": "Rais Bionic Fire Cheminée à Bois Double Chambre",
  "p1_23:description": "Cheminée à bois danoise Rais Bionic Fire à double chambre, technologie de combustion innovante.",
  "p1_22:name": "Haas+sohn Treviso Cheminée à Bois en Stéatite",
  "p1_22:description": "Cheminée à bois en stéatite autrichienne Haas+sohn Treviso, chaleur durable.",
  "p1_21:name": "Haas+sohn Kuopio-II Cheminée à Bois en Stéatite",
  "p1_21:description": "Cheminée à bois en stéatite autrichienne Haas+sohn Kuopio-II, artisanat nordique.",
  "p1_20:name": "Haas+sohn Ficus-II-RLU Cheminée à Bois Autonome",
  "p1_20:description": "Cheminée à bois autonome autrichienne Haas+sohn Ficus-II-RLU, design courbé élégant.",
  "p1_2:name": "Haas+sohn Aruba Easy Poêle à Bois en Stéatite",
  "p1_2:description": "Poêle à bois en stéatite autrichien Haas+sohn Aruba Easy, facile à utiliser.",
  "p1_35:name": "Ruegg Tillia Cheminée à Bois Encastrable Trois Faces",
  "p1_35:description": "Cheminée à bois encastrable trois faces suisse Ruegg Tillia, précision suisse.",
  "p1_34:name": "Ruegg Rondeo Cheminée à Bois Encastrable Verre Courbé",
  "p1_34:description": "Cheminée à bois encastrable suisse Ruegg Rondeo au verre courbé unique.",
  "p1_33:name": "Ruegg RII Cheminée à Bois Encastrable d'Angle",
  "p1_33:description": "Cheminée à bois encastrable d'angle suisse Ruegg RII, gain de place.",
  "p1_18:name": "Ruegg Odeon 270° Cheminée à Bois Suspendue Courbée",
  "p1_18:description": "Cheminée à bois suspendue courbée suisse Ruegg Odeon 270°, design artistique.",
  "p2_56:name": "Element4 Lucius 140 Cheminée à Gaz Encastrable",
  "p2_56:description": "Cheminée à gaz encastrable néerlandaise Element4 Lucius 140, grande vitre.",
  "p2_55:name": "Element4 Tenore 140 Cheminée à Gaz Encastrable",
  "p2_55:description": "Cheminée à gaz encastrable néerlandaise Element4 Tenore 140, design linéaire minimaliste.",
  "p2_54:name": "Element4 Summum 100F Cheminée à Gaz Encastrable",
  "p2_54:description": "Cheminée à gaz encastrable néerlandaise Element4 Summum 100F, expérience premium.",
  "p2_53:name": "Element4 Sky Série Intérieure Cheminée à Gaz",
  "p2_53:description": "Cheminée à gaz intérieure néerlandaise Element4 Sky, design intérieur-extérieur.",
  "p2_31:name": "Element4 Trisore 140 Cheminée à Gaz Trois Faces",
  "p2_31:description": "Cheminée à gaz trois faces néerlandaise Element4 Trisore 140, vue panoramique.",
  "p2_29:name": "Element4 Bidore 100 Cheminée à Gaz d'Angle",
  "p2_29:description": "Cheminée à gaz d'angle néerlandaise Element4 Bidore 100, vue d'angle double face.",
  "p3_14:name": "Cheminée à Alcool (Personnalisable)",
  "p3_14:description": "Cheminée bioéthanol, taille et apparence personnalisables, écologique.",
  "p4_70:name": "Cheminée à Brume Murale Divisée (Personnalisable)",
  "p4_70:description": "Cheminée à brume 3D design mural divisé, effets de flamme personnalisables.",
  "p4_69:name": "Cheminée à Brume Double Face (Personnalisable)",
  "p4_69:description": "Cheminée à brume double face, idéale pour séparation de pièces.",
  "p4_68:name": "Cheminée à Brume Panoramique (Personnalisable)",
  "p4_68:description": "Cheminée à brume panoramique ultra-large.",
  "p4_67:name": "Cheminée à Brume Trois Faces (Personnalisable)",
  "p4_67:description": "Cheminée à brume trois faces avec vue 270°.",
  "p4_66:name": "Cheminée à Brume Ronde (Personnalisable)",
  "p4_66:description": "Cheminée à brume ronde au design circulaire unique.",
  "p4_65:name": "Cheminée à Brume Suspendue OVNI (Personnalisable)",
  "p4_65:description": "Cheminée à brume suspendue en forme d'OVNI au design futuriste.",
  "p4_64:name": "Cheminée à Brume Cloison (Personnalisable)",
  "p4_64:description": "Cheminée à brume qui sert aussi de cloison ou d'écran.",
  "p4_62:name": "Cheminée à Brume Simple Face (Personnalisable)",
  "p4_62:description": "Cheminée à brume simple face, design classique pour installation murale.",
  "p4_11:name": "Cheminée à Brume 3D Intelligente (Personnalisable)",
  "p4_11:description": "Cheminée à brume 3D intelligente avec contrôle intelligent.",
  "p6_49:name": "Service Complet de Cheminée Personnalisée",
  "p6_49:description": "Service de conception et d'installation de cheminée sur mesure pour toutes catégories.",
  "p7_6:name": "Cheminée Électrique (Personnalisable)",
  "p7_6:description": "Cheminée électrique avec effets de flamme réalistes, taille personnalisable.",
  "p88_51:name": "Foyer Extérieur (Personnalisable)",
  "p88_51:description": "Foyer extérieur pour jardin et terrasse, designs personnalisables.",
  "p8_52:name": "Kit d'Outils de Cheminée",
  "p8_52:description": "Kit d'outils de cheminée danois Rais, accessoires de haute qualité.",
};

export default fr_data;
