const fr_data: Record<string, string> = {
  "p1:name": "Cheminée à Bois",
  "p2:name": "Cheminée à Gaz",
  "p3:name": "Cheminée à Alcool",
  "p4:name": "Cheminée à Brume",
  "p7:name": "Cheminée Électrique",
  "p9:name": "Cheminée Holographique",
  "p6:name": "Cheminée Sur Mesure",
  "p88:name": "Foyer Extérieur",
  "p8:name": "Accessoires",
  "独立式": "Autonome",
  "嵌入式": "Encastrable",
  "壁挂式": "Mural",
  "悬挂式": "Suspendu",
  "悬挂/独立/嵌入": "Suspendu / Autonome / Encastrable",
  "独立/嵌入": "Autonome / Encastrable",
  "附件": "Accessoires",
  "西班牙": "Espagne",
  "丹麦": "Danemark",
  "奥地利": "Autriche",
  "瑞士": "Suisse",
  "荷兰": "Pays-Bas",
  "中国": "Chine",
  "p1_71:name": "Lacunza Altea Poêle à Bois Autonome avec Four",
  "p1_71:description": "Poêle à bois autonome espagnol Lacunza Altea avec four, alliant cuisine et chauffage dans un design classique.",
  "p1_1:name": "Lacunza Stelar 93 Cheminée à Bois Autonome",
  "p1_1:description": "Cheminée à bois autonome espagnole Lacunza Stelar 93, design élégant avec une excellente efficacité de chauffage.",
  "p1_45:name": "Lacunza Sara Cheminée à Bois Encastrable",
  "p1_45:description": "Cheminée à bois encastrable espagnole Lacunza Sara, design minimaliste gain de place.",
  "p1_44:name": "Lacunza Oslo Poêle à Bois Autonome",
  "p1_44:description": "Poêle à bois autonome espagnol Lacunza Oslo avec fonction de cuisson.",
  "p1_43:name": "Lacunza Nickel Cheminée à Bois Encastrable Double Face",
  "p1_43:description": "Cheminée à bois encastrable double face espagnole Lacunza Nickel, vitres des deux côtés.",
  "p1_42:name": "Lacunza K2 800 Cheminée à Bois Encastrable",
  "p1_42:description": "Cheminée à bois encastrable espagnole Lacunza K2 800 avec grande vitre.",
  "p1_41:name": "Lacunza Itaca Cheminée à Bois Encastrable",
  "p1_41:description": "Cheminée à bois encastrable simple face espagnole Lacunza Itaca, design classique.",
  "p1_39:name": "Lacunza CM 300R Cheminée à Bois Autonome d'Angle",
  "p1_39:description": "Cheminée à bois autonome d'angle espagnole Lacunza CM 300R, conçue pour installation en angle.",
  "p1_38:name": "Lacunza Clasica 7T Poêle à Bois avec Four",
  "p1_38:description": "Poêle à bois espagnol Lacunza Clasica 7T avec four, style champêtre européen.",
  "p1_37:name": "Lacunza Atlantic 603 Cheminée à Bois Autonome",
  "p1_37:description": "Cheminée à bois autonome espagnole Lacunza Atlantic 603, aspect imposant avec chauffage puissant.",
  "p1_36:name": "Lacunza Adour 700ST Cheminée à Bois Encastrable",
  "p1_36:description": "Cheminée à bois encastrable espagnole Lacunza Adour 700ST, lignes épurées, design moderne.",
  "p1_61:name": "Rais Q TEE 2C Cheminée à Bois Autonome",
  "p1_61:description": "Cheminée à bois autonome danoise Rais Q TEE 2C, design minimaliste nordique.",
  "p1_60:name": "Rais Nexo Série Cheminée à Bois Autonome",
  "p1_60:description": "Cheminée à bois autonome danoise Rais Nexo série, style moderne minimaliste.",
  "p1_59:name": "Rais Juno L Cheminée à Bois Autonome",
  "p1_59:description": "Cheminée à bois autonome danoise Rais Juno L avec fenêtre ronde.",
  "p1_58:name": "Rais Caro 90 Cheminée à Bois Autonome",
  "p1_58:description": "Cheminée à bois autonome danoise Rais Caro 90, forme cylindrique élégante.",
  "p1_28:name": "Rais Viva L Série Cheminée à Bois Autonome",
  "p1_28:description": "Cheminée à bois autonome danoise Rais Viva L série, effet de flamme dynamique.",
  "p1_27:name": "Rais Visio 3 Cheminée à Bois Encastrable Trois Faces",
  "p1_27:description": "Cheminée à bois encastrable trois faces danoise Rais Visio 3, vue panoramique 270°.",
  "p1_26:name": "Rais Q-TEE 2 Cheminée à Bois Autonome",
  "p1_26:description": "Cheminée à bois autonome danoise Rais Q-TEE 2, design géométrique artistique.",
  "p1_25:name": "Rais Q-BE Cheminée à Bois Autonome Vue d'Angle",
  "p1_25:description": "Cheminée à bois autonome danoise Rais Q-BE vue d'angle, design angulaire innovant.",
  "p1_24:name": "Rais Pilar Cheminée à Bois Autonome",
  "p1_24:description": "Cheminée à bois autonome danoise Rais Pilar, design en colonne, simple et élégant.",
  "p1_23:name": "Rais Bionic Fire Cheminée à Bois Double Chambre",
  "p1_23:description": "Cheminée à bois danoise Rais Bionic Fire à double chambre, technologie de combustion innovante.",
  "p1_22:name": "Haas+sohn Treviso Cheminée à Bois en Stéatite",
  "p1_22:description": "Cheminée à bois en stéatite autrichienne Haas+sohn Treviso, chaleur durable.",
  "p1_21:name": "Haas+sohn Kuopio-II Cheminée à Bois en Stéatite",
  "p1_21:description": "Cheminée à bois en stéatite autrichienne Haas+sohn Kuopio-II, artisanat nordique.",
  "p1_20:name": "Haas+sohn Ficus-II-RLU Cheminée à Bois Autonome",
  "p1_20:description": "Cheminée à bois autonome autrichienne Haas+sohn Ficus-II-RLU, design courbé élégant.",
  "p1_2:name": "Haas+sohn Aruba Easy Poêle à Bois en Stéatite",
  "p1_2:description": "Poêle à bois en stéatite autrichien Haas+sohn Aruba Easy, facile à utiliser.",
  "p1_35:name": "Ruegg Tillia Cheminée à Bois Encastrable Trois Faces",
  "p1_35:description": "Cheminée à bois encastrable trois faces suisse Ruegg Tillia, précision suisse.",
  "p1_34:name": "Ruegg Rondeo Cheminée à Bois Encastrable Verre Courbé",
  "p1_34:description": "Cheminée à bois encastrable suisse Ruegg Rondeo au verre courbé unique.",
  "p1_33:name": "Ruegg RII Cheminée à Bois Encastrable d'Angle",
  "p1_33:description": "Cheminée à bois encastrable d'angle suisse Ruegg RII, gain de place.",
  "p1_18:name": "Ruegg Odeon 270° Cheminée à Bois Suspendue Courbée",
  "p1_18:description": "Cheminée à bois suspendue courbée suisse Ruegg Odeon 270°, design artistique.",
  "p2_56:name": "Element4 Lucius 140 Cheminée à Gaz Encastrable",
  "p2_56:description": "Cheminée à gaz encastrable néerlandaise Element4 Lucius 140, grande vitre.",
  "p2_55:name": "Element4 Tenore 140 Cheminée à Gaz Encastrable",
  "p2_55:description": "Cheminée à gaz encastrable néerlandaise Element4 Tenore 140, design linéaire minimaliste.",
  "p2_54:name": "Element4 Summum 100F Cheminée à Gaz Encastrable",
  "p2_54:description": "Cheminée à gaz encastrable néerlandaise Element4 Summum 100F, expérience premium.",
  "p2_53:name": "Element4 Sky Série Intérieure Cheminée à Gaz",
  "p2_53:description": "Cheminée à gaz intérieure néerlandaise Element4 Sky, design intérieur-extérieur.",
  "p2_31:name": "Element4 Trisore 140 Cheminée à Gaz Trois Faces",
  "p2_31:description": "Cheminée à gaz trois faces néerlandaise Element4 Trisore 140, vue panoramique.",
  "p2_29:name": "Element4 Bidore 100 Cheminée à Gaz d'Angle",
  "p2_29:description": "Cheminée à gaz d'angle néerlandaise Element4 Bidore 100, vue d'angle double face.",
  "p3_14:name": "Cheminée à Alcool (Personnalisable)",
  "p3_14:description": "Cheminée bioéthanol, taille et apparence personnalisables, écologique.",
  "p4_70:name": "Cheminée à Brume Murale Divisée (Personnalisable)",
  "p4_70:description": "Cheminée à brume 3D design mural divisé, effets de flamme personnalisables.",
  "p4_61:name": "Cheminée linéaire 3D à brume avec bûches charbon décoratives",
  "p4_61:description": "Cheminée linéaire à vapeur d'eau 3D avec effet charbon décoratif, conçue pour hôtels, villas, clubs et projets commerciaux en gros ou OEM/ODM.",
  "p4_69:name": "Cheminée à Brume Double Face (Personnalisable)",
  "p4_69:description": "Cheminée à brume double face, idéale pour séparation de pièces.",
  "p4_68:name": "Cheminée à Brume Panoramique (Personnalisable)",
  "p4_68:description": "Cheminée à brume panoramique ultra-large.",
  "p4_67:name": "Cheminée à Brume Trois Faces (Personnalisable)",
  "p4_67:description": "Cheminée à brume trois faces avec vue 270°.",
  "p4_66:name": "Cheminée à Brume Ronde (Personnalisable)",
  "p4_66:description": "Cheminée à brume ronde au design circulaire unique.",
  "p4_65:name": "Cheminée à Brume Suspendue OVNI (Personnalisable)",
  "p4_65:description": "Cheminée à brume suspendue en forme d'OVNI au design futuriste.",
  "p4_64:name": "Cheminée à Brume Cloison (Personnalisable)",
  "p4_64:description": "Cheminée à brume qui sert aussi de cloison ou d'écran.",
  "p4_62:name": "Cheminée à Brume Simple Face (Personnalisable)",
  "p4_62:description": "Cheminée à brume simple face, design classique pour installation murale.",
  "p4_11:name": "Cheminée à Brume 3D Intelligente (Personnalisable)",
  "p4_11:description": "Cheminée à brume 3D intelligente avec contrôle intelligent.",
  "嵌入式 / 语音控制": "Encastrable / commande vocale",
  "嵌入式 / 音乐播放": "Encastrable / lecture musicale",
  "嵌入式 / 户外防水": "Encastrable / extérieur étanche",
  "圆形 / 仿真木柴": "Rond / bûches décoratives",
  "独立式 / 半球装饰": "Autonome / hémisphérique",
  "p4_71:name": "Cheminée à vapeur d’eau 3D linéaire avec commande vocale",
  "p4_71:description": "Cheminée à vapeur d’eau 3D linéaire encastrable avec commande vocale pour hôtels, villas, clubs, showrooms et murs décoratifs commerciaux. Longueur, éclairage, emballage et OEM/ODM personnalisables.",
  "p4_72:name": "Cheminée à vapeur d’eau 3D linéaire avec lecture musicale",
  "p4_72:description": "Cheminée à vapeur d’eau 3D linéaire encastrable avec lecture musicale pour appartements témoins, suites d’hôtel, clubs et espaces de présentation.",
  "p4_73:name": "Cheminée à vapeur d’eau 3D linéaire extérieure étanche",
  "p4_73:description": "Cheminée à vapeur d’eau 3D linéaire étanche pour terrasses, espaces extérieurs d’hôtel, lounges commerciaux et projets semi-extérieurs.",
  "p4_74:name": "Cheminée ronde encastrable à vapeur d’eau 3D avec bûches décoratives",
  "p4_74:description": "Cheminée ronde encastrable à vapeur d’eau 3D avec bûches décoratives pour clubs, showrooms, salons d’hôtel et installations décoratives.",
  "p4_75:name": "Cheminée décorative hémisphérique autonome à vapeur d’eau",
  "p4_75:description": "Cheminée décorative hémisphérique autonome à vapeur d’eau 3D pour halls d’hôtel, clubs, showrooms et espaces commerciaux sans conduit.",
  "p6_49:name": "Service Complet de Cheminée Personnalisée",
  "p6_49:description": "Service de conception et d'installation de cheminée sur mesure pour toutes catégories.",
  "p7_6:name": "Cheminée Électrique (Personnalisable)",
  "p7_6:description": "Cheminée électrique avec effets de flamme réalistes, taille personnalisable.",
  "嵌入式 / 长条批发": "Encastrable / linéaire grossiste",
  "转角 / 双面观火": "Angle / vue deux faces",
  "四面观火": "Vue quatre faces",
  "圆形 / 定制": "Rond / sur mesure",
  "半圆 / 定制": "Demi-rond / sur mesure",
  "三角形 / 定制": "Triangle / sur mesure",
  "拱形 / 定制": "Arche / sur mesure",
  "p7_10:name": "Cheminée électrique linéaire encastrable pour grossistes",
  "p7_10:description": "Cheminée électrique linéaire encastrable de 500 à 3000 mm pour murs TV, chambres d’hôtel, appartements témoins, showrooms et projets en série. Chauffage, son, porte de protection, cadre, couleur et OEM/ODM en option.",
  "p7_11:name": "Cheminée électrique d’angle gauche à deux faces",
  "p7_11:description": "Cheminée électrique en L côté gauche avec vue de flamme sur deux faces pour angles de murs TV et espaces commerciaux. Prix calculé selon la longueur frontale et latérale.",
  "p7_12:name": "Cheminée électrique d’angle droit à deux faces",
  "p7_12:description": "Cheminée électrique en L côté droit avec vue de flamme sur deux faces pour installations d’angle et projets intérieurs personnalisés.",
  "p7_13:name": "Cheminée électrique trois faces",
  "p7_13:description": "Cheminée électrique trois faces avec vue à 270 degrés pour installation près d’un mur, suites d’hôtel et espaces commerciaux.",
  "p7_14:name": "Cheminée électrique trois faces type B",
  "p7_14:description": "Cheminée électrique trois faces type B pour longues zones de visibilité et séparation d’espace. Prix de gros selon les longueurs combinées.",
  "p7_15:name": "Cheminée électrique quatre faces",
  "p7_15:description": "Cheminée électrique quatre faces pour îlots, comptoirs et zones centrales où la flamme doit être visible de tous les côtés.",
  "p7_16:name": "Cheminée électrique ronde",
  "p7_16:description": "Cheminée électrique ronde en diamètres 500-700 mm pour showrooms, salons d’hôtel et structures décoratives sur mesure.",
  "p7_17:name": "Cheminée électrique demi-ronde inférieure",
  "p7_17:description": "Cheminée électrique demi-ronde inférieure pour murs courbes, panneaux spéciaux et projets personnalisés de 500 à 700 mm.",
  "p7_18:name": "Cheminée électrique demi-ronde supérieure",
  "p7_18:description": "Cheminée électrique demi-ronde supérieure pour arches, courbes et murs décoratifs spéciaux avec options de taille, couleur et fonction.",
  "p7_19:name": "Cheminée électrique triangulaire",
  "p7_19:description": "Cheminée électrique triangulaire pour intérieurs design, installations d’exposition et murs spéciaux avec côtés de 500 à 700 mm.",
  "p7_20:name": "Cheminée électrique arquée",
  "p7_20:description": "Cheminée électrique arquée pour espaces européens, premium et commerciaux, avec tailles 2DN500-2DN600 et personnalisation projet.",
  "p88_51:name": "Foyer Extérieur (Personnalisable)",
  "p88_51:description": "Foyer extérieur pour jardin et terrasse, designs personnalisables.",
  "p8_52:name": "Kit d'Outils de Cheminée",
  "p8_52:description": "Kit d'outils de cheminée danois Rais, accessoires de haute qualité.",
  "燃木壁炉": "Cheminée à bois",
  "悬挂式 / 烟囱款": "Suspendue / avec conduit",
  "装饰 / 落地款": "Décorative / autonome",
  "球形 / 装饰款": "Sphérique / décorative",
  "p1_72:name": "Cheminée à bois suspendue en forme de soucoupe",
  "p1_72:description": "Cheminée à bois suspendue en forme de soucoupe pour villas, lodges, clubs et espaces lounge commerciaux. Conduit de 2 m inclus; bride, couleur, sections de conduit, emballage et détails OEM/ODM à confirmer par projet.",
  "p3_27:name": "Cheminée éthanol suspendue en forme de soucoupe",
  "p3_27:description": "Cheminée bioéthanol suspendue en forme de soucoupe pour villas, hôtels, clubs, appartements témoins et projets décoratifs commerciaux, avec données de gros et emballage export.",
  "p4_76:name": "Cheminée 3D à vapeur d’eau suspendue en forme de soucoupe",
  "p4_76:description": "Cheminée 3D à vapeur d’eau suspendue pour halls d’hôtel, clubs, villas et espaces intérieurs recherchant une ambiance flamme sans feu ouvert.",
  "p3_28:name": "Cheminée éthanol décorative autonome",
  "p3_28:description": "Cheminée éthanol décorative autonome pour salons de villa, lounges d’hôtel, clubs, restaurants et showrooms, avec tailles de gros et données d’emballage export.",
  "p4_77:name": "Cheminée 3D à vapeur d’eau décorative autonome",
  "p4_77:description": "Cheminée 3D à vapeur d’eau décorative autonome pour hôtels, clubs, showrooms et projets résidentiels sans flamme ouverte.",
  "p3_29:name": "Cheminée éthanol décorative sphérique",
  "p3_29:description": "Cheminée éthanol décorative sphérique pour villas, hôtels, restaurants, clubs et showrooms, avec plusieurs diamètres pour la fourniture en gros.",
};

export default fr_data;
