const it_data: Record<string, string> = {
  "p1:name": "Caminetto a Legna",
  "p2:name": "Caminetto a Gas",
  "p3:name": "Caminetto ad Alcol",
  "p4:name": "Caminetto a Nebbia",
  "p7:name": "Caminetto Elettrico",
  "p9:name": "Caminetto Olografico",
  "p6:name": "Caminetto Personalizzato",
  "p88:name": "Fuoco all'Aperto",
  "p8:name": "Accessori",
  "独立式": "Autonomo",
  "嵌入式": "Da incasso",
  "壁挂式": "A parete",
  "悬挂式": "Sospeso",
  "悬挂/独立/嵌入": "Sospeso / Autonomo / Incasso",
  "独立/嵌入": "Autonomo / Incasso",
  "附件": "Accessori",
  "西班牙": "Spagna",
  "丹麦": "Danimarca",
  "奥地利": "Austria",
  "瑞士": "Svizzera",
  "荷兰": "Paesi Bassi",
  "中国": "Cina",
  "p1_71:name": "Lacunza Altea Stufa a Legna Autonoma con Forno",
  "p1_71:description": "Stufa a legna autonoma spagnola Lacunza Altea con forno, unisce cucina e riscaldamento.",
  "p1_1:name": "Lacunza Stelar 93 Caminetto a Legna Autonomo",
  "p1_1:description": "Caminetto a legna autonomo spagnolo Lacunza Stelar 93, design elegante.",
  "p1_45:name": "Lacunza Sara Caminetto a Legna da Incasso",
  "p1_45:description": "Caminetto a legna da incasso spagnolo Lacunza Sara, design minimalista.",
  "p1_44:name": "Lacunza Oslo Stufa a Legna Autonoma",
  "p1_44:description": "Stufa a legna autonoma spagnola Lacunza Oslo con funzione cottura.",
  "p1_43:name": "Lacunza Nickel Caminetto a Legna Incasso Bifacciale",
  "p1_43:description": "Caminetto a legna incasso bifacciale spagnolo Lacunza Nickel.",
  "p1_42:name": "Lacunza K2 800 Caminetto a Legna da Incasso",
  "p1_42:description": "Caminetto a legna da incasso spagnolo Lacunza K2 800 con ampia vetrata.",
  "p1_41:name": "Lacunza Itaca Caminetto a Legna da Incasso",
  "p1_41:description": "Caminetto a legna da incasso unifacciale spagnolo Lacunza Itaca.",
  "p1_39:name": "Lacunza CM 300R Caminetto a Legna Autonomo d'Angolo",
  "p1_39:description": "Caminetto a legna autonomo d'angolo spagnolo Lacunza CM 300R.",
  "p1_38:name": "Lacunza Clasica 7T Stufa a Legna con Forno",
  "p1_38:description": "Stufa a legna spagnola Lacunza Clasica 7T con forno, stile country europeo.",
  "p1_37:name": "Lacunza Atlantic 603 Caminetto a Legna Autonomo",
  "p1_37:description": "Caminetto a legna autonomo spagnolo Lacunza Atlantic 603.",
  "p1_36:name": "Lacunza Adour 700ST Caminetto a Legna da Incasso",
  "p1_36:description": "Caminetto a legna da incasso spagnolo Lacunza Adour 700ST, linee pulite.",
  "p1_61:name": "Rais Q TEE 2C Caminetto a Legna Autonomo",
  "p1_61:description": "Caminetto a legna autonomo danese Rais Q TEE 2C, design nordico minimalista.",
  "p1_60:name": "Rais Nexo Serie Caminetto a Legna Autonomo",
  "p1_60:description": "Caminetto a legna autonomo danese Rais Nexo serie, stile moderno.",
  "p1_59:name": "Rais Juno L Caminetto a Legna Autonomo",
  "p1_59:description": "Caminetto a legna autonomo danese Rais Juno L con finestra circolare.",
  "p1_58:name": "Rais Caro 90 Caminetto a Legna Autonomo",
  "p1_58:description": "Caminetto a legna autonomo danese Rais Caro 90, forma cilindrica.",
  "p1_28:name": "Rais Viva L Serie Caminetto a Legna Autonomo",
  "p1_28:description": "Caminetto a legna autonomo danese Rais Viva L serie, fiamma dinamica.",
  "p1_27:name": "Rais Visio 3 Caminetto a Legna Incasso Tre Facce",
  "p1_27:description": "Caminetto a legna incasso tre facce danese Rais Visio 3, vista 270°.",
  "p1_26:name": "Rais Q-TEE 2 Caminetto a Legna Autonomo",
  "p1_26:description": "Caminetto a legna autonomo danese Rais Q-TEE 2, design geometrico.",
  "p1_25:name": "Rais Q-BE Caminetto a Legna Autonomo Vista Angolare",
  "p1_25:description": "Caminetto a legna autonomo danese Rais Q-BE vista angolare.",
  "p1_24:name": "Rais Pilar Caminetto a Legna Autonomo",
  "p1_24:description": "Caminetto a legna autonomo danese Rais Pilar, design a colonna.",
  "p1_23:name": "Rais Bionic Fire Caminetto a Legna Doppia Camera",
  "p1_23:description": "Caminetto a legna danese Rais Bionic Fire a doppia camera.",
  "p1_22:name": "Haas+sohn Treviso Caminetto a Legna in Steatite",
  "p1_22:description": "Caminetto a legna in steatite austriaco Haas+sohn Treviso, calore duraturo.",
  "p1_21:name": "Haas+sohn Kuopio-II Caminetto a Legna in Steatite",
  "p1_21:description": "Caminetto a legna in steatite austriaco Haas+sohn Kuopio-II.",
  "p1_20:name": "Haas+sohn Ficus-II-RLU Caminetto a Legna Autonomo",
  "p1_20:description": "Caminetto a legna autonomo austriaco Haas+sohn Ficus-II-RLU, design curvo.",
  "p1_2:name": "Haas+sohn Aruba Easy Stufa a Legna in Steatite",
  "p1_2:description": "Stufa a legna in steatite austriaca Haas+sohn Aruba Easy.",
  "p1_35:name": "Ruegg Tillia Caminetto a Legna Incasso Tre Facce",
  "p1_35:description": "Caminetto a legna incasso tre facce svizzero Ruegg Tillia, precisione svizzera.",
  "p1_34:name": "Ruegg Rondeo Caminetto a Legna Incasso Vetro Curvo",
  "p1_34:description": "Caminetto a legna incasso svizzero Ruegg Rondeo con vetro curvo.",
  "p1_33:name": "Ruegg RII Caminetto a Legna Incasso d'Angolo",
  "p1_33:description": "Caminetto a legna incasso d'angolo svizzero Ruegg RII.",
  "p1_18:name": "Ruegg Odeon 270° Caminetto a Legna Sospeso Curvo",
  "p1_18:description": "Caminetto a legna sospeso curvo svizzero Ruegg Odeon 270°.",
  "p2_56:name": "Element4 Lucius 140 Caminetto a Gas da Incasso",
  "p2_56:description": "Caminetto a gas da incasso olandese Element4 Lucius 140.",
  "p2_55:name": "Element4 Tenore 140 Caminetto a Gas da Incasso",
  "p2_55:description": "Caminetto a gas da incasso olandese Element4 Tenore 140.",
  "p2_54:name": "Element4 Summum 100F Caminetto a Gas da Incasso",
  "p2_54:description": "Caminetto a gas da incasso olandese Element4 Summum 100F.",
  "p2_53:name": "Element4 Sky Serie Interna Caminetto a Gas",
  "p2_53:description": "Caminetto a gas interno olandese Element4 Sky, design integrato.",
  "p2_31:name": "Element4 Trisore 140 Caminetto a Gas Tre Facce",
  "p2_31:description": "Caminetto a gas tre facce olandese Element4 Trisore 140, vista panoramica.",
  "p2_29:name": "Element4 Bidore 100 Caminetto a Gas d'Angolo",
  "p2_29:description": "Caminetto a gas d'angolo olandese Element4 Bidore 100.",
  "p3_14:name": "Caminetto ad Alcol (Personalizzabile)",
  "p3_14:description": "Caminetto bioetanolo, dimensioni personalizzabili, ecologico.",
  "p4_70:name": "Caminetto a Nebbia Sospeso Diviso (Personalizzabile)",
  "p4_70:description": "Caminetto a nebbia 3D sospeso diviso, effetti personalizzabili.",
  "p4_61:name": "Caminetto lineare 3D a vapore con carbone decorativo",
  "p4_61:description": "Caminetto lineare 3D a vapore acqueo con effetto carbone decorativo per hotel, ville, club e progetti commerciali wholesale o OEM/ODM.",
  "p4_69:name": "Caminetto a Nebbia Bifacciale (Personalizzabile)",
  "p4_69:description": "Caminetto a nebbia bifacciale, ideale per divisori.",
  "p4_68:name": "Caminetto a Nebbia Panoramico (Personalizzabile)",
  "p4_68:description": "Caminetto a nebbia panoramico ultra-wide.",
  "p4_67:name": "Caminetto a Nebbia Tre Facce (Personalizzabile)",
  "p4_67:description": "Caminetto a nebbia tre facce con vista 270°.",
  "p4_66:name": "Caminetto a Nebbia Rotondo (Personalizzabile)",
  "p4_66:description": "Caminetto a nebbia rotondo dal design circolare unico.",
  "p4_65:name": "Caminetto a Nebbia Sospeso UFO (Personalizzabile)",
  "p4_65:description": "Caminetto a nebbia sospeso a forma di UFO.",
  "p4_64:name": "Caminetto a Nebbia Divisorio (Personalizzabile)",
  "p4_64:description": "Caminetto a nebbia che funge da divisorio o schermo.",
  "p4_62:name": "Caminetto a Nebbia Unifacciale (Personalizzabile)",
  "p4_62:description": "Caminetto a nebbia unifacciale, design classico.",
  "p4_11:name": "Caminetto a Nebbia 3D Intelligente (Personalizzabile)",
  "p4_11:description": "Caminetto a nebbia 3D intelligente con controllo smart.",
  "嵌入式 / 语音控制": "Incasso / controllo vocale",
  "嵌入式 / 音乐播放": "Incasso / musica",
  "嵌入式 / 户外防水": "Incasso / esterno impermeabile",
  "圆形 / 仿真木柴": "Rotondo / ceppi decorativi",
  "独立式 / 半球装饰": "Freestanding / emisferico",
  "p4_71:name": "Camino lineare 3D a vapore acqueo con controllo vocale",
  "p4_71:description": "Camino lineare da incasso 3D a vapore acqueo con controllo vocale per hotel, ville, club, showroom e pareti commerciali. Lunghezza, luce, imballo e OEM/ODM personalizzabili.",
  "p4_72:name": "Camino lineare 3D a vapore acqueo con musica",
  "p4_72:description": "Camino lineare da incasso 3D a vapore acqueo con riproduzione musicale per appartamenti campione, suite hotel, club e spazi espositivi.",
  "p4_73:name": "Camino lineare 3D a vapore acqueo impermeabile per esterni",
  "p4_73:description": "Camino lineare 3D a vapore acqueo impermeabile per terrazze, aree esterne hotel, lounge commerciali e progetti semi-esterni.",
  "p4_74:name": "Camino rotondo da incasso 3D a vapore acqueo con ceppi decorativi",
  "p4_74:description": "Camino rotondo da incasso 3D a vapore acqueo con ceppi decorativi per club, showroom, lounge hotel e installazioni decorative.",
  "p4_75:name": "Camino decorativo emisferico freestanding a vapore acqueo",
  "p4_75:description": "Camino decorativo emisferico freestanding 3D a vapore acqueo per lobby hotel, club, showroom e spazi commerciali senza canna fumaria.",
  "p6_49:name": "Servizio Completo Caminetto Personalizzato",
  "p6_49:description": "Servizio completo di progettazione e installazione caminetti personalizzati.",
  "p7_6:name": "Caminetto Elettrico (Personalizzabile)",
  "p7_6:description": "Caminetto elettrico con effetti fiamma realistici.",
  "嵌入式 / 长条批发": "Incasso / lineare ingrosso",
  "转角 / 双面观火": "Angolo / bifacciale",
  "四面观火": "Vista su quattro lati",
  "圆形 / 定制": "Rotondo / su misura",
  "半圆 / 定制": "Semirotondo / su misura",
  "三角形 / 定制": "Triangolo / su misura",
  "拱形 / 定制": "Arco / su misura",
  "p7_10:name": "Camino elettrico lineare da incasso per ingrosso",
  "p7_10:description": "Camino elettrico lineare da incasso da 500 a 3000 mm per pareti TV, camere hotel, appartamenti campione, showroom e progetti in serie. Riscaldamento, audio, porta di protezione, telaio, colore e OEM/ODM opzionali.",
  "p7_11:name": "Camino elettrico angolare sinistro bifacciale",
  "p7_11:description": "Camino elettrico a L sinistro con vista fiamma su due lati per angoli di pareti multimediali e spazi commerciali. Prezzo in base alla lunghezza frontale e laterale.",
  "p7_12:name": "Camino elettrico angolare destro bifacciale",
  "p7_12:description": "Camino elettrico a L destro con vista fiamma su due lati per installazioni ad angolo e progetti su misura.",
  "p7_13:name": "Camino elettrico su tre lati",
  "p7_13:description": "Camino elettrico su tre lati con vista fiamma a 270 gradi per installazioni a parete, suite hotel e spazi commerciali.",
  "p7_14:name": "Camino elettrico su tre lati tipo B",
  "p7_14:description": "Camino elettrico su tre lati tipo B per lati lunghi a vista e divisione degli spazi. Prezzo all’ingrosso secondo le lunghezze combinate.",
  "p7_15:name": "Camino elettrico su quattro lati",
  "p7_15:description": "Camino elettrico su quattro lati per isole, piani e aree centrali con effetto fiamma visibile da ogni lato.",
  "p7_16:name": "Camino elettrico rotondo",
  "p7_16:description": "Camino elettrico rotondo con diametri 500-700 mm per showroom, lounge hotel e strutture decorative su misura.",
  "p7_17:name": "Camino elettrico semirotondo inferiore",
  "p7_17:description": "Camino elettrico semirotondo inferiore per pareti curve, pannelli sagomati e progetti personalizzati da 500 a 700 mm.",
  "p7_18:name": "Camino elettrico semirotondo superiore",
  "p7_18:description": "Camino elettrico semirotondo superiore per archi, curve e pareti speciali con opzioni di misura, colore e funzione.",
  "p7_19:name": "Camino elettrico triangolare",
  "p7_19:description": "Camino elettrico triangolare per interni di design, installazioni espositive e pareti speciali con lati da 500 a 700 mm.",
  "p7_20:name": "Camino elettrico ad arco",
  "p7_20:description": "Camino elettrico ad arco per ambienti europei, luxury e commerciali con misure 2DN500-2DN600 e personalizzazione progetto.",
  "p88_51:name": "Fuoco all'Aperto (Personalizzabile)",
  "p88_51:description": "Fuoco all'aperto per giardino e patio, design personalizzabili.",
  "p8_52:name": "Set di Utensili per Caminetto",
  "p8_52:description": "Set di utensili per caminetto danese Rais, accessori di qualità.",
  "燃木壁炉": "Camino a legna",
  "悬挂式 / 烟囱款": "Sospeso / con camino",
  "装饰 / 落地款": "Decorativo / freestanding",
  "球形 / 装饰款": "Sferico / decorativo",
  "p1_72:name": "Camino a legna sospeso a disco",
  "p1_72:description": "Camino a legna sospeso a disco per ville, lodge, club e lounge commerciali. Include camino standard da 2 m; flangia, colore, sezioni camino, imballo e dettagli OEM/ODM da confermare per progetto.",
  "p3_27:name": "Camino a etanolo sospeso a disco",
  "p3_27:description": "Camino a bioetanolo sospeso a disco per ville, hotel, club, appartamenti campione e progetti decorativi commerciali con dati all’ingrosso e imballo export.",
  "p4_76:name": "Camino 3D a vapore acqueo sospeso a disco",
  "p4_76:description": "Camino 3D a vapore acqueo sospeso per lobby hotel, club, ville e interni commerciali che richiedono atmosfera di fiamma senza fuoco aperto.",
  "p3_28:name": "Camino decorativo freestanding a etanolo",
  "p3_28:description": "Camino decorativo freestanding a etanolo per salotti di ville, lounge hotel, club, ristoranti e showroom con misure wholesale e dati di imballo export.",
  "p4_77:name": "Camino decorativo freestanding 3D a vapore acqueo",
  "p4_77:description": "Camino decorativo freestanding 3D a vapore acqueo per hotel, club, showroom e progetti residenziali dove si preferisce evitare fiamma aperta.",
  "p3_29:name": "Camino decorativo sferico a etanolo",
  "p3_29:description": "Camino decorativo sferico a etanolo per ville, hotel, ristoranti, club e showroom con vari diametri per fornitura wholesale.",
};

export default it_data;
