const it_data: Record<string, string> = {
  "p1:name": "Caminetto a Legna",
  "p2:name": "Caminetto a Gas",
  "p3:name": "Caminetto ad Alcol",
  "p4:name": "Caminetto a Nebbia",
  "p7:name": "Caminetto Elettrico",
  "p6:name": "Caminetto Personalizzato",
  "p88:name": "Fuoco all'Aperto",
  "p8:name": "Accessori",
  "独立式": "Autonomo",
  "嵌入式": "Da incasso",
  "壁挂式": "A parete",
  "悬挂式": "Sospeso",
  "悬挂/独立/嵌入": "Sospeso / Autonomo / Incasso",
  "独立/嵌入": "Autonomo / Incasso",
  "附件": "Accessori",
  "西班牙": "Spagna",
  "丹麦": "Danimarca",
  "奥地利": "Austria",
  "瑞士": "Svizzera",
  "荷兰": "Paesi Bassi",
  "中国": "Cina",
  "p1_71:name": "Lacunza Altea Stufa a Legna Autonoma con Forno",
  "p1_71:description": "Stufa a legna autonoma spagnola Lacunza Altea con forno, unisce cucina e riscaldamento.",
  "p1_1:name": "Lacunza Stelar 93 Caminetto a Legna Autonomo",
  "p1_1:description": "Caminetto a legna autonomo spagnolo Lacunza Stelar 93, design elegante.",
  "p1_45:name": "Lacunza Sara Caminetto a Legna da Incasso",
  "p1_45:description": "Caminetto a legna da incasso spagnolo Lacunza Sara, design minimalista.",
  "p1_44:name": "Lacunza Oslo Stufa a Legna Autonoma",
  "p1_44:description": "Stufa a legna autonoma spagnola Lacunza Oslo con funzione cottura.",
  "p1_43:name": "Lacunza Nickel Caminetto a Legna Incasso Bifacciale",
  "p1_43:description": "Caminetto a legna incasso bifacciale spagnolo Lacunza Nickel.",
  "p1_42:name": "Lacunza K2 800 Caminetto a Legna da Incasso",
  "p1_42:description": "Caminetto a legna da incasso spagnolo Lacunza K2 800 con ampia vetrata.",
  "p1_41:name": "Lacunza Itaca Caminetto a Legna da Incasso",
  "p1_41:description": "Caminetto a legna da incasso unifacciale spagnolo Lacunza Itaca.",
  "p1_39:name": "Lacunza CM 300R Caminetto a Legna Autonomo d'Angolo",
  "p1_39:description": "Caminetto a legna autonomo d'angolo spagnolo Lacunza CM 300R.",
  "p1_38:name": "Lacunza Clasica 7T Stufa a Legna con Forno",
  "p1_38:description": "Stufa a legna spagnola Lacunza Clasica 7T con forno, stile country europeo.",
  "p1_37:name": "Lacunza Atlantic 603 Caminetto a Legna Autonomo",
  "p1_37:description": "Caminetto a legna autonomo spagnolo Lacunza Atlantic 603.",
  "p1_36:name": "Lacunza Adour 700ST Caminetto a Legna da Incasso",
  "p1_36:description": "Caminetto a legna da incasso spagnolo Lacunza Adour 700ST, linee pulite.",
  "p1_61:name": "Rais Q TEE 2C Caminetto a Legna Autonomo",
  "p1_61:description": "Caminetto a legna autonomo danese Rais Q TEE 2C, design nordico minimalista.",
  "p1_60:name": "Rais Nexo Serie Caminetto a Legna Autonomo",
  "p1_60:description": "Caminetto a legna autonomo danese Rais Nexo serie, stile moderno.",
  "p1_59:name": "Rais Juno L Caminetto a Legna Autonomo",
  "p1_59:description": "Caminetto a legna autonomo danese Rais Juno L con finestra circolare.",
  "p1_58:name": "Rais Caro 90 Caminetto a Legna Autonomo",
  "p1_58:description": "Caminetto a legna autonomo danese Rais Caro 90, forma cilindrica.",
  "p1_28:name": "Rais Viva L Serie Caminetto a Legna Autonomo",
  "p1_28:description": "Caminetto a legna autonomo danese Rais Viva L serie, fiamma dinamica.",
  "p1_27:name": "Rais Visio 3 Caminetto a Legna Incasso Tre Facce",
  "p1_27:description": "Caminetto a legna incasso tre facce danese Rais Visio 3, vista 270°.",
  "p1_26:name": "Rais Q-TEE 2 Caminetto a Legna Autonomo",
  "p1_26:description": "Caminetto a legna autonomo danese Rais Q-TEE 2, design geometrico.",
  "p1_25:name": "Rais Q-BE Caminetto a Legna Autonomo Vista Angolare",
  "p1_25:description": "Caminetto a legna autonomo danese Rais Q-BE vista angolare.",
  "p1_24:name": "Rais Pilar Caminetto a Legna Autonomo",
  "p1_24:description": "Caminetto a legna autonomo danese Rais Pilar, design a colonna.",
  "p1_23:name": "Rais Bionic Fire Caminetto a Legna Doppia Camera",
  "p1_23:description": "Caminetto a legna danese Rais Bionic Fire a doppia camera.",
  "p1_22:name": "Haas+sohn Treviso Caminetto a Legna in Steatite",
  "p1_22:description": "Caminetto a legna in steatite austriaco Haas+sohn Treviso, calore duraturo.",
  "p1_21:name": "Haas+sohn Kuopio-II Caminetto a Legna in Steatite",
  "p1_21:description": "Caminetto a legna in steatite austriaco Haas+sohn Kuopio-II.",
  "p1_20:name": "Haas+sohn Ficus-II-RLU Caminetto a Legna Autonomo",
  "p1_20:description": "Caminetto a legna autonomo austriaco Haas+sohn Ficus-II-RLU, design curvo.",
  "p1_2:name": "Haas+sohn Aruba Easy Stufa a Legna in Steatite",
  "p1_2:description": "Stufa a legna in steatite austriaca Haas+sohn Aruba Easy.",
  "p1_35:name": "Ruegg Tillia Caminetto a Legna Incasso Tre Facce",
  "p1_35:description": "Caminetto a legna incasso tre facce svizzero Ruegg Tillia, precisione svizzera.",
  "p1_34:name": "Ruegg Rondeo Caminetto a Legna Incasso Vetro Curvo",
  "p1_34:description": "Caminetto a legna incasso svizzero Ruegg Rondeo con vetro curvo.",
  "p1_33:name": "Ruegg RII Caminetto a Legna Incasso d'Angolo",
  "p1_33:description": "Caminetto a legna incasso d'angolo svizzero Ruegg RII.",
  "p1_18:name": "Ruegg Odeon 270° Caminetto a Legna Sospeso Curvo",
  "p1_18:description": "Caminetto a legna sospeso curvo svizzero Ruegg Odeon 270°.",
  "p2_56:name": "Element4 Lucius 140 Caminetto a Gas da Incasso",
  "p2_56:description": "Caminetto a gas da incasso olandese Element4 Lucius 140.",
  "p2_55:name": "Element4 Tenore 140 Caminetto a Gas da Incasso",
  "p2_55:description": "Caminetto a gas da incasso olandese Element4 Tenore 140.",
  "p2_54:name": "Element4 Summum 100F Caminetto a Gas da Incasso",
  "p2_54:description": "Caminetto a gas da incasso olandese Element4 Summum 100F.",
  "p2_53:name": "Element4 Sky Serie Interna Caminetto a Gas",
  "p2_53:description": "Caminetto a gas interno olandese Element4 Sky, design integrato.",
  "p2_31:name": "Element4 Trisore 140 Caminetto a Gas Tre Facce",
  "p2_31:description": "Caminetto a gas tre facce olandese Element4 Trisore 140, vista panoramica.",
  "p2_29:name": "Element4 Bidore 100 Caminetto a Gas d'Angolo",
  "p2_29:description": "Caminetto a gas d'angolo olandese Element4 Bidore 100.",
  "p3_14:name": "Caminetto ad Alcol (Personalizzabile)",
  "p3_14:description": "Caminetto bioetanolo, dimensioni personalizzabili, ecologico.",
  "p4_70:name": "Caminetto a Nebbia Sospeso Diviso (Personalizzabile)",
  "p4_70:description": "Caminetto a nebbia 3D sospeso diviso, effetti personalizzabili.",
  "p4_69:name": "Caminetto a Nebbia Bifacciale (Personalizzabile)",
  "p4_69:description": "Caminetto a nebbia bifacciale, ideale per divisori.",
  "p4_68:name": "Caminetto a Nebbia Panoramico (Personalizzabile)",
  "p4_68:description": "Caminetto a nebbia panoramico ultra-wide.",
  "p4_67:name": "Caminetto a Nebbia Tre Facce (Personalizzabile)",
  "p4_67:description": "Caminetto a nebbia tre facce con vista 270°.",
  "p4_66:name": "Caminetto a Nebbia Rotondo (Personalizzabile)",
  "p4_66:description": "Caminetto a nebbia rotondo dal design circolare unico.",
  "p4_65:name": "Caminetto a Nebbia Sospeso UFO (Personalizzabile)",
  "p4_65:description": "Caminetto a nebbia sospeso a forma di UFO.",
  "p4_64:name": "Caminetto a Nebbia Divisorio (Personalizzabile)",
  "p4_64:description": "Caminetto a nebbia che funge da divisorio o schermo.",
  "p4_62:name": "Caminetto a Nebbia Unifacciale (Personalizzabile)",
  "p4_62:description": "Caminetto a nebbia unifacciale, design classico.",
  "p4_11:name": "Caminetto a Nebbia 3D Intelligente (Personalizzabile)",
  "p4_11:description": "Caminetto a nebbia 3D intelligente con controllo smart.",
  "p6_49:name": "Servizio Completo Caminetto Personalizzato",
  "p6_49:description": "Servizio completo di progettazione e installazione caminetti personalizzati.",
  "p7_6:name": "Caminetto Elettrico (Personalizzabile)",
  "p7_6:description": "Caminetto elettrico con effetti fiamma realistici.",
  "p88_51:name": "Fuoco all'Aperto (Personalizzabile)",
  "p88_51:description": "Fuoco all'aperto per giardino e patio, design personalizzabili.",
  "p8_52:name": "Set di Utensili per Caminetto",
  "p8_52:description": "Set di utensili per caminetto danese Rais, accessori di qualità.",
};

export default it_data;
