const ja: Record<string, string> = {
  // Categories
  "p1:name": "薪暖炉",
  "p2:name": "ガス暖炉",
  "p3:name": "アルコール暖炉",
  "p4:name": "ミスト暖炉",
  "p7:name": "電子暖炉",
  "p6:name": "カスタム暖炉",
  "p88:name": "屋外火景",
  "p8:name": "アクセサリー",

  // Installation types
  "独立式": "独立型",
  "嵌入式": "埋込型",
  "壁挂式": "壁掛型",
  "悬挂式": "吊下型",
  "悬挂/独立/嵌入": "吊下/独立/埋込",
  "独立/嵌入": "独立/埋込",
  "附件": "アクセサリー",

  // Countries
  "西班牙": "スペイン",
  "丹麦": "デンマーク",
  "奥地利": "オーストリア",
  "瑞士": "スイス",
  "荷兰": "オランダ",
  "中国": "中国",

  // === Product names & descriptions ===
  "p1_71:name": "Lacunza Altea オーブン付き独立型薪ストーブ",
  "p1_71:description": "スペインLacunza Alteaオーブン付き独立型薪ストーブ。調理と暖房を兼ね備えたクラシックデザイン。",
  "p1_1:name": "Lacunza Stelar 93 独立型薪暖炉",
  "p1_1:description": "スペインLacunza Stelar 93独立型薪暖炉。エレガントなデザインと優れた熱効率。",
  "p1_45:name": "Lacunza Sara 埋込型薪暖炉",
  "p1_45:description": "スペインLacunza Sara埋込型薪暖炉。シンプルな埋込デザインで省スペース。",
  "p1_44:name": "Lacunza Oslo 独立型薪ストーブ",
  "p1_44:description": "スペインLacunza Oslo独立型薪ストーブ。調理機能付き。",
  "p1_43:name": "Lacunza Nickel 両面埋込型薪暖炉",
  "p1_43:description": "スペインLacunza Nickel両面埋込型薪暖炉。両面ガラスで両側から炎を楽しめます。",
  "p1_42:name": "Lacunza K2 800 埋込型薪暖炉",
  "p1_42:description": "スペインLacunza K2 800埋込型薪暖炉。大きな観窓で空間全体を暖めます。",
  "p1_41:name": "Lacunza Itaca 片面埋込型薪暖炉",
  "p1_41:description": "スペインLacunza Itaca片面埋込型薪暖炉。クラシックな片面観火、効率的な暖房。",
  "p1_39:name": "Lacunza CM 300R コーナー独立型薪暖炉",
  "p1_39:description": "スペインLacunza CM 300Rコーナー独立型薪暖炉。コーナー設置に特化。",
  "p1_38:name": "Lacunza Clasica 7T オーブン付き薪ストーブ",
  "p1_38:description": "スペインLacunza Clasica 7Tオーブン付き薪ストーブ。ヨーロピアンカントリースタイル。",
  "p1_37:name": "Lacunza Atlantic 603 独立型薪暖炉",
  "p1_37:description": "スペインLacunza Atlantic 603独立型薪暖炉。風格ある外観と強力な暖房。",
  "p1_36:name": "Lacunza Adour 700ST 埋込型薪暖炉",
  "p1_36:description": "スペインLacunza Adour 700ST埋込型薪暖炉。シンプルなラインのモダンデザイン。",
  "p1_61:name": "Rais Q TEE 2C 独立型薪暖炉",
  "p1_61:description": "デンマークRais Q TEE 2C独立型薪暖炉。北欧ミニマリストデザイン、高効率燃焼。",
  "p1_60:name": "Rais Nexo シリーズ独立型薪暖炉",
  "p1_60:description": "デンマークRais Nexoシリーズ独立型薪暖炉。モダンでミニマルなスタイル。",
  "p1_59:name": "Rais Juno L 独立型薪暖炉",
  "p1_59:description": "デンマークRais Juno L独立型薪暖炉。円形観窓が特徴的なデザイン。",
  "p1_58:name": "Rais Caro 90 独立型薪暖炉",
  "p1_58:description": "デンマークRais Caro 90独立型薪暖炉。エレガントな円筒形状。",
  "p1_28:name": "Rais Viva L シリーズ独立型薪暖炉",
  "p1_28:description": "デンマークRais Viva Lシリーズ独立型薪暖炉。ダイナミックな炎の演出。",
  "p1_27:name": "Rais Visio 3 三面埋込型薪暖炉",
  "p1_27:description": "デンマークRais Visio 3三面埋込型薪暖炉。270°の炎の眺め。",
  "p1_26:name": "Rais Q-TEE 2 独立型薪暖炉",
  "p1_26:description": "デンマークRais Q-TEE 2独立型薪暖炉。幾何学的なアートデザイン。",
  "p1_25:name": "Rais Q-BE コーナー観火独立型薪暖炉",
  "p1_25:description": "デンマークRais Q-BEコーナー観火独立型薪暖炉。革新的な角度デザイン。",
  "p1_24:name": "Rais Pilar 独立型薪暖炉",
  "p1_24:description": "デンマークRais Pilar独立型薪暖炉。柱状デザイン、シンプルで風格あり。",
  "p1_23:name": "Rais Bionic Fire 二重燃焼独立型薪暖炉",
  "p1_23:description": "デンマークRais Bionic Fire二重燃焼独立型薪暖炉。革新的な二重燃焼技術。",
  "p1_22:name": "Haas+sohn Treviso ソープストーン独立型薪暖炉",
  "p1_22:description": "オーストリアHaas+sohn Trevisoソープストーン独立型薪暖炉。蓄熱で持続的な暖かさ。",
  "p1_21:name": "Haas+sohn Kuopio-II ソープストーン薪暖炉",
  "p1_21:description": "オーストリアHaas+sohn Kuopio-IIソープストーン独立型薪暖炉。クラシック北欧工芸。",
  "p1_20:name": "Haas+sohn Ficus-II-RLU 独立型薪暖炉",
  "p1_20:description": "オーストリアHaas+sohn Ficus-II-RLU独立型薪暖炉。エレガントな曲線デザイン。",
  "p1_2:name": "Haas+sohn Aruba Easy ソープストーン薪ストーブ",
  "p1_2:description": "オーストリアHaas+sohn Aruba easyソープストーン薪ストーブ。簡単操作、高効率蓄熱。",
  "p1_35:name": "Ruegg Tillia 三面埋込型薪暖炉",
  "p1_35:description": "スイスRuegg Tillia三面埋込型薪暖炉。スイスの精密な職人品質。",
  "p1_34:name": "Ruegg Rondeo 曲面ガラス埋込型薪暖炉",
  "p1_34:description": "スイスRuegg Rondeo曲面ガラス埋込型薪暖炉。ユニークな曲面ガラス。",
  "p1_33:name": "Ruegg RII コーナー埋込型薪暖炉",
  "p1_33:description": "スイスRuegg RIIコーナー埋込型薪暖炉。省スペースのコーナーデザイン。",
  "p1_18:name": "Ruegg Odeon 270° 曲面吊下型薪暖炉",
  "p1_18:description": "スイスRuegg Odeon 270°曲面吊下型薪暖炉。アートな吊下デザインとパノラマ眺望。",
  "p2_56:name": "Element4 Lucius 140 埋込型ガス暖炉",
  "p2_56:description": "オランダElement4 Lucius 140埋込型ガス暖炉。広い観窓、最新ガス技術。",
  "p2_55:name": "Element4 Tenore 140 埋込型ガス暖炉",
  "p2_55:description": "オランダElement4 Tenore 140埋込型ガス暖炉。リニアでミニマルなデザイン。",
  "p2_54:name": "Element4 Summum 100F 埋込型ガス暖炉",
  "p2_54:description": "オランダElement4 Summum 100F埋込型ガス暖炉。プレミアムガス暖炉体験。",
  "p2_53:name": "Element4 Sky 屋内シリーズガス暖炉",
  "p2_53:description": "オランダElement4 Sky屋内シリーズガス暖炉。シームレスな屋内・屋外デザイン。",
  "p2_31:name": "Element4 Trisore 140 三面ガス暖炉",
  "p2_31:description": "オランダElement4 Trisore 140三面埋込型ガス暖炉。パノラマの炎の眺め。",
  "p2_29:name": "Element4 Bidore 100 コーナーガス暖炉",
  "p2_29:description": "オランダElement4 Bidore 100コーナー埋込型ガス暖炉。両面コーナー観火。",
  "p3_14:name": "アルコール暖炉（カスタム可能）",
  "p3_14:description": "バイオエタノール暖炉。サイズや外観のカスタマイズ可能、環境に優しい。",
  "p4_70:name": "吊下・分離型ミスト暖炉（カスタム可能）",
  "p4_70:description": "3Dミスト暖炉、吊下・分離型デザイン、カスタマイズ可能な炎効果。",
  "p4_69:name": "両面観火ミスト暖炉（カスタム可能）",
  "p4_69:description": "両面観火ミスト暖炉。両側から炎が見え、間仕切り設置に最適。",
  "p4_68:name": "パノラマミスト暖炉（カスタム可能）",
  "p4_68:description": "パノラマミスト暖炉。超ワイドなパノラマ炎効果。",
  "p4_67:name": "三面観火ミスト暖炉（カスタム可能）",
  "p4_67:description": "三面観火ミスト暖炉。270°の炎の眺め、視覚的に圧倒。",
  "p4_66:name": "円形ミスト暖炉（カスタム可能）",
  "p4_66:description": "円形ミスト暖炉。ユニークな円形デザイン、アート感あふれる。",
  "p4_65:name": "UFO型吊下ミスト暖炉（カスタム可能）",
  "p4_65:description": "UFO型吊下ミスト暖炉。未来的な吊下デザイン。",
  "p4_64:name": "間仕切り・スクリーンミスト暖炉（カスタム可能）",
  "p4_64:description": "間仕切りやスクリーンとしても使えるミスト暖炉。",
  "p4_63:name": "「太陽の目」ミスト暖炉（カスタム可能）",
  "p4_63:description": "「太陽の目」ミスト暖炉。特徴的な円形デザイン。",
  "p4_62:name": "片面観火ミスト暖炉（カスタム可能）",
  "p4_62:description": "片面観火ミスト暖炉。クラシックな片面デザイン、壁設置に最適。",
  "p4_11:name": "スマート3Dミスト暖炉（カスタム可能）",
  "p4_11:description": "スマート3Dミスト暖炉。インテリジェント制御と3D立体炎効果。",
  "p6_49:name": "全カテゴリーカスタム暖炉サービス",
  "p6_49:description": "オーダーメイド暖炉の設計・施工サービス。全カテゴリー対応。",
  "p7_6:name": "電子暖炉（カスタム可能）",
  "p7_6:description": "リアルな炎効果の電子暖炉。サイズカスタマイズ可能、簡単設置。",
  "p88_51:name": "屋外火景（カスタム可能）",
  "p88_51:description": "庭やパティオ用の屋外火景。カスタマイズ可能なデザイン。",
  "p8_52:name": "暖炉ツールセット",
  "p8_52:description": "デンマークRais暖炉ツールセット。高品質アクセサリー。",
};

export default ja;
