const pt_data: Record<string, string> = {
  "p1:name": "Lareira a Lenha",
  "p2:name": "Lareira a Gás",
  "p3:name": "Lareira a Álcool",
  "p4:name": "Lareira de Névoa",
  "p7:name": "Lareira Elétrica",
  "p9:name": "Lareira Holográfica",
  "p6:name": "Lareira Personalizada",
  "p88:name": "Fogo Externo",
  "p8:name": "Acessórios",
  "独立式": "Autônomo",
  "嵌入式": "Embutido",
  "壁挂式": "De parede",
  "悬挂式": "Suspenso",
  "悬挂/独立/嵌入": "Suspenso / Autônomo / Embutido",
  "独立/嵌入": "Autônomo / Embutido",
  "附件": "Acessórios",
  "西班牙": "Espanha",
  "丹麦": "Dinamarca",
  "奥地利": "Áustria",
  "瑞士": "Suíça",
  "荷兰": "Países Baixos",
  "中国": "China",
  "p1_71:name": "Lacunza Altea Fogão a Lenha Autônomo com Forno",
  "p1_71:description": "Fogão a lenha autônomo espanhol Lacunza Altea com forno, combinando culinária e aquecimento.",
  "p1_1:name": "Lacunza Stelar 93 Lareira a Lenha Autônoma",
  "p1_1:description": "Lareira a lenha autônoma espanhola Lacunza Stelar 93, design elegante.",
  "p1_45:name": "Lacunza Sara Lareira a Lenha Embutida",
  "p1_45:description": "Lareira a lenha embutida espanhola Lacunza Sara, design minimalista.",
  "p1_44:name": "Lacunza Oslo Fogão a Lenha Autônomo",
  "p1_44:description": "Fogão a lenha autônomo espanhol Lacunza Oslo com função de cozinhar.",
  "p1_43:name": "Lacunza Nickel Lareira a Lenha Embutida Dupla Face",
  "p1_43:description": "Lareira a lenha embutida dupla face espanhola Lacunza Nickel.",
  "p1_42:name": "Lacunza K2 800 Lareira a Lenha Embutida",
  "p1_42:description": "Lareira a lenha embutida espanhola Lacunza K2 800 com grande vitrine.",
  "p1_41:name": "Lacunza Itaca Lareira a Lenha Embutida",
  "p1_41:description": "Lareira a lenha embutida unilateral espanhola Lacunza Itaca.",
  "p1_39:name": "Lacunza CM 300R Lareira a Lenha Autônoma de Canto",
  "p1_39:description": "Lareira a lenha autônoma de canto espanhola Lacunza CM 300R.",
  "p1_38:name": "Lacunza Clasica 7T Fogão a Lenha com Forno",
  "p1_38:description": "Fogão a lenha espanhol Lacunza Clasica 7T com forno, estilo campestre.",
  "p1_37:name": "Lacunza Atlantic 603 Lareira a Lenha Autônoma",
  "p1_37:description": "Lareira a lenha autônoma espanhola Lacunza Atlantic 603.",
  "p1_36:name": "Lacunza Adour 700ST Lareira a Lenha Embutida",
  "p1_36:description": "Lareira a lenha embutida espanhola Lacunza Adour 700ST.",
  "p1_61:name": "Rais Q TEE 2C Lareira a Lenha Autônoma",
  "p1_61:description": "Lareira a lenha autônoma dinamarquesa Rais Q TEE 2C, design nórdico.",
  "p1_60:name": "Rais Nexo Série Lareira a Lenha Autônoma",
  "p1_60:description": "Lareira a lenha autônoma dinamarquesa Rais Nexo série, estilo moderno.",
  "p1_59:name": "Rais Juno L Lareira a Lenha Autônoma",
  "p1_59:description": "Lareira a lenha autônoma dinamarquesa Rais Juno L com janela circular.",
  "p1_58:name": "Rais Caro 90 Lareira a Lenha Autônoma",
  "p1_58:description": "Lareira a lenha autônoma dinamarquesa Rais Caro 90, forma cilíndrica.",
  "p1_28:name": "Rais Viva L Série Lareira a Lenha Autônoma",
  "p1_28:description": "Lareira a lenha autônoma dinamarquesa Rais Viva L série.",
  "p1_27:name": "Rais Visio 3 Lareira a Lenha Embutida Três Faces",
  "p1_27:description": "Lareira a lenha embutida três faces dinamarquesa Rais Visio 3.",
  "p1_26:name": "Rais Q-TEE 2 Lareira a Lenha Autônoma",
  "p1_26:description": "Lareira a lenha autônoma dinamarquesa Rais Q-TEE 2.",
  "p1_25:name": "Rais Q-BE Lareira a Lenha Autônoma Vista Angular",
  "p1_25:description": "Lareira a lenha autônoma dinamarquesa Rais Q-BE.",
  "p1_24:name": "Rais Pilar Lareira a Lenha Autônoma",
  "p1_24:description": "Lareira a lenha autônoma dinamarquesa Rais Pilar.",
  "p1_23:name": "Rais Bionic Fire Lareira a Lenha Dupla Câmara",
  "p1_23:description": "Lareira a lenha dinamarquesa Rais Bionic Fire de câmara dupla.",
  "p1_22:name": "Haas+sohn Treviso Lareira a Lenha de Esteatito",
  "p1_22:description": "Lareira a lenha de esteatito austríaca Haas+sohn Treviso.",
  "p1_21:name": "Haas+sohn Kuopio-II Lareira a Lenha de Esteatito",
  "p1_21:description": "Lareira a lenha de esteatito austríaca Haas+sohn Kuopio-II.",
  "p1_20:name": "Haas+sohn Ficus-II-RLU Lareira a Lenha Autônoma",
  "p1_20:description": "Lareira a lenha autônoma austríaca Haas+sohn Ficus-II-RLU.",
  "p1_2:name": "Haas+sohn Aruba Easy Fogão a Lenha de Esteatito",
  "p1_2:description": "Fogão a lenha de esteatito austríaco Haas+sohn Aruba Easy.",
  "p1_35:name": "Ruegg Tillia Lareira a Lenha Embutida Três Faces",
  "p1_35:description": "Lareira a lenha embutida três faces suíça Ruegg Tillia.",
  "p1_34:name": "Ruegg Rondeo Lareira a Lenha Embutida Vidro Curvo",
  "p1_34:description": "Lareira a lenha embutida suíça Ruegg Rondeo com vidro curvo.",
  "p1_33:name": "Ruegg RII Lareira a Lenha Embutida de Canto",
  "p1_33:description": "Lareira a lenha embutida de canto suíça Ruegg RII.",
  "p1_18:name": "Ruegg Odeon 270° Lareira a Lenha Suspensa Curva",
  "p1_18:description": "Lareira a lenha suspensa curva suíça Ruegg Odeon 270°.",
  "p2_56:name": "Element4 Lucius 140 Lareira a Gás Embutida",
  "p2_56:description": "Lareira a gás embutida neerlandesa Element4 Lucius 140.",
  "p2_55:name": "Element4 Tenore 140 Lareira a Gás Embutida",
  "p2_55:description": "Lareira a gás embutida neerlandesa Element4 Tenore 140.",
  "p2_54:name": "Element4 Summum 100F Lareira a Gás Embutida",
  "p2_54:description": "Lareira a gás embutida neerlandesa Element4 Summum 100F.",
  "p2_53:name": "Element4 Sky Série Interna Lareira a Gás",
  "p2_53:description": "Lareira a gás interna neerlandesa Element4 Sky.",
  "p2_31:name": "Element4 Trisore 140 Lareira a Gás Três Faces",
  "p2_31:description": "Lareira a gás três faces neerlandesa Element4 Trisore 140.",
  "p2_29:name": "Element4 Bidore 100 Lareira a Gás de Canto",
  "p2_29:description": "Lareira a gás de canto neerlandesa Element4 Bidore 100.",
  "p3_14:name": "Lareira a Álcool (Personalizável)",
  "p3_14:description": "Lareira a bioetanol, tamanho personalizável, ecológica.",
  "p4_70:name": "Lareira de Névoa Suspensa Dividida (Personalizável)",
  "p4_70:description": "Lareira de névoa 3D suspensa dividida, efeitos personalizáveis.",
  "p4_61:name": "Lareira linear 3D a vapor com carvão decorativo",
  "p4_61:description": "Lareira linear 3D a vapor de água com efeito de carvão decorativo para hotéis, villas, clubes e projetos comerciais em atacado ou OEM/ODM.",
  "p4_69:name": "Lareira de Névoa Dupla Face (Personalizável)",
  "p4_69:description": "Lareira de névoa dupla face, ideal para divisórias.",
  "p4_68:name": "Lareira de Névoa Panorâmica (Personalizável)",
  "p4_68:description": "Lareira de névoa panorâmica ultra-larga.",
  "p4_67:name": "Lareira de Névoa Três Faces (Personalizável)",
  "p4_67:description": "Lareira de névoa três faces com vista 270°.",
  "p4_66:name": "Lareira de Névoa Redonda (Personalizável)",
  "p4_66:description": "Lareira de névoa redonda com design circular único.",
  "p4_65:name": "Lareira de Névoa Suspensa OVNI (Personalizável)",
  "p4_65:description": "Lareira de névoa suspensa em forma de OVNI.",
  "p4_64:name": "Lareira de Névoa Divisória (Personalizável)",
  "p4_64:description": "Lareira de névoa que serve como divisória.",
  "p4_62:name": "Lareira de Névoa Unilateral (Personalizável)",
  "p4_62:description": "Lareira de névoa unilateral, design clássico.",
  "p4_11:name": "Lareira de Névoa 3D Inteligente (Personalizável)",
  "p4_11:description": "Lareira de névoa 3D inteligente com controle inteligente.",
  "嵌入式 / 语音控制": "Embutida / controle por voz",
  "嵌入式 / 音乐播放": "Embutida / música",
  "嵌入式 / 户外防水": "Embutida / exterior impermeável",
  "圆形 / 仿真木柴": "Redonda / lenha decorativa",
  "独立式 / 半球装饰": "Independente / hemisférica",
  "p4_71:name": "Lareira linear 3D a vapor de água com controle por voz",
  "p4_71:description": "Lareira linear embutida 3D a vapor de água com controle por voz para hotéis, villas, clubes, showrooms e paredes comerciais. Comprimento, iluminação, embalagem e OEM/ODM personalizáveis.",
  "p4_72:name": "Lareira linear 3D a vapor de água com música",
  "p4_72:description": "Lareira linear embutida 3D a vapor de água com reprodução musical para apartamentos modelo, suítes de hotel, clubes e espaços de exposição.",
  "p4_73:name": "Lareira linear 3D a vapor de água impermeável para exterior",
  "p4_73:description": "Lareira linear 3D a vapor de água impermeável para terraços, áreas externas de hotéis, lounges comerciais e projetos semiabertos.",
  "p4_74:name": "Lareira redonda embutida 3D a vapor de água com lenha decorativa",
  "p4_74:description": "Lareira redonda embutida 3D a vapor de água com lenha decorativa para clubes, showrooms, lounges de hotel e instalações decorativas.",
  "p4_75:name": "Lareira decorativa hemisférica independente a vapor de água",
  "p4_75:description": "Lareira decorativa hemisférica independente 3D a vapor de água para lobbies de hotéis, clubes, showrooms e espaços comerciais sem chaminé.",
  "p6_49:name": "Serviço Completo de Lareira Personalizada",
  "p6_49:description": "Serviço completo de design e instalação de lareiras personalizadas.",
  "p7_6:name": "Lareira Elétrica (Personalizável)",
  "p7_6:description": "Lareira elétrica com efeitos de chama realistas.",
  "嵌入式 / 长条批发": "Embutida / linear atacado",
  "转角 / 双面观火": "Canto / duas faces",
  "四面观火": "Vista quatro faces",
  "圆形 / 定制": "Redonda / personalizada",
  "半圆 / 定制": "Semirredonda / personalizada",
  "三角形 / 定制": "Triangular / personalizada",
  "拱形 / 定制": "Arqueada / personalizada",
  "p7_10:name": "Lareira elétrica linear embutida para atacado",
  "p7_10:description": "Lareira elétrica linear embutida de 500 a 3000 mm para paredes de TV, hotéis, apartamentos modelo, showrooms e projetos em lote. Aquecimento, som, porta de proteção, moldura, cor e OEM/ODM opcionais.",
  "p7_11:name": "Lareira elétrica em L esquerda de duas faces",
  "p7_11:description": "Lareira elétrica de canto esquerdo com chama visível em duas faces para paredes multimídia e espaços comerciais. Preço conforme comprimento frontal e lateral.",
  "p7_12:name": "Lareira elétrica em L direita de duas faces",
  "p7_12:description": "Lareira elétrica de canto direito com chama visível em duas faces para instalações de canto e projetos personalizados.",
  "p7_13:name": "Lareira elétrica de três faces",
  "p7_13:description": "Lareira elétrica de três faces com vista de chama em 270 graus para instalação junto à parede, suítes de hotel e espaços comerciais.",
  "p7_14:name": "Lareira elétrica de três faces tipo B",
  "p7_14:description": "Lareira elétrica de três faces tipo B para lados longos visíveis e divisão de ambientes. Preço de atacado conforme comprimentos combinados.",
  "p7_15:name": "Lareira elétrica de quatro faces",
  "p7_15:description": "Lareira elétrica de quatro faces para ilhas, bancadas e áreas centrais com efeito de chama visível por todos os lados.",
  "p7_16:name": "Lareira elétrica redonda",
  "p7_16:description": "Lareira elétrica redonda com diâmetros de 500-700 mm para showrooms, lounges de hotel e estruturas decorativas personalizadas.",
  "p7_17:name": "Lareira elétrica semirredonda inferior",
  "p7_17:description": "Lareira elétrica semirredonda inferior para paredes curvas, painéis especiais e projetos personalizados de 500 a 700 mm.",
  "p7_18:name": "Lareira elétrica semirredonda superior",
  "p7_18:description": "Lareira elétrica semirredonda superior para arcos, curvas e paredes especiais com opções de tamanho, cor e função.",
  "p7_19:name": "Lareira elétrica triangular",
  "p7_19:description": "Lareira elétrica triangular para interiores de design, instalações de exposição e paredes especiais com lados de 500 a 700 mm.",
  "p7_20:name": "Lareira elétrica arqueada",
  "p7_20:description": "Lareira elétrica arqueada para espaços europeus, premium e comerciais com tamanhos 2DN500-2DN600 e personalização de projeto.",
  "p88_51:name": "Fogo Externo (Personalizável)",
  "p88_51:description": "Fogo externo para jardim e pátio, designs personalizáveis.",
  "p8_52:name": "Kit de Ferramentas para Lareira",
  "p8_52:description": "Kit de ferramentas para lareira dinamarquês Rais.",
};

export default pt_data;
