import { alibabaProducts } from "./alibaba-products";

export interface Product {
  id: string;
  category: string;
  brand: string;
  brandCountry: string;
  name: string;
  nameEn: string;
  description: string;
  descriptionEn: string;
  installation: string;
  priceCny?: number;
  images: string[];
  coverImage: string;
}

export const categories = [
  { id: "p1", name: "燃木壁炉", nameEn: "Wood Fireplace", icon: "🔥" },
  { id: "p3", name: "酒精壁炉", nameEn: "Ethanol Fireplace", icon: "🔥" },
  { id: "p4", name: "雾化壁炉", nameEn: "Mist Fireplace", icon: "💨" },
  { id: "p7", name: "电子壁炉", nameEn: "Electric Fireplace", icon: "⚡" },
  { id: "p9", name: "全息壁炉", nameEn: "Holographic Fireplace", icon: "✨" },
];

const activeCategoryIds = new Set(categories.map((category) => category.id));
const activeLegacyWoodProductIds = new Set(["p1_72"]);

export const brands = [
  { name: "壁炉宗师", country: "中国", nameEn: "Fireplace Master", countryEn: "China" },
];

const OSS = "/media/oss";
const ETHANOL_SERIES = "/media/products/ethanol-series";
const MIST_SERIES = "/media/products/mist-series";
const ELECTRIC_SERIES = "/media/products/electric-series";
const HOLOGRAPHIC_SERIES = "/media/products/holographic-series";

const productCatalog: Product[] = [
  // === LACUNZA (燃木) ===
  {
    id: "p1_71",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza Altea 带烤箱独立式燃木壁炉",
    nameEn: "Lacunza Altea Freestanding Wood Stove with Oven -",
    description: "。西班牙Lacunza Altea带烤箱独立式燃木壁炉，集烹饪与取暖于一体，经典设计。",
    descriptionEn:
      ". Spanish Lacunza Altea freestanding wood-burning fireplace with oven, combining cooking and heating in one classic design.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/ALtea/1.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/ALtea/1.jpg`,
  },
  {
    id: "p1_1",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza Stelar 93 独立式真火燃木壁炉",
    nameEn: "Lacunza Stelar 93 Freestanding Wood Fireplace -",
    description: "。西班牙Lacunza Stelar 93独立式真火燃木壁炉，造型优雅，热效卓越。",
    descriptionEn:
      ". Spanish Lacunza Stelar 93 freestanding wood fireplace, elegant design with卓越 heating efficiency.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/stelar%2093/%E5%86%85%E5%AE%B9%E9%A1%B51.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/stelar%2093/%E5%86%85%E5%AE%B9%E9%A1%B51.png`,
  },
  {
    id: "p1_45",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza Sara 嵌入式燃木真火壁炉",
    nameEn: "Lacunza Sara Built-in Wood Fireplace -",
    description: "。西班牙Lacunza Sara嵌入式燃木真火壁炉，简约嵌入设计，节省空间。",
    descriptionEn: ". Spanish Lacunza Sara built-in wood fireplace, space-saving minimalist design.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Sara/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Sara/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`,
  },
  {
    id: "p1_44",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza Oslo 可做饭独立式燃木真火壁炉",
    nameEn: "Lacunza Oslo Freestanding Wood Stove -",
    description: "。西班牙Lacunza Oslo可做饭独立式燃木真火壁炉，兼具烹饪功能。",
    descriptionEn: ". Spanish Lacunza Oslo freestanding wood stove with cooking functionality.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Oslo/%E5%86%85%E5%AE%B9%E9%A1%B51.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Oslo/%E5%86%85%E5%AE%B9%E9%A1%B51.png`,
  },
  {
    id: "p1_43",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza Nickel 嵌入式双面观火燃木真火壁炉",
    nameEn: "Lacunza Nickel Double-Sided Built-in Wood Fireplace -",
    description: "。西班牙Lacunza Nickel嵌入式双面观火燃木真火壁炉，双面玻璃设计，可观双面火焰。",
    descriptionEn:
      ". Spanish Lacunza Nickel double-sided built-in wood fireplace, dual glass panels for viewing fire from both sides.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Nickel%20/%E5%86%85%E5%AE%B9%E9%A1%B51.gif`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Nickel%20/%E5%86%85%E5%AE%B9%E9%A1%B51.gif`,
  },
  {
    id: "p1_42",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza K2 800 嵌入式燃木真火壁炉",
    nameEn: "Lacunza K2 800 Built-in Wood Fireplace -",
    description: "。西班牙Lacunza K2 800嵌入式燃木真火壁炉，大观火面设计，温暖整个空间。",
    descriptionEn: ". Spanish Lacunza K2 800 built-in wood fireplace with large viewing window.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/K2%20800/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/K2%20800/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`,
  },
  {
    id: "p1_41",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza Itaca 嵌入式单面真火燃木壁炉",
    nameEn: "Lacunza Itaca Built-in Wood Fireplace -",
    description: "。西班牙Lacunza Itaca嵌入式单面真火燃木壁炉，经典单面观火，高效取暖。",
    descriptionEn:
      ". Spanish Lacunza Itaca single-sided built-in wood fireplace, classic design with efficient heating.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Itaca/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Itaca/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`,
  },
  {
    id: "p1_39",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza CM 300R 角落独立式燃木真火壁炉",
    nameEn: "Lacunza CM 300R Corner Freestanding Wood Fireplace -",
    description: "。西班牙Lacunza CM 300R角落独立式燃木真火壁炉，专为角落空间设计。",
    descriptionEn:
      ". Spanish Lacunza CM 300R corner freestanding wood fireplace, designed for corner installation.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/CM%20300R/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/CM%20300R/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`,
  },
  {
    id: "p1_38",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza Clasica 7T 带烤箱可做饭燃木真火壁炉",
    nameEn: "Lacunza Clasica 7T Wood Stove with Oven -",
    description: "。西班牙Lacunza Clasica 7T带烤箱可做饭燃木真火壁炉，欧式乡村风格。",
    descriptionEn:
      ". Spanish Lacunza Clasica 7T wood stove with oven, European country style design.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Clasica/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Clasica/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`,
  },
  {
    id: "p1_37",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza Atlantic 603 独立式燃木真火壁炉",
    nameEn: "Lacunza Atlantic 603 Freestanding Wood Fireplace -",
    description: "。西班牙Lacunza Atlantic 603独立式燃木真火壁炉，大气外观，供暖强劲。",
    descriptionEn:
      ". Spanish Lacunza Atlantic 603 freestanding wood fireplace, grand appearance with powerful heating.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Atlantic%20603%20/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Atlantic%20603%20/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`,
  },
  {
    id: "p1_36",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza Adour 700ST 嵌入式燃木真火壁炉",
    nameEn: "Lacunza Adour 700ST Built-in Wood Fireplace -",
    description: "。西班牙Lacunza Adour 700ST嵌入式燃木真火壁炉，简约线条，现代设计。",
    descriptionEn:
      ". Spanish Lacunza Adour 700ST built-in wood fireplace, clean lines, modern design.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Adour%20700ST/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Adour%20700ST/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`,
  },
  // === RAIS (燃木) ===
  {
    id: "p1_61",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Q TEE 2C 独立式燃木真火壁炉",
    nameEn: "Rais Q TEE 2C Freestanding Wood Fireplace -",
    description: "。丹麦Rais Q TEE 2C独立式燃木真火壁炉，北欧简约设计，高效燃烧技术。",
    descriptionEn:
      ". Danish Rais Q TEE 2C freestanding wood fireplace, Nordic minimalist design,高效燃烧技术.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Q%20TEE%202C/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Q%20TEE%202C/1.png`,
  },
  {
    id: "p1_60",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Nexo 系列独立式燃木真火壁炉",
    nameEn: "Rais Nexo Series Freestanding Wood Fireplace -",
    description: "。丹麦Rais Nexo系列独立式燃木真火壁炉，现代极简风格。",
    descriptionEn:
      ". Danish Rais Nexo series freestanding wood fireplace, modern minimalist style.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Nexo%20120/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Nexo%20120/1.png`,
  },
  {
    id: "p1_59",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Juno L 独立式燃木真火壁炉",
    nameEn: "Rais Juno L Freestanding Wood Fireplace -",
    description: "。丹麦Rais Juno L独立式燃木真火壁炉，圆形观火窗，独特设计。",
    descriptionEn: ". Danish Rais Juno L freestanding wood fireplace with circular viewing window.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Juno%20L/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Juno%20L/1.png`,
  },
  {
    id: "p1_58",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Caro 90 独立式燃木真火壁炉",
    nameEn: "Rais Caro 90 Freestanding Wood Fireplace -",
    description: "。丹麦Rais Caro 90独立式燃木真火壁炉，优雅圆柱造型。",
    descriptionEn: ". Danish Rais Caro 90 freestanding wood fireplace, elegant cylindrical design.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Caro%2090/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Caro%2090/1.png`,
  },
  {
    id: "p1_28",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Viva L 系列独立式燃木真火壁炉",
    nameEn: "Rais Viva L Series Freestanding Wood Fireplace -",
    description: "。丹麦Rais Viva L系列独立式燃木真火壁炉，灵动火焰视觉效果。",
    descriptionEn:
      ". Danish Rais Viva L series freestanding wood fireplace, dynamic flame视觉效果.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Viva%20L/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Viva%20L/1.png`,
  },
  {
    id: "p1_27",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Visio 3 三面观火嵌入式燃木真火壁炉",
    nameEn: "Rais Visio 3 Three-Sided Built-in Wood Fireplace -",
    description: "。丹麦Rais Visio 3 三面观火嵌入式燃木真火壁炉，270°火焰视野。",
    descriptionEn:
      ". Danish Rais Visio 3 three-sided built-in wood fireplace, 270° flame view.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Visio/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Visio/1.png`,
  },
  {
    id: "p1_26",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Q-TEE 2 独立式燃木真火壁炉",
    nameEn: "Rais Q-TEE 2 Freestanding Wood Fireplace -",
    description: "。丹麦Rais Q-TEE 2独立式燃木真火壁炉，几何造型艺术感十足。",
    descriptionEn: ". Danish Rais Q-TEE 2 freestanding wood fireplace, geometric artistic design.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Q-TEE%202/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Q-TEE%202/1.png`,
  },
  {
    id: "p1_25",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Q-BE 独立式转角观火燃木真火壁炉",
    nameEn: "Rais Q-BE Corner View Freestanding Wood Fireplace -",
    description: "。丹麦Rais Q-BE独立式转角观火燃木真火壁炉，转角设计新颖独特。",
    descriptionEn: ". Danish Rais Q-BE corner-view freestanding wood fireplace, innovative angle design.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Q-BE/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Q-BE/1.png`,
  },
  {
    id: "p1_24",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Pilar 独立式燃木真火壁炉",
    nameEn: "Rais Pilar Freestanding Wood Fireplace -",
    description: "。丹麦Rais Pilar独立式燃木真火壁炉，柱形设计，简约大气。",
    descriptionEn: ". Danish Rais Pilar freestanding wood fireplace, pillar design,简约大气.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Pilar/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Pilar/1.png`,
  },
  {
    id: "p1_23",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Bionic Fire 双室燃烧独立式燃木真火壁炉",
    nameEn: "Rais Bionic Fire Dual-Chamber Wood Fireplace -",
    description: "。丹麦Rais Bionic Fire双室燃烧独立式燃木真火壁炉，创新双室燃烧技术。",
    descriptionEn:
      ". Danish Rais Bionic Fire dual-chamber combustion freestanding wood fireplace, innovative technology.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/bionic%20fire/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/bionic%20fire/1.png`,
  },
  // === HAAS+SOHN (燃木) ===
  {
    id: "p1_22",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "奥地利",
    name: "Haas+sohn Treviso 独立式皂石燃木真火壁炉",
    nameEn: "Haas+sohn Treviso Soapstone Wood Fireplace -",
    description: "。奥地利Haas+sohn Treviso独立式皂石燃木真火壁炉，皂石蓄热，持久温暖。",
    descriptionEn:
      ". Austrian Haas+sohn Treviso freestanding soapstone wood fireplace, soapstone heat storage for lasting warmth.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E5%A5%A5%E5%9C%B0%E5%88%A9Haas%2Bsohn/Treviso/1.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E5%A5%A5%E5%9C%B0%E5%88%A9Haas%2Bsohn/Treviso/1.jpg`,
  },
  {
    id: "p1_21",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "奥地利",
    name: "Haas+sohn Kuopio-II 独立式皂石燃木真火壁炉",
    nameEn: "Haas+sohn Kuopio-II Soapstone Wood Fireplace -",
    description: "。奥地利Haas+sohn Kuopio-II独立式皂石燃木真火壁炉，经典北欧皂石工艺。",
    descriptionEn:
      ". Austrian Haas+sohn Kuopio-II freestanding soapstone wood fireplace, classic Nordic soapstone craftsmanship.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E5%A5%A5%E5%9C%B0%E5%88%A9Haas%2Bsohn/Kuopi0-II/1.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E5%A5%A5%E5%9C%B0%E5%88%A9Haas%2Bsohn/Kuopi0-II/1.jpg`,
  },
  {
    id: "p1_20",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "奥地利",
    name: "Haas+sohn Ficus-II-RLU 独立式燃木真火壁炉",
    nameEn: "Haas+sohn Ficus-II-RLU Freestanding Wood Fireplace -",
    description: "。奥地利Haas+sohn Ficus-II-RLU独立式燃木真火壁炉，优雅曲线设计。",
    descriptionEn:
      ". Austrian Haas+sohn Ficus-II-RLU freestanding wood fireplace, elegant curved design.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E5%A5%A5%E5%9C%B0%E5%88%A9Haas%2Bsohn/Ficus-II-rlu/1.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E5%A5%A5%E5%9C%B0%E5%88%A9Haas%2Bsohn/Ficus-II-rlu/1.jpg`,
  },
  {
    id: "p1_2",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "奥地利",
    name: "Haas+sohn Aruba easy 独立式皂石燃木壁炉",
    nameEn: "Haas+sohn Aruba Easy Soapstone Wood Stove -",
    description: "。奥地利Haas+sohn Aruba easy独立式皂石燃木壁炉，操作简便，高效蓄热。",
    descriptionEn:
      ". Austrian Haas+sohn Aruba easy freestanding soapstone wood stove, easy operation, efficient heat storage.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E5%A5%A5%E5%9C%B0%E5%88%A9Haas%2Bsohn/Aruba/1.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E5%A5%A5%E5%9C%B0%E5%88%A9Haas%2Bsohn/Aruba/1.jpg`,
  },
  // === RUEGG (燃木) ===
  {
    id: "p1_35",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "瑞士",
    name: "Ruegg Tillia 嵌入式三面观火燃木真火壁炉",
    nameEn: "Ruegg Tillia Three-Sided Built-in Wood Fireplace -",
    description: "。瑞士Ruegg Tillia嵌入式三面观火燃木真火壁炉，瑞士精工品质。",
    descriptionEn:
      ". Swiss Ruegg Tillia three-sided built-in wood fireplace, Swiss precision craftsmanship.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E7%91%9E%E5%A3%ABRuegg/Tilia/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E7%91%9E%E5%A3%ABRuegg/Tilia/1.png`,
  },
  {
    id: "p1_34",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "瑞士",
    name: "Ruegg Rondeo 嵌入式弧面观火燃木真火壁炉",
    nameEn: "Ruegg Rondeo Curved Glass Built-in Wood Fireplace -",
    description: "。瑞士Ruegg Rondeo嵌入式弧面观火燃木真火壁炉，独特弧面玻璃设计。",
    descriptionEn:
      ". Swiss Ruegg Rondeo built-in wood fireplace with curved glass, unique弧形设计.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E7%91%9E%E5%A3%ABRuegg/Rondeo/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E7%91%9E%E5%A3%ABRuegg/Rondeo/1.png`,
  },
  {
    id: "p1_33",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "瑞士",
    name: "Ruegg RII 嵌入式转角观火燃木真火壁炉",
    nameEn: "Ruegg RII Corner Built-in Wood Fireplace -",
    description: "。瑞士Ruegg RII嵌入式转角观火燃木真火壁炉，转角设计节省空间。",
    descriptionEn: ". Swiss Ruegg RII corner built-in wood fireplace, space-saving corner design.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E7%91%9E%E5%A3%ABRuegg/RII/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E7%91%9E%E5%A3%ABRuegg/RII/1.png`,
  },
  {
    id: "p1_18",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "瑞士",
    name: "Ruegg Odeon 270°弧面观火悬挂燃木壁炉",
    nameEn: "Ruegg Odeon 270° Curved Suspended Wood Fireplace -",
    description: "。瑞士Ruegg Odeon 270°弧面观火悬挂燃木壁炉，艺术悬挂设计，270°全景视野。",
    descriptionEn:
      ". Swiss Ruegg Odeon 270° curved suspended wood fireplace, artistic悬挂设计 with panoramic view.",
    installation: "悬挂式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E7%91%9E%E5%A3%ABRuegg/Odeon/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E7%91%9E%E5%A3%ABRuegg/Odeon/1.png`,
  },
  // === ELEMENT 4 (燃气) ===
  {
    id: "p2_56",
    category: "p2",
    brand: "壁炉宗师",
    brandCountry: "荷兰",
    name: "Element4 Lucius 140 嵌入式燃气壁炉",
    nameEn: "Element4 Lucius 140 Built-in Gas Fireplace -",
    description: "。荷兰Element4 Lucius 140嵌入式燃气壁炉，宽大观火面，现代燃气技术。",
    descriptionEn:
      ". Dutch Element4 Lucius 140 built-in gas fireplace, large viewing area, modern gas technology.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Lucius%20140/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Lucius%20140/1.png`,
  },
  {
    id: "p2_55",
    category: "p2",
    brand: "壁炉宗师",
    brandCountry: "荷兰",
    name: "Element4 Tenore 140 嵌入式燃气壁炉",
    nameEn: "Element4 Tenore 140 Built-in Gas Fireplace -",
    description: "。荷兰Element4 Tenore 140嵌入式燃气壁炉，线性简约设计。",
    descriptionEn: ". Dutch Element4 Tenore 140 built-in gas fireplace, linear minimalist design.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Tenore%20140/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Tenore%20140/1.png`,
  },
  {
    id: "p2_54",
    category: "p2",
    brand: "壁炉宗师",
    brandCountry: "荷兰",
    name: "Element4 Summum 100F 嵌入式燃气壁炉",
    nameEn: "Element4 Summum 100F Built-in Gas Fireplace -",
    description: "。荷兰Element4 Summum 100F嵌入式燃气壁炉，顶级燃气壁炉体验。",
    descriptionEn:
      ". Dutch Element4 Summum 100F built-in gas fireplace, premium gas fireplace experience.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Summum%20100%20F/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Summum%20100%20F/1.png`,
  },
  {
    id: "p2_53",
    category: "p2",
    brand: "壁炉宗师",
    brandCountry: "荷兰",
    name: "Element4 Sky 室内系列嵌入式燃气壁炉",
    nameEn: "Element4 Sky Indoor Series Gas Fireplace -",
    description: "。荷兰Element4 Sky室内系列嵌入式燃气壁炉，室内外无缝融合设计。",
    descriptionEn:
      ". Dutch Element4 Sky indoor series gas fireplace, seamless indoor-outdoor design.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Sky%20%E5%AE%A4%E5%86%85%E7%B3%BB%E5%88%97/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Sky%20%E5%AE%A4%E5%86%85%E7%B3%BB%E5%88%97/1.png`,
  },
  {
    id: "p2_31",
    category: "p2",
    brand: "壁炉宗师",
    brandCountry: "荷兰",
    name: "Element4 Trisore 140 嵌入式三面观火燃气壁炉",
    nameEn: "Element4 Trisore 140 Three-Sided Gas Fireplace -",
    description: "。荷兰Element4 Trisore 140嵌入式三面观火燃气壁炉，三面玻璃全景火焰。",
    descriptionEn:
      ". Dutch Element4 Trisore 140 three-sided gas fireplace, panoramic flame view.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Trisore%20140/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Trisore%20140/1.png`,
  },
  {
    id: "p2_29",
    category: "p2",
    brand: "壁炉宗师",
    brandCountry: "荷兰",
    name: "Element4 Bidore 100 嵌入式转角观火燃气壁炉",
    nameEn: "Element4 Bidore 100 Corner Gas Fireplace -",
    description: "。荷兰Element4 Bidore 100嵌入式转角观火燃气壁炉，转角双面观火。",
    descriptionEn:
      ". Dutch Element4 Bidore 100 corner gas fireplace, dual-sided corner view.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Bidore%20100/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Bidore%20100/1.png`,
  },
  // === 酒精壁炉 ===
  {
    id: "p3_14",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "手动线性生物乙醇燃烧器（型号A01）",
    nameEn: "Manual Linear Bio Ethanol Burner - A01",
    description: "型号 A01，可选尺寸 600 mm / 800 mm / 1000 mm。面向海外品牌商、进口商、经销商和工程采购的嵌入式线性生物乙醇燃烧器，支持尺寸、外观、玻璃挡火、铭牌和出口包装定制。",
    descriptionEn:
      "Model A01, available size 600 mm / 800 mm / 1000 mm. Built-in linear bio ethanol burner for overseas brands, importers, distributors, and project buyers, with custom size, finish, glass guard, private label, and export packaging.",
    installation: "嵌入式 / 批量定制",
    priceCny: 1650,
    images: [
      `${ETHANOL_SERIES}/product/linear-burner.webp`,
      `${ETHANOL_SERIES}/scene/linear-burner.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/linear-burner.webp`,
  },
  {
    id: "p3_15",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "自动酒精燃烧器（型号A02）",
    nameEn: "Automatic Bio Ethanol Burner - A02",
    description: "型号 A02，可选尺寸 600 mm / 800 mm / 1000 mm / 1200 mm / +2。带自动点火和模块化结构的生物乙醇燃烧器，适合酒店、会所、别墅壁龛和批量工程定制。",
    descriptionEn:
      "Model A02, available size 600 mm / 800 mm / 1000 mm / 1200 mm / +2. Automatic bio ethanol burner with modular structure for hotels, clubs, villa niches, and project customization.",
    installation: "嵌入式 / 自动控制",
    priceCny: 12800,
    images: [
      `${ETHANOL_SERIES}/product/automatic-burner.webp`,
      `${ETHANOL_SERIES}/scene/automatic-burner.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/automatic-burner.webp`,
  },
  {
    id: "p3_16",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "双面隔断酒精壁炉（型号A03）",
    nameEn: "Double-Sided Ethanol Fireplace Divider - A03",
    description: "型号 A03，可选尺寸 1000 mm / 1200 mm / 1500 mm / 1800 mm / +1。双面观火结构，可作为餐厅、会所、客厅与商业空间的低矮隔断和真火视觉焦点。",
    descriptionEn:
      "Model A03, available size 1000 mm / 1200 mm / 1500 mm / 1800 mm / +1. Double-sided ethanol fireplace divider for restaurants, clubs, living rooms, and commercial interiors.",
    installation: "双面 / 隔断式",
    priceCny: 16800,
    images: [
      `${ETHANOL_SERIES}/product/double-sided-divider.webp`,
      `${ETHANOL_SERIES}/scene/double-sided-divider.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/double-sided-divider.webp`,
  },
  {
    id: "p3_17",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "三面观火酒精壁炉（型号A04）",
    nameEn: "Three-Sided Ethanol Fireplace - A04",
    description: "型号 A04，可选尺寸 1000 mm / 1200 mm / 1500 mm / 1800 mm / +1。三面可视真火结构，适合半岛式背景墙、端景墙和高端住宅会客空间。",
    descriptionEn:
      "Model A04, available size 1000 mm / 1200 mm / 1500 mm / 1800 mm / +1. Three-sided real-flame ethanol fireplace for peninsula feature walls and premium residential lounges.",
    installation: "三面观火",
    priceCny: 19800,
    images: [
      `${ETHANOL_SERIES}/product/three-sided-peninsula.webp`,
      `${ETHANOL_SERIES}/scene/three-sided-peninsula.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/three-sided-peninsula.webp`,
  },
  {
    id: "p3_18",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "桌面酒精壁炉（型号A05）",
    nameEn: "Tabletop Ethanol Fireplace - A05",
    description: "型号 A05，可选尺寸 300 mm / 400 mm / 600 mm。小型桌面生物乙醇壁炉，适合样板间、民宿、公寓、餐桌和轻量级软装氛围。",
    descriptionEn:
      "Model A05, available size 300 mm / 400 mm / 600 mm. Compact tabletop ethanol fireplace for model rooms, apartments, dining tables, and decorative atmosphere.",
    installation: "桌面式",
    priceCny: 2800,
    images: [
      `${ETHANOL_SERIES}/product/tabletop.webp`,
      `${ETHANOL_SERIES}/scene/tabletop.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/tabletop.webp`,
  },
  {
    id: "p3_19",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "独立式酒精壁炉（型号A06）",
    nameEn: "Freestanding Ethanol Fireplace - A06",
    description: "型号 A06，可选尺寸 500 mm / 800 mm / 1000 mm。可移动独立式酒精壁炉，适合客厅、休闲区、会所和不方便开孔的空间。",
    descriptionEn:
      "Model A06, available size 500 mm / 800 mm / 1000 mm. Freestanding ethanol fireplace for lounges, clubs, living rooms, and spaces where built-in work is difficult.",
    installation: "独立式",
    priceCny: 6800,
    images: [
      `${ETHANOL_SERIES}/product/freestanding.webp`,
      `${ETHANOL_SERIES}/scene/freestanding.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/freestanding.webp`,
  },
  {
    id: "p3_20",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "圆形酒精火盆（型号A07）",
    nameEn: "Round Ethanol Fire Bowl - A07",
    description: "型号 A07，可选尺寸 Ø600 mm / Ø800 mm / Ø1000 mm / Ø1200 mm。圆形真火酒精火盆，适合庭院、露台、度假酒店和户外休闲空间。",
    descriptionEn:
      "Model A07, available size Ø600 mm / Ø800 mm / Ø1000 mm / Ø1200 mm. Round real-flame ethanol fire bowl for patios, terraces, resort hotels, and outdoor lounge spaces.",
    installation: "户外 / 火盆",
    priceCny: 5800,
    images: [
      `${ETHANOL_SERIES}/product/round-fire-bowl.webp`,
      `${ETHANOL_SERIES}/scene/round-fire-bowl.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/round-fire-bowl.webp`,
  },
  {
    id: "p3_21",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "户外酒精火桌（型号A08）",
    nameEn: "Outdoor Ethanol Fire Table - A08",
    description: "型号 A08，可选尺寸 1200 mm / 1500 mm / 1800 mm / 2400 mm。户外长条酒精火桌，适合露台、屋顶花园、商业外摆和度假酒店项目。",
    descriptionEn:
      "Model A08, available size 1200 mm / 1500 mm / 1800 mm / 2400 mm. Outdoor ethanol fire table for terraces, rooftop gardens, commercial patios, and resort projects.",
    installation: "户外 / 火桌",
    priceCny: 15800,
    images: [
      `${ETHANOL_SERIES}/product/outdoor-fire-table.webp`,
      `${ETHANOL_SERIES}/scene/outdoor-fire-table.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/outdoor-fire-table.webp`,
  },
  {
    id: "p3_22",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "岩板岛台酒精壁炉（型号A09）",
    nameEn: "Stone Island Ethanol Fireplace - A09",
    description: "型号 A09，可选尺寸 1200 mm / 1600 mm / 2000 mm / 2600 mm。岩板或石材岛台式酒精壁炉，可与客厅、餐厅、开放式厨房和商业接待空间结合。",
    descriptionEn:
      "Model A09, available size 1200 mm / 1600 mm / 2000 mm / 2600 mm. Stone island ethanol fireplace for living rooms, dining areas, open kitchens, and commercial reception spaces.",
    installation: "岛台式",
    priceCny: 22800,
    images: [
      `${ETHANOL_SERIES}/product/stone-island.webp`,
      `${ETHANOL_SERIES}/scene/stone-island.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/stone-island.webp`,
  },
  {
    id: "p3_23",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "酒店大堂长条酒精壁炉（型号A10）",
    nameEn: "Hotel Lobby Linear Ethanol Fireplace - A10",
    description: "型号 A10，可选尺寸 2000 mm / 3000 mm / 4000 mm / 6000 mm。超长线性酒精壁炉，适合酒店大堂、会所、售楼部和商业接待区的真火主景。",
    descriptionEn:
      "Model A10, available size 2000 mm / 3000 mm / 4000 mm / 6000 mm. Extra-long linear ethanol fireplace for hotel lobbies, clubs, sales centers, and commercial reception areas.",
    installation: "工程长条",
    priceCny: 32800,
    images: [
      `${ETHANOL_SERIES}/product/hotel-lobby-linear.webp`,
      `${ETHANOL_SERIES}/scene/hotel-lobby-linear.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/hotel-lobby-linear.webp`,
  },
  {
    id: "p3_24",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "嵌入式壁龛酒精壁炉套件（型号A11）",
    nameEn: "Built-In Ethanol Fireplace Niche Kit - A11",
    description: "型号 A11，可选尺寸 800 mm / 1200 mm / 1600 mm / 2000 mm。适合背景墙和壁龛安装的酒精壁炉套件，包含框体、火槽、玻璃挡火和安装结构。",
    descriptionEn:
      "Model A11, available size 800 mm / 1200 mm / 1600 mm / 2000 mm. Built-in ethanol fireplace niche kit with frame, burner, glass guard, and installation structure.",
    installation: "壁龛嵌入式",
    priceCny: 9800,
    images: [
      `${ETHANOL_SERIES}/product/wall-niche-kit.webp`,
      `${ETHANOL_SERIES}/scene/wall-niche-kit.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/wall-niche-kit.webp`,
  },
  {
    id: "p3_25",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "酒精燃烧器套件（型号A12）",
    nameEn: "Ethanol Burner Kit - A12",
    description: "型号 A12，可选尺寸 400 mm / 800 mm / 1200 mm / 1600 mm。面向品牌方、工程商和批量客户的酒精燃烧器套件，可按图纸、样品和包装需求定制。",
    descriptionEn:
      "Model A12, available size 400 mm / 800 mm / 1200 mm / 1600 mm. OEM ethanol burner kit for brands, contractors, and batch buyers, customizable by drawings, samples, and packaging needs.",
    installation: "OEM套件",
    priceCny: 4800,
    images: [
      `${ETHANOL_SERIES}/product/oem-burner-kit.webp`,
      `${ETHANOL_SERIES}/scene/oem-burner-kit.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/oem-burner-kit.webp`,
  },
  {
    id: "p3_26",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "悬挂式酒精壁炉（型号A13）",
    nameEn: "Suspended Ethanol Fireplace - A13",
    description: "型号 A13，可选尺寸 Ø800 mm / Ø1000 mm / Ø1200 mm。悬挂式艺术造型酒精壁炉，适合挑高客厅、会所、民宿和设计感空间。",
    descriptionEn:
      "Model A13, available size Ø800 mm / Ø1000 mm / Ø1200 mm. Suspended sculptural ethanol fireplace for high-ceiling living rooms, clubs, boutique hotels, and design-led interiors.",
    installation: "悬挂式",
    priceCny: 13800,
    images: [
      `${ETHANOL_SERIES}/product/suspended-fireplace.webp`,
      `${ETHANOL_SERIES}/scene/suspended-fireplace.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/suspended-fireplace.webp`,
  },
  // === 雾化壁炉 ===
  {
    id: "p4_70",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "长条雾化壁炉模块（型号M01）",
    nameEn: "Linear Mist Fireplace Module - M01",
    description: "型号 M01，可选尺寸 600 mm / 700 mm / 800 mm / 900 mm / +11。长条3D水雾壁炉模块，适合酒店大堂、会所、别墅客厅和商业背景墙，支持长度、灯光、补水排水和OEM/ODM定制。",
    descriptionEn:
      "Model M01, available size 600 mm / 700 mm / 800 mm / 900 mm / +11. Linear 3D water vapor fireplace module for hotel lobbies, clubs, villas, and commercial feature walls, customizable by length, lighting, water access, and OEM/ODM requirements.",
    installation: "嵌入式 / 长条",
    priceCny: 913.5984,
    images: [
      `${MIST_SERIES}/product/linear-mist-module.webp`,
      `${MIST_SERIES}/scene/linear-mist-module.webp`,
    ],
    coverImage: `${MIST_SERIES}/product/linear-mist-module.webp`,
  },
  {
    id: "p4_61",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "仿木炭长条3D雾化壁炉（型号M11）",
    nameEn: "Linear 3D Mist Fireplace with Charcoal Logs - M11",
    description: "型号 M11，可选尺寸 600 mm / 700 mm / 800 mm / 900 mm / +11。带仿木炭装饰的长条3D雾化壁炉，适合酒店、别墅、会所和商业空间批量项目，火焰层次更接近真火视觉。",
    descriptionEn:
      "Model M11, available size 600 mm / 700 mm / 800 mm / 900 mm / +11. Linear 3D water vapor fireplace with decorative charcoal logs for hotels, villas, clubs, and commercial projects, creating a richer real-flame visual effect without heat or open fire.",
    installation: "嵌入式 / 长条 / 仿木炭",
    priceCny: 1086.194,
    images: [
      `${MIST_SERIES}/product/charcoal-linear-mist-front.webp`,
      `${MIST_SERIES}/product/charcoal-linear-mist-angle.webp`,
      `${MIST_SERIES}/product/charcoal-linear-mist-detail.webp`,
      `${MIST_SERIES}/scene/charcoal-linear-mist-living-room.webp`,
      `${MIST_SERIES}/scene/charcoal-linear-mist-hotel-lobby.webp`,
      `${MIST_SERIES}/scene/charcoal-linear-mist-installation.webp`,
    ],
    coverImage: `${MIST_SERIES}/product/charcoal-linear-mist-front.webp`,
  },
  {
    id: "p4_71",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "语音控制长条嵌入式3D雾化壁炉（型号M12）",
    nameEn: "Voice-Control Linear Built-In 3D Mist Fireplace - M12",
    description: "型号 M12，可选尺寸 600 mm / 700 mm / 800 mm / 900 mm / +11。带语音控制的长条嵌入式3D雾化壁炉，适合酒店、别墅、会所、展厅和商业背景墙项目，支持长度、灯光、包装和OEM/ODM批量定制。",
    descriptionEn: "Model M12, available size 600 mm / 700 mm / 800 mm / 900 mm / +11. Voice-control linear built-in 3D water vapor fireplace for hotels, villas, clubs, showrooms, and commercial feature walls. Length, lighting, packing, and OEM/ODM details can be customized for wholesale projects.",
    installation: "嵌入式 / 语音控制",
    priceCny: 969.5984,
    images: [
      "/media/products/mist-series/product/m12-voice-linear-mist.webp",
      "/media/products/mist-series/product/m12-voice-linear-mist-white.webp",
      "/media/products/mist-series/product/m12-voice-linear-mist-dark.webp",
      "/media/products/mist-series/scene/linear-mist-module.webp",
      "/media/products/mist-series/scene/charcoal-linear-mist-hotel-lobby.webp",
      "/media/products/mist-series/scene/charcoal-linear-mist-installation.webp",
    ],
    coverImage: "/media/products/mist-series/product/m12-voice-linear-mist.webp",
  },
  {
    id: "p4_72",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "音乐播放长条嵌入式3D雾化壁炉（型号M13）",
    nameEn: "Music Playback Linear Built-In 3D Mist Fireplace - M13",
    description: "型号 M13，可选尺寸 600 mm / 700 mm / 800 mm / 900 mm / +11。带音乐播放功能的长条嵌入式3D雾化壁炉，适合样板间、酒店套房、会所和展示空间，增强火焰展示氛围。",
    descriptionEn: "Model M13, available size 600 mm / 700 mm / 800 mm / 900 mm / +11. Music playback linear built-in 3D mist fireplace for show flats, hotel suites, clubs, and display spaces where atmosphere and flame presentation matter.",
    installation: "嵌入式 / 音乐播放",
    priceCny: 1014.5984,
    images: [
      "/media/products/mist-series/product/m13-music-linear-mist.webp",
      "/media/products/mist-series/product/m13-music-linear-mist-white.webp",
      "/media/products/mist-series/product/m13-music-linear-mist-dark.webp",
      "/media/products/mist-series/scene/linear-mist-module.webp",
      "/media/products/mist-series/scene/charcoal-linear-mist-hotel-lobby.webp",
      "/media/products/mist-series/scene/charcoal-linear-mist-installation.webp",
    ],
    coverImage: "/media/products/mist-series/product/m13-music-linear-mist.webp",
  },
  {
    id: "p4_73",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "户外防水长条嵌入式3D雾化壁炉（型号M14）",
    nameEn: "Outdoor Waterproof Linear Built-In 3D Mist Fireplace - M14",
    description: "型号 M14，可选尺寸 600 mm / 700 mm / 800 mm / 900 mm / +11。户外防水长条嵌入式3D雾化壁炉，适合庭院、露台、酒店外摆、商业休闲区和半户外工程项目。",
    descriptionEn: "Model M14, available size 600 mm / 700 mm / 800 mm / 900 mm / +11. Outdoor waterproof linear built-in 3D mist fireplace for patios, terraces, hotel outdoor seating, commercial lounge areas, and semi-outdoor projects.",
    installation: "嵌入式 / 户外防水",
    priceCny: 1049.5984,
    images: [
      "/media/products/mist-series/product/m14-outdoor-linear-mist.webp",
      "/media/products/mist-series/product/m14-outdoor-linear-mist-white.webp",
      "/media/products/mist-series/product/m14-outdoor-linear-mist-dark.webp",
      "/media/products/mist-series/scene/linear-mist-module.webp",
      "/media/products/mist-series/scene/charcoal-linear-mist-hotel-lobby.webp",
      "/media/products/mist-series/scene/charcoal-linear-mist-installation.webp",
    ],
    coverImage: "/media/products/mist-series/product/m14-outdoor-linear-mist.webp",
  },
  {
    id: "p4_74",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "圆形嵌入式3D雾化壁炉带仿真木柴装饰（型号M15）",
    nameEn: "Round Built-In 3D Mist Fireplace with Decorative Logs - M15",
    description: "型号 M15，可选尺寸 Ø500 mm / Ø550 mm / Ø600 mm。圆形嵌入式3D雾化壁炉，带仿真木柴装饰，适合会所、展厅、酒店休闲区和装饰性工程项目。",
    descriptionEn: "Model M15, available size Ø500 mm / Ø550 mm / Ø600 mm. Round built-in 3D mist fireplace with decorative logs for clubs, showrooms, hotel lounge areas, and decorative project installations.",
    installation: "圆形 / 仿真木柴",
    priceCny: 1622.7552,
    images: [
      "/media/products/mist-series/product/m15-round-charcoal-mist.webp",
      "/media/products/mist-series/product/m15-round-charcoal-mist-white.webp",
      "/media/products/mist-series/product/m15-round-charcoal-mist-dark.webp",
      "/media/products/mist-series/scene/round-mist-bowl.webp",
      "/media/products/mist-series/scene/charcoal-linear-mist-living-room.webp",
      "/media/products/mist-series/scene/charcoal-linear-mist-hotel-lobby.webp",
    ],
    coverImage: "/media/products/mist-series/product/m15-round-charcoal-mist.webp",
  },
  {
    id: "p4_75",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "半球独立装饰雾化壁炉（型号M16）",
    nameEn: "Freestanding Hemisphere Decorative Mist Fireplace - M16",
    description: "型号 M16，可选尺寸 Ø556 mm / Ø600 mm / Ø650 mm。半球独立装饰雾化壁炉，适合酒店大堂、会所、展厅、商业空间和室内软装展示，无需传统烟道。",
    descriptionEn: "Model M16, available size Ø556 mm / Ø600 mm / Ø650 mm. Freestanding hemisphere decorative 3D mist fireplace for hotel lobbies, clubs, showrooms, commercial spaces, and interior display areas without chimney work.",
    installation: "独立式 / 半球装饰",
    priceCny: 1785.0307,
    images: [
      "/media/products/mist-series/product/m16-hemisphere-mist.webp",
      "/media/products/mist-series/product/m16-hemisphere-mist-white.webp",
      "/media/products/mist-series/product/m16-hemisphere-mist-dark.webp",
      "/media/products/mist-series/scene/round-mist-bowl.webp",
      "/media/products/mist-series/scene/charcoal-linear-mist-living-room.webp",
      "/media/products/mist-series/scene/charcoal-linear-mist-hotel-lobby.webp",
    ],
    coverImage: "/media/products/mist-series/product/m16-hemisphere-mist.webp",
  },
  {
    id: "p4_69",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "双面隔断雾化壁炉（型号M02）",
    nameEn: "Double-Sided Mist Fireplace Divider - M02",
    description: "型号 M02，可选尺寸 600 mm / 700 mm / 800 mm / 900 mm / +11。双面水雾火焰结构，可作为餐厅、会所、售楼部和开放式空间隔断，适合长时间展示。",
    descriptionEn: "Model M02, available size 600 mm / 700 mm / 800 mm / 900 mm / +11. Double-sided mist fireplace divider for restaurants, clubs, sales centers, and open-plan spaces.",
    installation: "双面 / 隔断式",
    priceCny: 1004.9582,
    images: [
      `${MIST_SERIES}/product/double-sided-divider.webp`,
      `${MIST_SERIES}/scene/double-sided-divider.webp`,
    ],
    coverImage: `${MIST_SERIES}/product/double-sided-divider.webp`,
  },
  {
    id: "p4_68",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "全景观火雾化壁炉（型号M03）",
    nameEn: "Panoramic Mist Fireplace - M03",
    description: "型号 M03，可选尺寸 1200 mm / 1500 mm / 1800 mm / 2400 mm / +1。壁炉宗师全景观火雾化壁炉，超宽全景火焰效果。",
    descriptionEn: "Model M03, available size 1200 mm / 1500 mm / 1800 mm / 2400 mm / +1. Panoramic mist fireplace with ultra-wide flame viewing area.",
    installation: "嵌入式",
    priceCny: 14800,
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E5%85%A8%E6%99%AF%E8%A7%82%E7%81%AB/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E5%85%A8%E6%99%AF%E8%A7%82%E7%81%AB/1.png`,
  },
  {
    id: "p4_67",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "三面观火雾化壁炉（型号M04）",
    nameEn: "Three-Sided Mist Fireplace - M04",
    description: "型号 M04，可选尺寸 1000 mm / 1200 mm / 1500 mm / 1800 mm / +1。壁炉宗师三面观火雾化壁炉，270°火焰视野，视觉震撼。",
    descriptionEn: "Model M04, available size 1000 mm / 1200 mm / 1500 mm / 1800 mm / +1. Three-sided mist fireplace with 270° flame view.",
    installation: "嵌入式",
    priceCny: 17800,
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E4%B8%89%E9%9D%A2%E8%A7%82%E7%81%AB/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E4%B8%89%E9%9D%A2%E8%A7%82%E7%81%AB/1.png`,
  },
  {
    id: "p4_66",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "圆形雾化火盆（型号M05）",
    nameEn: "Round Mist Fire Bowl - M05",
    description: "型号 M05，可选尺寸 Ø300 mm / Ø350 mm / Ø400 mm / Ø450 mm / +4。圆形3D雾化火盆，适合会所、展厅、庭院半户外区域和艺术装置空间。",
    descriptionEn: "Model M05, available size Ø300 mm / Ø350 mm / Ø400 mm / Ø450 mm / +4. Round 3D mist fire bowl for clubs, showrooms, semi-outdoor patios, and art feature spaces.",
    installation: "圆形 / 火盆",
    priceCny: 1060,
    images: [
      `${MIST_SERIES}/product/round-mist-bowl.webp`,
      `${MIST_SERIES}/scene/round-mist-bowl.webp`,
    ],
    coverImage: `${MIST_SERIES}/product/round-mist-bowl.webp`,
  },
  {
    id: "p4_65",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "悬挂式雾化壁炉（型号M06）",
    nameEn: "Suspended Mist Fireplace - M06",
    description: "型号 M06，可选尺寸 Ø800 mm / Ø1000 mm / Ø1200 mm。悬挂式水雾壁炉，适合挑高客厅、会所、民宿和商业空间做中心视觉装置。",
    descriptionEn: "Model M06, available size Ø800 mm / Ø1000 mm / Ø1200 mm. Suspended mist fireplace for high-ceiling living rooms, clubs, boutique stays, and commercial focal installations.",
    installation: "悬挂式",
    priceCny: 18800,
    images: [
      `${MIST_SERIES}/product/suspended-mist.webp`,
      `${MIST_SERIES}/scene/suspended-mist.webp`,
    ],
    coverImage: `${MIST_SERIES}/product/suspended-mist.webp`,
  },
  {
    id: "p4_64",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "隔断/屏风雾化壁炉（型号M07）",
    nameEn: "Room Divider Mist Fireplace - M07",
    description: "型号 M07，可选尺寸 1200 mm / 1500 mm / 2000 mm / 3000 mm。壁炉宗师可做隔断/屏风雾化壁炉，兼具隔断与装饰功能。",
    descriptionEn: "Model M07, available size 1200 mm / 1500 mm / 2000 mm / 3000 mm. Mist fireplace that doubles as a room divider or screen.",
    installation: "嵌入式",
    priceCny: 15800,
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E9%9A%94%E6%96%AD%3A%E5%B1%8F%E9%A3%8E/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E9%9A%94%E6%96%AD%3A%E5%B1%8F%E9%A3%8E/1.png`,
  },
  {
    id: "p4_63",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: '"太阳之眼"雾化壁炉（型号M08）',
    nameEn: '"Eye of the Sun" Mist Fireplace - M08',
    description: '型号 M08，可选尺寸 Ø1000 mm / Ø1200 mm / Ø1500 mm / Ø1800 mm。壁炉宗师"太阳之眼"雾化壁炉，独特圆形造型，如太阳之眼。',
    descriptionEn: 'Model M08, available size Ø1000 mm / Ø1200 mm / Ø1500 mm / Ø1800 mm. "Eye of the Sun" mist fireplace with distinctive circular design.',
    installation: "嵌入式",
    priceCny: 23800,
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E5%A4%AA%E9%98%B3%E4%B9%8B%E7%9C%BC/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E5%A4%AA%E9%98%B3%E4%B9%8B%E7%9C%BC/1.png`,
  },
  {
    id: "p4_62",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "单面观火雾化壁炉（型号M09）",
    nameEn: "Single-Sided Mist Fireplace - M09",
    description: "型号 M09，可选尺寸 800 mm / 1200 mm / 1500 mm / 1800 mm / +1。壁炉宗师单面观火雾化壁炉，经典单面设计，适合壁挂安装。",
    descriptionEn: "Model M09, available size 800 mm / 1200 mm / 1500 mm / 1800 mm / +1. Single-sided mist fireplace, classic design for wall installation.",
    installation: "嵌入式",
    priceCny: 12800,
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E5%8D%95%E9%9D%A2%E8%A7%82%E7%81%AB/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E5%8D%95%E9%9D%A2%E8%A7%82%E7%81%AB/1.png`,
  },
  {
    id: "p4_11",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "智能3D雾化壁炉（型号M10）",
    nameEn: "Smart 3D Mist Fireplace - M10",
    description: "型号 M10，可选尺寸 600 mm / 700 mm / 800 mm / 900 mm / +11。壁炉宗师智能3D雾化壁炉，智能控制，3D立体火焰效果。",
    descriptionEn: "Model M10, available size 600 mm / 700 mm / 800 mm / 900 mm / +11. Smart 3D mist fireplace with intelligent control and 3D flame effects.",
    installation: "嵌入式",
    priceCny: 913.5984,
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/1.png`,
  },
  // === 定制壁炉 ===
  {
    id: "p6_49",
    category: "p6",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "全品类定制壁炉服务",
    nameEn: "Full Category Custom Fireplace Service -",
    description: "。壁炉宗师提供个性化全品类壁炉定制服务，从设计到安装一站式解决。",
    descriptionEn:
      ". Full-service custom fireplace design and installation for all categories.",
    installation: "悬挂/独立/嵌入",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E5%AE%9A%E5%88%B6%E5%A3%81%E7%82%89/%E5%86%85%E5%AE%B9%E9%A1%B5.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E5%AE%9A%E5%88%B6%E5%A3%81%E7%82%89/%E5%86%85%E5%AE%B9%E9%A1%B5.png`,
  },
  // === 电子壁炉 ===
  {
    id: "p7_6",
    category: "p7",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "长条嵌入式电子壁炉（型号E01）",
    nameEn: "Linear Built-In Electric Fireplace - E01",
    description: "型号 E01，可选尺寸 800 mm / 1200 mm / 1500 mm / 1800 mm / +1。壁炉宗师电子壁炉源头工厂产品，支持电视背景墙、酒店客房、样板间和商业空间的尺寸、火焰效果、结构和OEM/ODM定制。",
    descriptionEn:
      "Model E01, available size 800 mm / 1200 mm / 1500 mm / 1800 mm / +1. Fireplace Master electric fireplace source-factory product with custom size, flame effect, structure, and OEM/ODM options for TV walls, hotel rooms, show flats, and commercial spaces.",
    installation: "嵌入式 / 电视墙",
    priceCny: 5800,
    images: [
      `${ELECTRIC_SERIES}/product/linear-electric-insert.webp`,
      `${ELECTRIC_SERIES}/scene/linear-electric-insert.webp`,
    ],
    coverImage: `${ELECTRIC_SERIES}/product/linear-electric-insert.webp`,
  },
  {
    id: "p7_7",
    category: "p7",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "全景电子壁炉（型号E02）",
    nameEn: "Panoramic Electric Fireplace - E02",
    description: "型号 E02，可选尺寸 1200 mm / 1500 mm / 1800 mm / 2400 mm / +1。超宽全景电子壁炉，适合酒店套房、样板间、会所和大尺寸背景墙，支持火焰颜色和尺寸定制。",
    descriptionEn:
      "Model E02, available size 1200 mm / 1500 mm / 1800 mm / 2400 mm / +1. Extra-wide panoramic electric fireplace for hotel suites, show flats, clubs, and large feature walls with custom size and flame color options.",
    installation: "全景嵌入式",
    priceCny: 9800,
    images: [
      `${ELECTRIC_SERIES}/product/panoramic-media-wall.webp`,
      `${ELECTRIC_SERIES}/scene/panoramic-media-wall.webp`,
    ],
    coverImage: `${ELECTRIC_SERIES}/product/panoramic-media-wall.webp`,
  },
  {
    id: "p7_8",
    category: "p7",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "独立式电子壁炉（型号E03）",
    nameEn: "Freestanding Electric Fireplace Stove - E03",
    description: "型号 E03，可选尺寸 450 mm / 600 mm / 700 mm。免烟道独立式电子壁炉，适合公寓、卧室、书房、民宿和已装修空间。",
    descriptionEn:
      "Model E03, available size 450 mm / 600 mm / 700 mm. Freestanding electric fireplace stove for apartments, bedrooms, studies, boutique stays, and finished interiors without chimney work.",
    installation: "独立式",
    priceCny: 3600,
    images: [
      `${ELECTRIC_SERIES}/product/freestanding-stove.webp`,
      `${ELECTRIC_SERIES}/scene/freestanding-stove.webp`,
    ],
    coverImage: `${ELECTRIC_SERIES}/product/freestanding-stove.webp`,
  },
  {
    id: "p7_9",
    category: "p7",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "电子壁炉机芯（型号E04）",
    nameEn: "Electric Fireplace Core Module - E04",
    description: "型号 E04，可选尺寸 600 mm / 800 mm / 1200 mm / 1800 mm / +1。面向品牌方和工程商的电子壁炉机芯，支持尺寸、外壳、火焰屏、控制板和包装OEM/ODM定制。",
    descriptionEn:
      "Model E04, available size 600 mm / 800 mm / 1200 mm / 1800 mm / +1. OEM electric fireplace core module for brands and contractors, customizable by size, housing, flame screen, control board, and packaging.",
    installation: "OEM机芯",
    priceCny: 2600,
    images: [
      `${ELECTRIC_SERIES}/product/oem-electric-module.webp`,
      `${ELECTRIC_SERIES}/scene/oem-electric-module.webp`,
    ],
    coverImage: `${ELECTRIC_SERIES}/product/oem-electric-module.webp`,
  },
  {
    id: "p7_10",
    category: "p7",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "直条内嵌式电子壁炉（型号E1）",
    nameEn: "Linear Built-In Electric Fireplace Series - E1",
    description: "型号 E1，可选尺寸 500 mm / 600 mm / 700 mm / 800 mm / +12。直条内嵌式电子壁炉，覆盖500-3000mm常规尺寸，适合电视墙、酒店客房、样板间、展厅和工程批量采购，支持加热、音乐、防护门、门框和颜色定制。",
    descriptionEn: "Model E1, available size 500 mm / 600 mm / 700 mm / 800 mm / +12. Linear built-in electric fireplace wholesale series covering 500-3000 mm standard sizes for media walls, hotel rooms, show flats, showrooms, and project procurement. Heating, sound, guard door, frame, color, and OEM/ODM options are available.",
    installation: "嵌入式 / 长条批发",
    priceCny: 468,
    images: [
      "/media/products/electric-series/product/e1-linear-built-in-1.webp",
      "/media/products/electric-series/product/e1-linear-built-in-1-white.webp",
      "/media/products/electric-series/product/e1-linear-built-in-1-dark.webp",
      "/media/products/electric-series/product/e1-linear-built-in-2.webp",
      "/media/products/electric-series/product/e1-linear-built-in-2-white.webp",
      "/media/products/electric-series/product/e1-linear-built-in-2-dark.webp",
    ],
    coverImage: "/media/products/electric-series/product/e1-linear-built-in-1.webp",
  },
  {
    id: "p7_11",
    category: "p7",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "左边L型两面观火内嵌式电子壁炉（型号E2）",
    nameEn: "Left-Corner Two-Sided Electric Fireplace - E2",
    description: "型号 E2，可选尺寸 1000+300 mm。左边L型两面观火电子壁炉，适合转角墙体、电视墙转角和商业空间端景位置，按正面与侧面长度组合报价。",
    descriptionEn: "Model E2, available size 1000+300 mm. Left-corner two-sided electric fireplace for corner media walls, wall returns, and commercial feature corners. Pricing is based on the front and side length combination.",
    installation: "转角 / 双面观火",
    priceCny: 730,
    images: [
      "/media/products/electric-series/product/e2-left-corner-5.webp",
      "/media/products/electric-series/product/e2-left-corner-5-white.webp",
      "/media/products/electric-series/product/e2-left-corner-5-dark.webp",
      "/media/products/electric-series/scene/linear-electric-insert.webp",
      "/media/products/electric-series/scene/panoramic-media-wall.webp",
      "/media/products/electric-series/scene/oem-electric-module.webp",
    ],
    coverImage: "/media/products/electric-series/product/e2-left-corner-5.webp",
  },
  {
    id: "p7_12",
    category: "p7",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "右边L型两面观火电子壁炉（型号E3）",
    nameEn: "Right-Corner Two-Sided Electric Fireplace - E3",
    description: "型号 E3，可选尺寸 300+1000 mm。右边L型两面观火电子壁炉，适合右侧转角安装、展示墙收口和工程定制空间，支持外观尺寸和控制方式定制。",
    descriptionEn: "Model E3, available size 300+1000 mm. Right-corner two-sided electric fireplace for right-hand corner installation, feature-wall returns, and custom project interiors with configurable dimensions and controls.",
    installation: "转角 / 双面观火",
    priceCny: 730,
    images: [
      "/media/products/electric-series/product/e3-right-corner-6.webp",
      "/media/products/electric-series/product/e3-right-corner-6-white.webp",
      "/media/products/electric-series/product/e3-right-corner-6-dark.webp",
      "/media/products/electric-series/scene/linear-electric-insert.webp",
      "/media/products/electric-series/scene/panoramic-media-wall.webp",
      "/media/products/electric-series/scene/oem-electric-module.webp",
    ],
    coverImage: "/media/products/electric-series/product/e3-right-corner-6.webp",
  },
  {
    id: "p7_13",
    category: "p7",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "三面观火电子壁炉（型号E4）",
    nameEn: "Three-Sided Electric Fireplace - E4",
    description: "型号 E4，可选尺寸 300+1000+300 mm。三面观火电子壁炉，适合靠墙非内嵌安装、端景展示、酒店套房和商业空间，形成正面与双侧可视火焰效果。",
    descriptionEn: "Model E4, available size 300+1000+300 mm. Three-sided electric fireplace for wall-side non-recessed installation, feature displays, hotel suites, and commercial spaces with front and two-side flame viewing.",
    installation: "三面观火",
    priceCny: 818,
    images: [
      "/media/products/electric-series/product/e4-three-sided-7.webp",
      "/media/products/electric-series/product/e4-three-sided-7-white.webp",
      "/media/products/electric-series/product/e4-three-sided-7-dark.webp",
      "/media/products/electric-series/scene/linear-electric-insert.webp",
      "/media/products/electric-series/scene/panoramic-media-wall.webp",
      "/media/products/electric-series/scene/oem-electric-module.webp",
    ],
    coverImage: "/media/products/electric-series/product/e4-three-sided-7.webp",
  },
  {
    id: "p7_14",
    category: "p7",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "三面观火B型电子壁炉（型号E5）",
    nameEn: "Three-Sided B Electric Fireplace - E5",
    description: "型号 E5，可选尺寸 1000+300+1000 mm。三面观火B型电子壁炉，适合长边展示和双向空间分隔，按多面长度组合计算批发报价。",
    descriptionEn: "Model E5, available size 1000+300+1000 mm. Three-sided B electric fireplace for long-side display and two-direction spatial division. Wholesale pricing is calculated by multi-side length combination.",
    installation: "三面观火",
    priceCny: 1015,
    images: [
      "/media/products/electric-series/product/e5-three-sided-b-8.webp",
      "/media/products/electric-series/product/e5-three-sided-b-8-white.webp",
      "/media/products/electric-series/product/e5-three-sided-b-8-dark.webp",
      "/media/products/electric-series/scene/linear-electric-insert.webp",
      "/media/products/electric-series/scene/panoramic-media-wall.webp",
      "/media/products/electric-series/scene/oem-electric-module.webp",
    ],
    coverImage: "/media/products/electric-series/product/e5-three-sided-b-8.webp",
  },
  {
    id: "p7_15",
    category: "p7",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "四面观火电子壁炉（型号E6）",
    nameEn: "Four-Sided Electric Fireplace - E6",
    description: "型号 E6，可选尺寸 4S。四面观火电子壁炉，适合岛台、台面和空间中心展示，让客户从四个方向看到电子火焰效果。",
    descriptionEn: "Model E6, available size 4S. Four-sided electric fireplace for island counters, tabletops, and central display positions where flame effects need to be visible from all four sides.",
    installation: "四面观火",
    priceCny: 1115,
    images: [
      "/media/products/electric-series/product/e6-four-sided-8.webp",
      "/media/products/electric-series/product/e6-four-sided-8-white.webp",
      "/media/products/electric-series/product/e6-four-sided-8-dark.webp",
      "/media/products/electric-series/scene/linear-electric-insert.webp",
      "/media/products/electric-series/scene/panoramic-media-wall.webp",
      "/media/products/electric-series/scene/oem-electric-module.webp",
    ],
    coverImage: "/media/products/electric-series/product/e6-four-sided-8.webp",
  },
  {
    id: "p7_16",
    category: "p7",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "圆形电子壁炉（型号E7）",
    nameEn: "Round Electric Fireplace - E7",
    description: "型号 E7，可选尺寸 Ø500 mm / Ø550 mm / Ø600 mm / Ø650 mm / +1。圆形电子壁炉，直径500-700mm可选，适合软装展示、品牌展厅、酒店休闲区和定制装饰结构。",
    descriptionEn: "Model E7, available size Ø500 mm / Ø550 mm / Ø600 mm / Ø650 mm / +1. Round electric fireplace with 500-700 mm diameter options for interior displays, brand showrooms, hotel lounge areas, and custom decorative structures.",
    installation: "圆形 / 定制",
    priceCny: 502,
    images: [
      "/media/products/electric-series/product/e7-round-9.webp",
      "/media/products/electric-series/product/e7-round-9-white.webp",
      "/media/products/electric-series/product/e7-round-9-dark.webp",
      "/media/products/electric-series/scene/linear-electric-insert.webp",
      "/media/products/electric-series/scene/panoramic-media-wall.webp",
      "/media/products/electric-series/scene/oem-electric-module.webp",
    ],
    coverImage: "/media/products/electric-series/product/e7-round-9.webp",
  },
  {
    id: "p7_17",
    category: "p7",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "下半圆形电子壁炉（型号E8）",
    nameEn: "Lower Half-Round Electric Fireplace - E8",
    description: "型号 E8，可选尺寸 500 mm / 550 mm / 600 mm / 650 mm / +1。下半圆形电子壁炉，适合弧形墙面、异形装饰面和工程定制，尺寸覆盖500-700mm。",
    descriptionEn: "Model E8, available size 500 mm / 550 mm / 600 mm / 650 mm / +1. Lower half-round electric fireplace for curved walls, shaped decorative panels, and custom project interiors, available from 500 to 700 mm.",
    installation: "半圆 / 定制",
    priceCny: 496,
    images: [
      "/media/products/electric-series/product/e8-lower-half-round-10.webp",
      "/media/products/electric-series/product/e8-lower-half-round-10-white.webp",
      "/media/products/electric-series/product/e8-lower-half-round-10-dark.webp",
      "/media/products/electric-series/scene/linear-electric-insert.webp",
      "/media/products/electric-series/scene/panoramic-media-wall.webp",
      "/media/products/electric-series/scene/oem-electric-module.webp",
    ],
    coverImage: "/media/products/electric-series/product/e8-lower-half-round-10.webp",
  },
  {
    id: "p7_18",
    category: "p7",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "上半圆形电子壁炉（型号E9）",
    nameEn: "Upper Half-Round Electric Fireplace - E9",
    description: "型号 E9，可选尺寸 500 mm / 550 mm / 600 mm / 650 mm / +1。上半圆形电子壁炉，用于拱形、圆弧和异形背景墙项目，支持尺寸、颜色和功能选配。",
    descriptionEn: "Model E9, available size 500 mm / 550 mm / 600 mm / 650 mm / +1. Upper half-round electric fireplace for arched, curved, and shaped feature-wall projects with configurable size, color, and functions.",
    installation: "半圆 / 定制",
    priceCny: 496,
    images: [
      "/media/products/electric-series/product/e9-upper-half-round-11.webp",
      "/media/products/electric-series/product/e9-upper-half-round-11-white.webp",
      "/media/products/electric-series/product/e9-upper-half-round-11-dark.webp",
      "/media/products/electric-series/scene/linear-electric-insert.webp",
      "/media/products/electric-series/scene/panoramic-media-wall.webp",
      "/media/products/electric-series/scene/oem-electric-module.webp",
    ],
    coverImage: "/media/products/electric-series/product/e9-upper-half-round-11.webp",
  },
  {
    id: "p7_19",
    category: "p7",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "三角形电子壁炉（型号EA）",
    nameEn: "Triangle Electric Fireplace - EA",
    description: "型号 EA，可选尺寸 500 mm / 550 mm / 600 mm / 650 mm / +1。三角形电子壁炉，适合设计感空间、展示装置和特殊墙面造型，按边长500-700mm提供批发规格。",
    descriptionEn: "Model EA, available size 500 mm / 550 mm / 600 mm / 650 mm / +1. Triangle electric fireplace for design-focused interiors, display installations, and special wall structures with 500-700 mm side-length wholesale specifications.",
    installation: "三角形 / 定制",
    priceCny: 506,
    images: [
      "/media/products/electric-series/product/ea-triangle-12.webp",
      "/media/products/electric-series/product/ea-triangle-12-white.webp",
      "/media/products/electric-series/product/ea-triangle-12-dark.webp",
      "/media/products/electric-series/scene/linear-electric-insert.webp",
      "/media/products/electric-series/scene/panoramic-media-wall.webp",
      "/media/products/electric-series/scene/oem-electric-module.webp",
    ],
    coverImage: "/media/products/electric-series/product/ea-triangle-12.webp",
  },
  {
    id: "p7_20",
    category: "p7",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "拱形电子壁炉（型号EB）",
    nameEn: "Arch Electric Fireplace - EB",
    description: "型号 EB，可选尺寸 2DN500 / 2DN550 / 2DN600。拱形电子壁炉，适合欧式、轻奢和商业展示空间，提供2DN500-2DN600常规规格并支持项目定制。",
    descriptionEn: "Model EB, available size 2DN500 / 2DN550 / 2DN600. Arch electric fireplace for European-style, luxury, and commercial display interiors, with 2DN500-2DN600 standard sizes and project customization support.",
    installation: "拱形 / 定制",
    priceCny: 560,
    images: [
      "/media/products/electric-series/product/eb-arch-13.webp",
      "/media/products/electric-series/product/eb-arch-13-white.webp",
      "/media/products/electric-series/product/eb-arch-13-dark.webp",
      "/media/products/electric-series/scene/linear-electric-insert.webp",
      "/media/products/electric-series/scene/panoramic-media-wall.webp",
      "/media/products/electric-series/scene/oem-electric-module.webp",
    ],
    coverImage: "/media/products/electric-series/product/eb-arch-13.webp",
  },
  {
    id: "p7_21",
    category: "p7",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "壁挂嵌入式RGB电子壁炉（型号EC）",
    nameEn: "Wall-Mounted Insert RGB Electric Fireplace - EC",
    description:
      "型号 EC，可选尺寸 72 inch / 80 inch。72/80英寸壁挂嵌入式RGB电子壁炉，支持750W/1500W双档加热、13色LED火焰、遥控和APP控制，适合酒店、公寓、电视墙和工程批发项目。",
    descriptionEn:
      "Model EC, available size 72 inch / 80 inch. 72/80 inch wall-mounted insert RGB electric fireplace for hotel, apartment, media-wall, and project wholesale orders, with 750W/1500W heating, 13-color LED flame, remote control, app control, and OEM/ODM options.",
    installation: "壁挂式 / 嵌入式",
    priceCny: 1100,
    images: [
      "/media/products/alibaba-electric-series/ec-wall-insert/ec-wall-insert-02.webp",
      "/media/products/alibaba-electric-series/ec-wall-insert/ec-wall-insert-01.webp",
      "/media/products/alibaba-electric-series/ec-wall-insert/ec-wall-insert-03.webp",
      "/media/products/alibaba-electric-series/ec-wall-insert/ec-wall-insert-04.webp",
      "/media/products/alibaba-electric-series/ec-wall-insert/ec-wall-insert-05.webp",
      "/media/products/alibaba-electric-series/ec-wall-insert/ec-wall-insert-06.webp",
    ],
    coverImage: "/media/products/alibaba-electric-series/ec-wall-insert/ec-wall-insert-02.webp",
  },
  // === 户外火景 ===
  {
    id: "p88_51",
    category: "p88",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "户外火景",
    nameEn: "Outdoor Fire Feature -",
    description: "。壁炉宗师户外火景，打造户外庭院温暖氛围，可定制各种造型。",
    descriptionEn: ". Outdoor fire features for garden and patio, customizable designs.",
    installation: "独立/嵌入",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E6%88%B7%E5%A4%96%E7%81%AB%E6%99%AF/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E6%88%B7%E5%A4%96%E7%81%AB%E6%99%AF/1.png`,
  },
  // === 工具附件 ===
  {
    id: "p8_52",
    category: "p8",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "壁炉工具套装",
    nameEn: "Fireplace Tool Set -",
    description: "。丹麦Rais壁炉工具套装，高品质壁炉配件。",
    descriptionEn: ". Danish Rais fireplace tool set, high-quality accessories.",
    installation: "附件",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E5%B7%A5%E5%85%B7%E9%99%84%E4%BB%B6/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E5%B7%A5%E5%85%B7%E9%99%84%E4%BB%B6/1.png`,
  },

  // === 艺术壁炉报价新增系列 ===
  {
    id: "p1_72",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "飞碟悬挂式燃木壁炉（型号W1）",
    nameEn: "Saucer Suspended Wood-Burning Fireplace - W1",
    description: "型号 W1，可选尺寸 Ø600 mm / Ø700 mm / Ø800 mm / Ø900 mm / +2。飞碟悬挂式燃木壁炉，适合别墅、民宿、会所和商业休闲空间的真火取暖项目。标准配置 2 米烟囱，不含法兰，可按工程需求确认颜色、吊装高度、烟囱段和出口包装。",
    descriptionEn: "Model W1, available size Ø600 mm / Ø700 mm / Ø800 mm / Ø900 mm / +2. Saucer suspended wood-burning fireplace for villas, lodges, clubs, and commercial lounge projects. Standard supply includes a 2 m chimney without flange; color, hanging height, chimney sections, and export packing can be confirmed by project.",
    installation: "悬挂式 / 烟囱款",
    priceCny: 4220,
    images: ["/media/products/art-fireplace-series/original/saucer-suspended-wood.webp"],
    coverImage: "/media/products/art-fireplace-series/original/saucer-suspended-wood.webp",
  },
  {
    id: "p3_27",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "飞碟悬挂式酒精壁炉（型号A14）",
    nameEn: "Saucer Suspended Ethanol Fireplace - A14",
    description: "型号 A14，可选尺寸 Ø600 mm / Ø700 mm / Ø800 mm / Ø900 mm / +2。飞碟悬挂式酒精壁炉，适合海外别墅、酒店休息区、会所和样板间项目。采用生物乙醇真火方案，标准配置 2 米烟囱，不含法兰，支持外观颜色、包装和项目尺寸确认。",
    descriptionEn: "Model A14, available size Ø600 mm / Ø700 mm / Ø800 mm / Ø900 mm / +2. Saucer suspended ethanol fireplace for villas, hotel lounges, clubs, and show-flat projects. It uses a real-flame bioethanol solution, includes a 2 m chimney without flange, and supports color, packing, and project-size confirmation.",
    installation: "悬挂式 / 烟囱款",
    priceCny: 4480,
    images: ["/media/products/art-fireplace-series/original/saucer-suspended-ethanol.webp"],
    coverImage: "/media/products/art-fireplace-series/original/saucer-suspended-ethanol.webp",
  },
  {
    id: "p4_76",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "飞碟悬挂式3D雾化壁炉（型号M17）",
    nameEn: "Saucer Suspended 3D Mist Fireplace - M17",
    description: "型号 M17，可选尺寸 Ø800 mm / Ø900 mm / Ø1000 mm / Ø1200 mm。飞碟悬挂式3D雾化壁炉，适合室内商业空间、酒店大堂、会所和别墅项目。无明火，强调水雾火焰视觉效果，标准配置 2 米烟囱，不含法兰，可做项目化外观和包装确认。",
    descriptionEn: "Model M17, available size Ø800 mm / Ø900 mm / Ø1000 mm / Ø1200 mm. Saucer suspended 3D mist fireplace for indoor commercial spaces, hotel lobbies, clubs, and villa projects. It creates a water-vapor flame effect without open flame, includes a 2 m chimney without flange, and supports project-based appearance and packing confirmation.",
    installation: "悬挂式 / 烟囱款",
    priceCny: 6770,
    images: ["/media/products/art-fireplace-series/original/saucer-suspended-mist.webp"],
    coverImage: "/media/products/art-fireplace-series/original/saucer-suspended-mist.webp",
  },
  {
    id: "p3_28",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "装饰落地式酒精壁炉（型号A15）",
    nameEn: "Decorative Freestanding Ethanol Fireplace - A15",
    description: "型号 A15，可选尺寸 Ø600 mm / Ø650 mm / Ø700 mm / Ø750 mm / +5。装饰落地式酒精壁炉，适合别墅客厅、酒店休息区、会所和展示空间。标准配置 1 米烟囱，不含法兰，适合做项目批发、样板间陈列和品牌定制。",
    descriptionEn: "Model A15, available size Ø600 mm / Ø650 mm / Ø700 mm / Ø750 mm / +5. Decorative freestanding ethanol fireplace for villa living rooms, hotel lounges, clubs, and display spaces. Standard supply includes a 1 m chimney without flange, suitable for project wholesale, show-flat display, and private-label customization.",
    installation: "装饰 / 落地款",
    priceCny: 3020,
    images: ["/media/products/art-fireplace-series/original/decorative-freestanding-ethanol.webp"],
    coverImage: "/media/products/art-fireplace-series/original/decorative-freestanding-ethanol.webp",
  },
  {
    id: "p4_77",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "装饰落地式3D雾化壁炉（型号M18）",
    nameEn: "Decorative Freestanding 3D Mist Fireplace - M18",
    description: "型号 M18，可选尺寸 Ø600 mm / Ø650 mm / Ø700 mm / Ø750 mm / +5。装饰落地式3D雾化壁炉，适合酒店、会所、商业展示和住宅项目。水雾火焰视觉柔和，无明火，标准配置 2 米烟囱，不含法兰，支持外观颜色和项目包装定制。",
    descriptionEn: "Model M18, available size Ø600 mm / Ø650 mm / Ø700 mm / Ø750 mm / +5. Decorative freestanding 3D mist fireplace for hotels, clubs, commercial displays, and residential projects. It provides a soft water-vapor flame effect without open flame, includes a 2 m chimney without flange, and supports color and project packing customization.",
    installation: "装饰 / 落地款",
    priceCny: 3310,
    images: ["/media/products/art-fireplace-series/original/decorative-freestanding-mist.webp"],
    coverImage: "/media/products/art-fireplace-series/original/decorative-freestanding-mist.webp",
  },
  {
    id: "p3_29",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "球形装饰酒精壁炉（型号A16）",
    nameEn: "Spherical Decorative Ethanol Fireplace - A16",
    description: "型号 A16，可选尺寸 Ø450 mm / Ø500 mm / Ø550 mm / Ø600 mm / +3。球形装饰酒精壁炉，适合别墅、酒店、会所、餐厅和展厅空间。球形外观适合做软装陈列和商业装饰项目，支持尺寸、颜色、包装和品牌资料确认。",
    descriptionEn: "Model A16, available size Ø450 mm / Ø500 mm / Ø550 mm / Ø600 mm / +3. Spherical decorative ethanol fireplace for villas, hotels, clubs, restaurants, and showrooms. The round sculptural form is suitable for interior styling and commercial decoration projects, with size, color, packing, and private-label details confirmed by order.",
    installation: "球形 / 装饰款",
    priceCny: 1910,
    images: ["/media/products/art-fireplace-series/original/spherical-decorative-ethanol.webp"],
    coverImage: "/media/products/art-fireplace-series/original/spherical-decorative-ethanol.webp",
  },
  // === 全息壁炉 ===
  {
    id: "p9_1",
    category: "p9",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "全息壁炉显示模块（型号H01）",
    nameEn: "Holographic Fireplace Display Module - H01",
    description: "型号 H01，可选尺寸 800 mm / 1200 mm / 1800 mm / 2400 mm。壁炉宗师全息壁炉源头工厂产品，适合展厅、酒店大堂、商业橱窗、会所和沉浸式空间，可定制全息火焰影像、尺寸比例、安装结构和控制系统。",
    descriptionEn:
      "Model H01, available size 800 mm / 1200 mm / 1800 mm / 2400 mm. Fireplace Master holographic fireplace source-factory product for showrooms, hotel lobbies, retail windows, clubs, and immersive spaces, with custom flame visuals, size ratio, installation structure, and control system.",
    installation: "全息显示",
    priceCny: 16800,
    images: [
      `${HOLOGRAPHIC_SERIES}/product/holographic-display-module.webp`,
      `${HOLOGRAPHIC_SERIES}/scene/holographic-display-module.webp`,
    ],
    coverImage: `${HOLOGRAPHIC_SERIES}/product/holographic-display-module.webp`,
  },
  {
    id: "p9_2",
    category: "p9",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "投影壁炉系统（型号H02）",
    nameEn: "Projection Fireplace System - H02",
    description: "型号 H02，可选尺寸 Project S / Project M / Project L。投影壁炉适合影音室、展厅、商业橱窗和沉浸式空间，可做大画面火焰、无热源视觉氛围和主题内容定制。",
    descriptionEn:
      "Model H02, available size Project S / Project M / Project L. Projection fireplace system for cinema rooms, showrooms, retail windows, and immersive spaces with large-scale flame visuals and custom content.",
    installation: "投影系统",
    priceCny: 22800,
    images: [
      `${HOLOGRAPHIC_SERIES}/product/projection-fireplace-system.webp`,
      `${HOLOGRAPHIC_SERIES}/scene/projection-fireplace-system.webp`,
    ],
    coverImage: `${HOLOGRAPHIC_SERIES}/product/projection-fireplace-system.webp`,
  },
  {
    id: "p9_3",
    category: "p9",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "沉浸式火焰影像墙（型号H03）",
    nameEn: "Immersive Flame Wall Kit - H03",
    description: "型号 H03，可选尺寸 2 m / 5 m / 10 m。模块化火焰影像墙，适合品牌展厅、酒店大堂、舞台背景和商业空间，支持画面比例、控制系统和内容定制。",
    descriptionEn:
      "Model H03, available size 2 m / 5 m / 10 m. Modular immersive flame wall kit for brand showrooms, hotel lobbies, stage backdrops, and commercial spaces with custom ratio, control system, and content.",
    installation: "影像墙",
    priceCny: 36800,
    images: [
      `${HOLOGRAPHIC_SERIES}/product/immersive-flame-wall.webp`,
      `${HOLOGRAPHIC_SERIES}/scene/immersive-flame-wall.webp`,
    ],
    coverImage: `${HOLOGRAPHIC_SERIES}/product/immersive-flame-wall.webp`,
  },
];

export const products: Product[] = [...productCatalog, ...alibabaProducts].filter((product) =>
  activeCategoryIds.has(product.category) &&
  (product.category !== "p1" || activeLegacyWoodProductIds.has(product.id)),
);

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.category === categoryId);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getCategoryName(categoryId: string): string {
  return categories.find((c) => c.id === categoryId)?.name || categoryId;
}

export function getCategory(categoryId: string) {
  return categories.find((c) => c.id === categoryId);
}
