export interface Product {
  id: string;
  category: string;
  brand: string;
  brandCountry: string;
  name: string;
  nameEn: string;
  description: string;
  descriptionEn: string;
  installation: string;
  priceCny?: number;
  images: string[];
  coverImage: string;
}

export const categories = [
  { id: "p3", name: "酒精壁炉", nameEn: "Ethanol Fireplace", icon: "🔥" },
  { id: "p4", name: "雾化壁炉", nameEn: "Mist Fireplace", icon: "💨" },
  { id: "p7", name: "电子壁炉", nameEn: "Electric Fireplace", icon: "⚡" },
  { id: "p9", name: "全息壁炉", nameEn: "Holographic Fireplace", icon: "✨" },
];

const activeCategoryIds = new Set(categories.map((category) => category.id));

export const brands = [
  { name: "壁炉宗师", country: "中国", nameEn: "Fireplace Master", countryEn: "China" },
];

const OSS = "/media/oss";
const ETHANOL_SERIES = "/media/products/ethanol-series";

const productCatalog: Product[] = [
  // === LACUNZA (燃木) ===
  {
    id: "p1_71",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza Altea 带烤箱独立式燃木壁炉",
    nameEn: "Lacunza Altea Freestanding Wood Stove with Oven",
    description: "西班牙Lacunza Altea带烤箱独立式燃木壁炉，集烹饪与取暖于一体，经典设计。",
    descriptionEn:
      "Spanish Lacunza Altea freestanding wood-burning fireplace with oven, combining cooking and heating in one classic design.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/ALtea/1.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/ALtea/1.jpg`,
  },
  {
    id: "p1_1",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza Stelar 93 独立式真火燃木壁炉",
    nameEn: "Lacunza Stelar 93 Freestanding Wood Fireplace",
    description: "西班牙Lacunza Stelar 93独立式真火燃木壁炉，造型优雅，热效卓越。",
    descriptionEn:
      "Spanish Lacunza Stelar 93 freestanding wood fireplace, elegant design with卓越 heating efficiency.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/stelar%2093/%E5%86%85%E5%AE%B9%E9%A1%B51.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/stelar%2093/%E5%86%85%E5%AE%B9%E9%A1%B51.png`,
  },
  {
    id: "p1_45",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza Sara 嵌入式燃木真火壁炉",
    nameEn: "Lacunza Sara Built-in Wood Fireplace",
    description: "西班牙Lacunza Sara嵌入式燃木真火壁炉，简约嵌入设计，节省空间。",
    descriptionEn: "Spanish Lacunza Sara built-in wood fireplace, space-saving minimalist design.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Sara/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Sara/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`,
  },
  {
    id: "p1_44",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza Oslo 可做饭独立式燃木真火壁炉",
    nameEn: "Lacunza Oslo Freestanding Wood Stove",
    description: "西班牙Lacunza Oslo可做饭独立式燃木真火壁炉，兼具烹饪功能。",
    descriptionEn: "Spanish Lacunza Oslo freestanding wood stove with cooking functionality.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Oslo/%E5%86%85%E5%AE%B9%E9%A1%B51.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Oslo/%E5%86%85%E5%AE%B9%E9%A1%B51.png`,
  },
  {
    id: "p1_43",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza Nickel 嵌入式双面观火燃木真火壁炉",
    nameEn: "Lacunza Nickel Double-Sided Built-in Wood Fireplace",
    description: "西班牙Lacunza Nickel嵌入式双面观火燃木真火壁炉，双面玻璃设计，可观双面火焰。",
    descriptionEn:
      "Spanish Lacunza Nickel double-sided built-in wood fireplace, dual glass panels for viewing fire from both sides.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Nickel%20/%E5%86%85%E5%AE%B9%E9%A1%B51.gif`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Nickel%20/%E5%86%85%E5%AE%B9%E9%A1%B51.gif`,
  },
  {
    id: "p1_42",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza K2 800 嵌入式燃木真火壁炉",
    nameEn: "Lacunza K2 800 Built-in Wood Fireplace",
    description: "西班牙Lacunza K2 800嵌入式燃木真火壁炉，大观火面设计，温暖整个空间。",
    descriptionEn: "Spanish Lacunza K2 800 built-in wood fireplace with large viewing window.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/K2%20800/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/K2%20800/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`,
  },
  {
    id: "p1_41",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza Itaca 嵌入式单面真火燃木壁炉",
    nameEn: "Lacunza Itaca Built-in Wood Fireplace",
    description: "西班牙Lacunza Itaca嵌入式单面真火燃木壁炉，经典单面观火，高效取暖。",
    descriptionEn:
      "Spanish Lacunza Itaca single-sided built-in wood fireplace, classic design with efficient heating.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Itaca/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Itaca/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`,
  },
  {
    id: "p1_39",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza CM 300R 角落独立式燃木真火壁炉",
    nameEn: "Lacunza CM 300R Corner Freestanding Wood Fireplace",
    description: "西班牙Lacunza CM 300R角落独立式燃木真火壁炉，专为角落空间设计。",
    descriptionEn:
      "Spanish Lacunza CM 300R corner freestanding wood fireplace, designed for corner installation.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/CM%20300R/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/CM%20300R/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`,
  },
  {
    id: "p1_38",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza Clasica 7T 带烤箱可做饭燃木真火壁炉",
    nameEn: "Lacunza Clasica 7T Wood Stove with Oven",
    description: "西班牙Lacunza Clasica 7T带烤箱可做饭燃木真火壁炉，欧式乡村风格。",
    descriptionEn:
      "Spanish Lacunza Clasica 7T wood stove with oven, European country style design.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Clasica/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Clasica/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`,
  },
  {
    id: "p1_37",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza Atlantic 603 独立式燃木真火壁炉",
    nameEn: "Lacunza Atlantic 603 Freestanding Wood Fireplace",
    description: "西班牙Lacunza Atlantic 603独立式燃木真火壁炉，大气外观，供暖强劲。",
    descriptionEn:
      "Spanish Lacunza Atlantic 603 freestanding wood fireplace, grand appearance with powerful heating.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Atlantic%20603%20/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Atlantic%20603%20/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`,
  },
  {
    id: "p1_36",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "西班牙",
    name: "Lacunza Adour 700ST 嵌入式燃木真火壁炉",
    nameEn: "Lacunza Adour 700ST Built-in Wood Fireplace",
    description: "西班牙Lacunza Adour 700ST嵌入式燃木真火壁炉，简约线条，现代设计。",
    descriptionEn:
      "Spanish Lacunza Adour 700ST built-in wood fireplace, clean lines, modern design.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Adour%20700ST/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%A5%BF%E7%8F%AD%E7%89%99Lacunza%20/Adour%20700ST/%E5%86%85%E5%AE%B9%E9%A1%B51.jpg`,
  },
  // === RAIS (燃木) ===
  {
    id: "p1_61",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Q TEE 2C 独立式燃木真火壁炉",
    nameEn: "Rais Q TEE 2C Freestanding Wood Fireplace",
    description: "丹麦Rais Q TEE 2C独立式燃木真火壁炉，北欧简约设计，高效燃烧技术。",
    descriptionEn:
      "Danish Rais Q TEE 2C freestanding wood fireplace, Nordic minimalist design,高效燃烧技术.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Q%20TEE%202C/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Q%20TEE%202C/1.png`,
  },
  {
    id: "p1_60",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Nexo 系列独立式燃木真火壁炉",
    nameEn: "Rais Nexo Series Freestanding Wood Fireplace",
    description: "丹麦Rais Nexo系列独立式燃木真火壁炉，现代极简风格。",
    descriptionEn:
      "Danish Rais Nexo series freestanding wood fireplace, modern minimalist style.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Nexo%20120/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Nexo%20120/1.png`,
  },
  {
    id: "p1_59",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Juno L 独立式燃木真火壁炉",
    nameEn: "Rais Juno L Freestanding Wood Fireplace",
    description: "丹麦Rais Juno L独立式燃木真火壁炉，圆形观火窗，独特设计。",
    descriptionEn: "Danish Rais Juno L freestanding wood fireplace with circular viewing window.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Juno%20L/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Juno%20L/1.png`,
  },
  {
    id: "p1_58",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Caro 90 独立式燃木真火壁炉",
    nameEn: "Rais Caro 90 Freestanding Wood Fireplace",
    description: "丹麦Rais Caro 90独立式燃木真火壁炉，优雅圆柱造型。",
    descriptionEn: "Danish Rais Caro 90 freestanding wood fireplace, elegant cylindrical design.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Caro%2090/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Caro%2090/1.png`,
  },
  {
    id: "p1_28",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Viva L 系列独立式燃木真火壁炉",
    nameEn: "Rais Viva L Series Freestanding Wood Fireplace",
    description: "丹麦Rais Viva L系列独立式燃木真火壁炉，灵动火焰视觉效果。",
    descriptionEn:
      "Danish Rais Viva L series freestanding wood fireplace, dynamic flame视觉效果.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Viva%20L/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Viva%20L/1.png`,
  },
  {
    id: "p1_27",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Visio 3 三面观火嵌入式燃木真火壁炉",
    nameEn: "Rais Visio 3 Three-Sided Built-in Wood Fireplace",
    description: "丹麦Rais Visio 3 三面观火嵌入式燃木真火壁炉，270°火焰视野。",
    descriptionEn:
      "Danish Rais Visio 3 three-sided built-in wood fireplace, 270° flame view.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Visio/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Visio/1.png`,
  },
  {
    id: "p1_26",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Q-TEE 2 独立式燃木真火壁炉",
    nameEn: "Rais Q-TEE 2 Freestanding Wood Fireplace",
    description: "丹麦Rais Q-TEE 2独立式燃木真火壁炉，几何造型艺术感十足。",
    descriptionEn: "Danish Rais Q-TEE 2 freestanding wood fireplace, geometric artistic design.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Q-TEE%202/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Q-TEE%202/1.png`,
  },
  {
    id: "p1_25",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Q-BE 独立式转角观火燃木真火壁炉",
    nameEn: "Rais Q-BE Corner View Freestanding Wood Fireplace",
    description: "丹麦Rais Q-BE独立式转角观火燃木真火壁炉，转角设计新颖独特。",
    descriptionEn: "Danish Rais Q-BE corner-view freestanding wood fireplace, innovative angle design.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Q-BE/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Q-BE/1.png`,
  },
  {
    id: "p1_24",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Pilar 独立式燃木真火壁炉",
    nameEn: "Rais Pilar Freestanding Wood Fireplace",
    description: "丹麦Rais Pilar独立式燃木真火壁炉，柱形设计，简约大气。",
    descriptionEn: "Danish Rais Pilar freestanding wood fireplace, pillar design,简约大气.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Pilar/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/Pilar/1.png`,
  },
  {
    id: "p1_23",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "Rais Bionic Fire 双室燃烧独立式燃木真火壁炉",
    nameEn: "Rais Bionic Fire Dual-Chamber Wood Fireplace",
    description: "丹麦Rais Bionic Fire双室燃烧独立式燃木真火壁炉，创新双室燃烧技术。",
    descriptionEn:
      "Danish Rais Bionic Fire dual-chamber combustion freestanding wood fireplace, innovative technology.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/bionic%20fire/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E4%B8%B9%E9%BA%A6RAIS/bionic%20fire/1.png`,
  },
  // === HAAS+SOHN (燃木) ===
  {
    id: "p1_22",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "奥地利",
    name: "Haas+sohn Treviso 独立式皂石燃木真火壁炉",
    nameEn: "Haas+sohn Treviso Soapstone Wood Fireplace",
    description: "奥地利Haas+sohn Treviso独立式皂石燃木真火壁炉，皂石蓄热，持久温暖。",
    descriptionEn:
      "Austrian Haas+sohn Treviso freestanding soapstone wood fireplace, soapstone heat storage for lasting warmth.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E5%A5%A5%E5%9C%B0%E5%88%A9Haas%2Bsohn/Treviso/1.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E5%A5%A5%E5%9C%B0%E5%88%A9Haas%2Bsohn/Treviso/1.jpg`,
  },
  {
    id: "p1_21",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "奥地利",
    name: "Haas+sohn Kuopio-II 独立式皂石燃木真火壁炉",
    nameEn: "Haas+sohn Kuopio-II Soapstone Wood Fireplace",
    description: "奥地利Haas+sohn Kuopio-II独立式皂石燃木真火壁炉，经典北欧皂石工艺。",
    descriptionEn:
      "Austrian Haas+sohn Kuopio-II freestanding soapstone wood fireplace, classic Nordic soapstone craftsmanship.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E5%A5%A5%E5%9C%B0%E5%88%A9Haas%2Bsohn/Kuopi0-II/1.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E5%A5%A5%E5%9C%B0%E5%88%A9Haas%2Bsohn/Kuopi0-II/1.jpg`,
  },
  {
    id: "p1_20",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "奥地利",
    name: "Haas+sohn Ficus-II-RLU 独立式燃木真火壁炉",
    nameEn: "Haas+sohn Ficus-II-RLU Freestanding Wood Fireplace",
    description: "奥地利Haas+sohn Ficus-II-RLU独立式燃木真火壁炉，优雅曲线设计。",
    descriptionEn:
      "Austrian Haas+sohn Ficus-II-RLU freestanding wood fireplace, elegant curved design.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E5%A5%A5%E5%9C%B0%E5%88%A9Haas%2Bsohn/Ficus-II-rlu/1.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E5%A5%A5%E5%9C%B0%E5%88%A9Haas%2Bsohn/Ficus-II-rlu/1.jpg`,
  },
  {
    id: "p1_2",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "奥地利",
    name: "Haas+sohn Aruba easy 独立式皂石燃木壁炉",
    nameEn: "Haas+sohn Aruba Easy Soapstone Wood Stove",
    description: "奥地利Haas+sohn Aruba easy独立式皂石燃木壁炉，操作简便，高效蓄热。",
    descriptionEn:
      "Austrian Haas+sohn Aruba easy freestanding soapstone wood stove, easy operation, efficient heat storage.",
    installation: "独立式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E5%A5%A5%E5%9C%B0%E5%88%A9Haas%2Bsohn/Aruba/1.jpg`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E5%A5%A5%E5%9C%B0%E5%88%A9Haas%2Bsohn/Aruba/1.jpg`,
  },
  // === RUEGG (燃木) ===
  {
    id: "p1_35",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "瑞士",
    name: "Ruegg Tillia 嵌入式三面观火燃木真火壁炉",
    nameEn: "Ruegg Tillia Three-Sided Built-in Wood Fireplace",
    description: "瑞士Ruegg Tillia嵌入式三面观火燃木真火壁炉，瑞士精工品质。",
    descriptionEn:
      "Swiss Ruegg Tillia three-sided built-in wood fireplace, Swiss precision craftsmanship.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E7%91%9E%E5%A3%ABRuegg/Tilia/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E7%91%9E%E5%A3%ABRuegg/Tilia/1.png`,
  },
  {
    id: "p1_34",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "瑞士",
    name: "Ruegg Rondeo 嵌入式弧面观火燃木真火壁炉",
    nameEn: "Ruegg Rondeo Curved Glass Built-in Wood Fireplace",
    description: "瑞士Ruegg Rondeo嵌入式弧面观火燃木真火壁炉，独特弧面玻璃设计。",
    descriptionEn:
      "Swiss Ruegg Rondeo built-in wood fireplace with curved glass, unique弧形设计.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E7%91%9E%E5%A3%ABRuegg/Rondeo/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E7%91%9E%E5%A3%ABRuegg/Rondeo/1.png`,
  },
  {
    id: "p1_33",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "瑞士",
    name: "Ruegg RII 嵌入式转角观火燃木真火壁炉",
    nameEn: "Ruegg RII Corner Built-in Wood Fireplace",
    description: "瑞士Ruegg RII嵌入式转角观火燃木真火壁炉，转角设计节省空间。",
    descriptionEn: "Swiss Ruegg RII corner built-in wood fireplace, space-saving corner design.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E7%91%9E%E5%A3%ABRuegg/RII/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E7%91%9E%E5%A3%ABRuegg/RII/1.png`,
  },
  {
    id: "p1_18",
    category: "p1",
    brand: "壁炉宗师",
    brandCountry: "瑞士",
    name: "Ruegg Odeon 270°弧面观火悬挂燃木壁炉",
    nameEn: "Ruegg Odeon 270° Curved Suspended Wood Fireplace",
    description: "瑞士Ruegg Odeon 270°弧面观火悬挂燃木壁炉，艺术悬挂设计，270°全景视野。",
    descriptionEn:
      "Swiss Ruegg Odeon 270° curved suspended wood fireplace, artistic悬挂设计 with panoramic view.",
    installation: "悬挂式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E7%91%9E%E5%A3%ABRuegg/Odeon/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E7%91%9E%E5%A3%ABRuegg/Odeon/1.png`,
  },
  // === ELEMENT 4 (燃气) ===
  {
    id: "p2_56",
    category: "p2",
    brand: "壁炉宗师",
    brandCountry: "荷兰",
    name: "Element4 Lucius 140 嵌入式燃气壁炉",
    nameEn: "Element4 Lucius 140 Built-in Gas Fireplace",
    description: "荷兰Element4 Lucius 140嵌入式燃气壁炉，宽大观火面，现代燃气技术。",
    descriptionEn:
      "Dutch Element4 Lucius 140 built-in gas fireplace, large viewing area, modern gas technology.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Lucius%20140/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Lucius%20140/1.png`,
  },
  {
    id: "p2_55",
    category: "p2",
    brand: "壁炉宗师",
    brandCountry: "荷兰",
    name: "Element4 Tenore 140 嵌入式燃气壁炉",
    nameEn: "Element4 Tenore 140 Built-in Gas Fireplace",
    description: "荷兰Element4 Tenore 140嵌入式燃气壁炉，线性简约设计。",
    descriptionEn: "Dutch Element4 Tenore 140 built-in gas fireplace, linear minimalist design.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Tenore%20140/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Tenore%20140/1.png`,
  },
  {
    id: "p2_54",
    category: "p2",
    brand: "壁炉宗师",
    brandCountry: "荷兰",
    name: "Element4 Summum 100F 嵌入式燃气壁炉",
    nameEn: "Element4 Summum 100F Built-in Gas Fireplace",
    description: "荷兰Element4 Summum 100F嵌入式燃气壁炉，顶级燃气壁炉体验。",
    descriptionEn:
      "Dutch Element4 Summum 100F built-in gas fireplace, premium gas fireplace experience.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Summum%20100%20F/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Summum%20100%20F/1.png`,
  },
  {
    id: "p2_53",
    category: "p2",
    brand: "壁炉宗师",
    brandCountry: "荷兰",
    name: "Element4 Sky 室内系列嵌入式燃气壁炉",
    nameEn: "Element4 Sky Indoor Series Gas Fireplace",
    description: "荷兰Element4 Sky室内系列嵌入式燃气壁炉，室内外无缝融合设计。",
    descriptionEn:
      "Dutch Element4 Sky indoor series gas fireplace, seamless indoor-outdoor design.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Sky%20%E5%AE%A4%E5%86%85%E7%B3%BB%E5%88%97/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Sky%20%E5%AE%A4%E5%86%85%E7%B3%BB%E5%88%97/1.png`,
  },
  {
    id: "p2_31",
    category: "p2",
    brand: "壁炉宗师",
    brandCountry: "荷兰",
    name: "Element4 Trisore 140 嵌入式三面观火燃气壁炉",
    nameEn: "Element4 Trisore 140 Three-Sided Gas Fireplace",
    description: "荷兰Element4 Trisore 140嵌入式三面观火燃气壁炉，三面玻璃全景火焰。",
    descriptionEn:
      "Dutch Element4 Trisore 140 three-sided gas fireplace, panoramic flame view.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Trisore%20140/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Trisore%20140/1.png`,
  },
  {
    id: "p2_29",
    category: "p2",
    brand: "壁炉宗师",
    brandCountry: "荷兰",
    name: "Element4 Bidore 100 嵌入式转角观火燃气壁炉",
    nameEn: "Element4 Bidore 100 Corner Gas Fireplace",
    description: "荷兰Element4 Bidore 100嵌入式转角观火燃气壁炉，转角双面观火。",
    descriptionEn:
      "Dutch Element4 Bidore 100 corner gas fireplace, dual-sided corner view.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Bidore%20100/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E8%8D%B7%E5%85%B0Elemnet4%20/Bidore%20100/1.png`,
  },
  // === 酒精壁炉 ===
  {
    id: "p3_14",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "酒精壁炉（可定制）",
    nameEn: "Ethanol Fireplace (Customizable)",
    description: "壁炉宗师酒精壁炉源头工厂产品，支持火槽、尺寸、外观和安装结构定制，适合酒店、会所、别墅和商业空间的真火氛围方案。",
    descriptionEn:
      "Fireplace Master bio ethanol fireplace source-factory product, customizable burner, size, finish, and installation structure for hotels, clubs, villas, and commercial spaces.",
    installation: "嵌入式",
    priceCny: 5800,
    images: [
      `${ETHANOL_SERIES}/product/linear-burner.webp`,
      `${ETHANOL_SERIES}/scene/linear-burner.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/linear-burner.webp`,
  },
  {
    id: "p3_15",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "自动酒精燃烧器",
    nameEn: "Automatic Bio Ethanol Burner",
    description: "带自动点火和模块化结构的生物乙醇燃烧器，适合酒店、会所、别墅壁龛和批量工程定制。",
    descriptionEn:
      "Automatic bio ethanol burner with modular structure for hotels, clubs, villa niches, and project customization.",
    installation: "嵌入式 / 自动控制",
    priceCny: 12800,
    images: [
      `${ETHANOL_SERIES}/product/automatic-burner.webp`,
      `${ETHANOL_SERIES}/scene/automatic-burner.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/automatic-burner.webp`,
  },
  {
    id: "p3_16",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "双面隔断酒精壁炉",
    nameEn: "Double-Sided Ethanol Fireplace Divider",
    description: "双面观火结构，可作为餐厅、会所、客厅与商业空间的低矮隔断和真火视觉焦点。",
    descriptionEn:
      "Double-sided ethanol fireplace divider for restaurants, clubs, living rooms, and commercial interiors.",
    installation: "双面 / 隔断式",
    priceCny: 16800,
    images: [
      `${ETHANOL_SERIES}/product/double-sided-divider.webp`,
      `${ETHANOL_SERIES}/scene/double-sided-divider.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/double-sided-divider.webp`,
  },
  {
    id: "p3_17",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "三面观火酒精壁炉",
    nameEn: "Three-Sided Ethanol Fireplace",
    description: "三面可视真火结构，适合半岛式背景墙、端景墙和高端住宅会客空间。",
    descriptionEn:
      "Three-sided real-flame ethanol fireplace for peninsula feature walls and premium residential lounges.",
    installation: "三面观火",
    priceCny: 19800,
    images: [
      `${ETHANOL_SERIES}/product/three-sided-peninsula.webp`,
      `${ETHANOL_SERIES}/scene/three-sided-peninsula.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/three-sided-peninsula.webp`,
  },
  {
    id: "p3_18",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "桌面酒精壁炉",
    nameEn: "Tabletop Ethanol Fireplace",
    description: "小型桌面生物乙醇壁炉，适合样板间、民宿、公寓、餐桌和轻量级软装氛围。",
    descriptionEn:
      "Compact tabletop ethanol fireplace for model rooms, apartments, dining tables, and decorative atmosphere.",
    installation: "桌面式",
    priceCny: 2800,
    images: [
      `${ETHANOL_SERIES}/product/tabletop.webp`,
      `${ETHANOL_SERIES}/scene/tabletop.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/tabletop.webp`,
  },
  {
    id: "p3_19",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "独立式酒精壁炉",
    nameEn: "Freestanding Ethanol Fireplace",
    description: "可移动独立式酒精壁炉，适合客厅、休闲区、会所和不方便开孔的空间。",
    descriptionEn:
      "Freestanding ethanol fireplace for lounges, clubs, living rooms, and spaces where built-in work is difficult.",
    installation: "独立式",
    priceCny: 6800,
    images: [
      `${ETHANOL_SERIES}/product/freestanding.webp`,
      `${ETHANOL_SERIES}/scene/freestanding.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/freestanding.webp`,
  },
  {
    id: "p3_20",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "圆形酒精火盆",
    nameEn: "Round Ethanol Fire Bowl",
    description: "圆形真火酒精火盆，适合庭院、露台、度假酒店和户外休闲空间。",
    descriptionEn:
      "Round real-flame ethanol fire bowl for patios, terraces, resort hotels, and outdoor lounge spaces.",
    installation: "户外 / 火盆",
    priceCny: 5800,
    images: [
      `${ETHANOL_SERIES}/product/round-fire-bowl.webp`,
      `${ETHANOL_SERIES}/scene/round-fire-bowl.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/round-fire-bowl.webp`,
  },
  {
    id: "p3_21",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "户外酒精火桌",
    nameEn: "Outdoor Ethanol Fire Table",
    description: "户外长条酒精火桌，适合露台、屋顶花园、商业外摆和度假酒店项目。",
    descriptionEn:
      "Outdoor ethanol fire table for terraces, rooftop gardens, commercial patios, and resort projects.",
    installation: "户外 / 火桌",
    priceCny: 15800,
    images: [
      `${ETHANOL_SERIES}/product/outdoor-fire-table.webp`,
      `${ETHANOL_SERIES}/scene/outdoor-fire-table.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/outdoor-fire-table.webp`,
  },
  {
    id: "p3_22",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "岩板岛台酒精壁炉",
    nameEn: "Stone Island Ethanol Fireplace",
    description: "岩板或石材岛台式酒精壁炉，可与客厅、餐厅、开放式厨房和商业接待空间结合。",
    descriptionEn:
      "Stone island ethanol fireplace for living rooms, dining areas, open kitchens, and commercial reception spaces.",
    installation: "岛台式",
    priceCny: 22800,
    images: [
      `${ETHANOL_SERIES}/product/stone-island.webp`,
      `${ETHANOL_SERIES}/scene/stone-island.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/stone-island.webp`,
  },
  {
    id: "p3_23",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "酒店大堂长条酒精壁炉",
    nameEn: "Hotel Lobby Linear Ethanol Fireplace",
    description: "超长线性酒精壁炉，适合酒店大堂、会所、售楼部和商业接待区的真火主景。",
    descriptionEn:
      "Extra-long linear ethanol fireplace for hotel lobbies, clubs, sales centers, and commercial reception areas.",
    installation: "工程长条",
    priceCny: 32800,
    images: [
      `${ETHANOL_SERIES}/product/hotel-lobby-linear.webp`,
      `${ETHANOL_SERIES}/scene/hotel-lobby-linear.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/hotel-lobby-linear.webp`,
  },
  {
    id: "p3_24",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "嵌入式壁龛酒精壁炉套件",
    nameEn: "Built-In Ethanol Fireplace Niche Kit",
    description: "适合背景墙和壁龛安装的酒精壁炉套件，包含框体、火槽、玻璃挡火和安装结构。",
    descriptionEn:
      "Built-in ethanol fireplace niche kit with frame, burner, glass guard, and installation structure.",
    installation: "壁龛嵌入式",
    priceCny: 9800,
    images: [
      `${ETHANOL_SERIES}/product/wall-niche-kit.webp`,
      `${ETHANOL_SERIES}/scene/wall-niche-kit.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/wall-niche-kit.webp`,
  },
  {
    id: "p3_25",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "OEM酒精燃烧器套件",
    nameEn: "OEM Ethanol Burner Kit",
    description: "面向品牌方、工程商和批量客户的酒精燃烧器套件，可按图纸、样品和包装需求定制。",
    descriptionEn:
      "OEM ethanol burner kit for brands, contractors, and batch buyers, customizable by drawings, samples, and packaging needs.",
    installation: "OEM套件",
    priceCny: 4800,
    images: [
      `${ETHANOL_SERIES}/product/oem-burner-kit.webp`,
      `${ETHANOL_SERIES}/scene/oem-burner-kit.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/oem-burner-kit.webp`,
  },
  {
    id: "p3_26",
    category: "p3",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "悬挂式酒精壁炉",
    nameEn: "Suspended Ethanol Fireplace",
    description: "悬挂式艺术造型酒精壁炉，适合挑高客厅、会所、民宿和设计感空间。",
    descriptionEn:
      "Suspended sculptural ethanol fireplace for high-ceiling living rooms, clubs, boutique hotels, and design-led interiors.",
    installation: "悬挂式",
    priceCny: 13800,
    images: [
      `${ETHANOL_SERIES}/product/suspended-fireplace.webp`,
      `${ETHANOL_SERIES}/scene/suspended-fireplace.webp`,
    ],
    coverImage: `${ETHANOL_SERIES}/product/suspended-fireplace.webp`,
  },
  // === 雾化壁炉 ===
  {
    id: "p4_70",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "悬挂-分体款雾化壁炉（可定制）",
    nameEn: "Wall-Mounted Split Mist Fireplace (Customizable)",
    description: "壁炉宗师悬挂-分体款雾化壁炉，3D雾化火焰效果，可定制。",
    descriptionEn:
      "3D mist fireplace with wall-mounted split design, customizable flame effects.",
    installation: "悬挂式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E6%82%AC%E6%8C%82-%E5%88%86%E4%BD%93%E6%AC%BE/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E6%82%AC%E6%8C%82-%E5%88%86%E4%BD%93%E6%AC%BE/1.png`,
  },
  {
    id: "p4_69",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "双面观火雾化壁炉（可定制）",
    nameEn: "Double-Sided Mist Fireplace (Customizable)",
    description: "壁炉宗师双面观火雾化壁炉，双面可视火焰，适合隔断安装。",
    descriptionEn: "Double-sided mist fireplace, suitable for room divider installation.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E5%8F%8C%E9%9D%A2%E8%A7%82%E7%81%AB/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E5%8F%8C%E9%9D%A2%E8%A7%82%E7%81%AB/1.png`,
  },
  {
    id: "p4_68",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "全景观火雾化壁炉（可定制）",
    nameEn: "Panoramic Mist Fireplace (Customizable)",
    description: "壁炉宗师全景观火雾化壁炉，超宽全景火焰效果。",
    descriptionEn: "Panoramic mist fireplace with ultra-wide flame viewing area.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E5%85%A8%E6%99%AF%E8%A7%82%E7%81%AB/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E5%85%A8%E6%99%AF%E8%A7%82%E7%81%AB/1.png`,
  },
  {
    id: "p4_67",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "三面观火雾化壁炉（可定制）",
    nameEn: "Three-Sided Mist Fireplace (Customizable)",
    description: "壁炉宗师三面观火雾化壁炉，270°火焰视野，视觉震撼。",
    descriptionEn: "Three-sided mist fireplace with 270° flame view.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E4%B8%89%E9%9D%A2%E8%A7%82%E7%81%AB/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E4%B8%89%E9%9D%A2%E8%A7%82%E7%81%AB/1.png`,
  },
  {
    id: "p4_66",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "圆形雾化壁炉（可定制）",
    nameEn: "Round Mist Fireplace (Customizable)",
    description: "壁炉宗师圆形雾化壁炉，独特圆形设计，艺术感十足。",
    descriptionEn: "Round mist fireplace with unique circular design.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%9C%86%E5%BD%A2%E6%AC%BE/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%9C%86%E5%BD%A2%E6%AC%BE/1.png`,
  },
  {
    id: "p4_65",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "飞碟款悬挂雾化壁炉（可定制）",
    nameEn: "UFO Hanging Mist Fireplace (Customizable)",
    description: "壁炉宗师飞碟款悬挂雾化壁炉，悬挂设计，未来感造型。",
    descriptionEn: "UFO-shaped hanging mist fireplace with futuristic design.",
    installation: "悬挂式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E6%82%AC%E6%8C%82-%E9%A3%9E%E7%A2%9F%E6%AC%BE/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E6%82%AC%E6%8C%82-%E9%A3%9E%E7%A2%9F%E6%AC%BE/1.png`,
  },
  {
    id: "p4_64",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "隔断/屏风雾化壁炉（可定制）",
    nameEn: "Room Divider Mist Fireplace (Customizable)",
    description: "壁炉宗师可做隔断/屏风雾化壁炉，兼具隔断与装饰功能。",
    descriptionEn: "Mist fireplace that doubles as a room divider or screen.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E9%9A%94%E6%96%AD%3A%E5%B1%8F%E9%A3%8E/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E9%9A%94%E6%96%AD%3A%E5%B1%8F%E9%A3%8E/1.png`,
  },
  {
    id: "p4_63",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: '"太阳之眼"雾化壁炉（可定制）',
    nameEn: '"Eye of the Sun" Mist Fireplace (Customizable)',
    description: '壁炉宗师"太阳之眼"雾化壁炉，独特圆形造型，如太阳之眼。',
    descriptionEn: '"Eye of the Sun" mist fireplace with distinctive circular design.',
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E5%A4%AA%E9%98%B3%E4%B9%8B%E7%9C%BC/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E5%A4%AA%E9%98%B3%E4%B9%8B%E7%9C%BC/1.png`,
  },
  {
    id: "p4_62",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "单面观火雾化壁炉（可定制）",
    nameEn: "Single-Sided Mist Fireplace (Customizable)",
    description: "壁炉宗师单面观火雾化壁炉，经典单面设计，适合壁挂安装。",
    descriptionEn: "Single-sided mist fireplace, classic design for wall installation.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E5%8D%95%E9%9D%A2%E8%A7%82%E7%81%AB/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/%E5%B8%B8%E8%A7%84%E6%AC%BE-%E5%8D%95%E9%9D%A2%E8%A7%82%E7%81%AB/1.png`,
  },
  {
    id: "p4_11",
    category: "p4",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "智能3D雾化壁炉（可定制）",
    nameEn: "Smart 3D Mist Fireplace (Customizable)",
    description: "壁炉宗师智能3D雾化壁炉，智能控制，3D立体火焰效果。",
    descriptionEn: "Smart 3D mist fireplace with intelligent control and 3D flame effects.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E9%9B%BE%E5%8C%96%E5%A3%81%E7%82%89/1.png`,
  },
  // === 定制壁炉 ===
  {
    id: "p6_49",
    category: "p6",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "全品类定制壁炉服务",
    nameEn: "Full Category Custom Fireplace Service",
    description: "壁炉宗师提供个性化全品类壁炉定制服务，从设计到安装一站式解决。",
    descriptionEn:
      "Full-service custom fireplace design and installation for all categories.",
    installation: "悬挂/独立/嵌入",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E5%AE%9A%E5%88%B6%E5%A3%81%E7%82%89/%E5%86%85%E5%AE%B9%E9%A1%B5.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E5%AE%9A%E5%88%B6%E5%A3%81%E7%82%89/%E5%86%85%E5%AE%B9%E9%A1%B5.png`,
  },
  // === 电子壁炉 ===
  {
    id: "p7_6",
    category: "p7",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "电子壁炉（可定制）",
    nameEn: "Electric Fireplace (Customizable)",
    description: "壁炉宗师电子壁炉源头工厂产品，支持电视背景墙、酒店客房、样板间和商业空间的尺寸、火焰效果、结构和OEM/ODM定制。",
    descriptionEn:
      "Fireplace Master electric fireplace source-factory product with custom size, flame effect, structure, and OEM/ODM options for TV walls, hotel rooms, show flats, and commercial spaces.",
    installation: "嵌入式",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E7%94%B5%E5%AD%90%E5%A3%81%E7%82%89/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E7%94%B5%E5%AD%90%E5%A3%81%E7%82%89/1.png`,
  },
  // === 户外火景 ===
  {
    id: "p88_51",
    category: "p88",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "户外火景（可定制）",
    nameEn: "Outdoor Fire Feature (Customizable)",
    description: "壁炉宗师户外火景，打造户外庭院温暖氛围，可定制各种造型。",
    descriptionEn: "Outdoor fire features for garden and patio, customizable designs.",
    installation: "独立/嵌入",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E6%88%B7%E5%A4%96%E7%81%AB%E6%99%AF/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E6%88%B7%E5%A4%96%E7%81%AB%E6%99%AF/1.png`,
  },
  // === 工具附件 ===
  {
    id: "p8_52",
    category: "p8",
    brand: "壁炉宗师",
    brandCountry: "丹麦",
    name: "壁炉工具套装",
    nameEn: "Fireplace Tool Set",
    description: "丹麦Rais壁炉工具套装，高品质壁炉配件。",
    descriptionEn: "Danish Rais fireplace tool set, high-quality accessories.",
    installation: "附件",
    images: [`${OSS}/%E4%BA%A7%E5%93%81/%E5%B7%A5%E5%85%B7%E9%99%84%E4%BB%B6/1.png`],
    coverImage: `${OSS}/%E4%BA%A7%E5%93%81/%E5%B7%A5%E5%85%B7%E9%99%84%E4%BB%B6/1.png`,
  },
  // === 全息壁炉 ===
  {
    id: "p9_1",
    category: "p9",
    brand: "壁炉宗师",
    brandCountry: "中国",
    name: "全息壁炉（可定制）",
    nameEn: "Holographic Fireplace (Customizable)",
    description: "壁炉宗师全息壁炉源头工厂产品，适合展厅、酒店大堂、商业橱窗、会所和沉浸式空间，可定制全息火焰影像、尺寸比例、安装结构和控制系统。",
    descriptionEn:
      "Fireplace Master holographic fireplace source-factory product for showrooms, hotel lobbies, retail windows, clubs, and immersive spaces, with custom flame visuals, size ratio, installation structure, and control system.",
    installation: "嵌入式",
    images: ["/media/home/featured-products/featured-product-4.png"],
    coverImage: "/media/home/featured-products/featured-product-4.png",
  },
];

export const products: Product[] = productCatalog.filter((product) =>
  activeCategoryIds.has(product.category),
);

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.category === categoryId);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getCategoryName(categoryId: string): string {
  return categories.find((c) => c.id === categoryId)?.name || categoryId;
}

export function getCategory(categoryId: string) {
  return categories.find((c) => c.id === categoryId);
}
