/**
 * Generate translation data files for de, fr, es, it, ru, pt.
 * Run: node scripts/generate-langs.mjs
 */
import { writeFileSync } from "fs";
import { resolve } from "path";

// ─── Fixed translations ───────────────────────────────────────

const install = {
  de: {
    "独立式": "Freistehend",
    "嵌入式": "Einbaugerät",
    "壁挂式": "Wandmontiert",
    "悬挂式": "Hängend",
    "悬挂/独立/嵌入": "Hängend / Freistehend / Einbau",
    "独立/嵌入": "Freistehend / Einbau",
    "附件": "Zubehör",
  },
  fr: {
    "独立式": "Autonome",
    "嵌入式": "Encastrable",
    "壁挂式": "Mural",
    "悬挂式": "Suspendu",
    "悬挂/独立/嵌入": "Suspendu / Autonome / Encastrable",
    "独立/嵌入": "Autonome / Encastrable",
    "附件": "Accessoires",
  },
  es: {
    "独立式": "Independiente",
    "嵌入式": "Empotrable",
    "壁挂式": "De pared",
    "悬挂式": "Colgante",
    "悬挂/独立/嵌入": "Colgante / Independiente / Empotrable",
    "独立/嵌入": "Independiente / Empotrable",
    "附件": "Accesorios",
  },
  it: {
    "独立式": "Autonomo",
    "嵌入式": "Da incasso",
    "壁挂式": "A parete",
    "悬挂式": "Sospeso",
    "悬挂/独立/嵌入": "Sospeso / Autonomo / Incasso",
    "独立/嵌入": "Autonomo / Incasso",
    "附件": "Accessori",
  },
  ru: {
    "独立式": "Отдельностоящий",
    "嵌入式": "Встраиваемый",
    "壁挂式": "Настенный",
    "悬挂式": "Подвесной",
    "悬挂/独立/嵌入": "Подвесной / Отдельностоящий / Встраиваемый",
    "独立/嵌入": "Отдельностоящий / Встраиваемый",
    "附件": "Аксессуары",
  },
  pt: {
    "独立式": "Autônomo",
    "嵌入式": "Embutido",
    "壁挂式": "De parede",
    "悬挂式": "Suspenso",
    "悬挂/独立/嵌入": "Suspenso / Autônomo / Embutido",
    "独立/嵌入": "Autônomo / Embutido",
    "附件": "Acessórios",
  },
};

const countries = {
  de: {
    "西班牙": "Spanien",
    "丹麦": "Dänemark",
    "奥地利": "Österreich",
    "瑞士": "Schweiz",
    "荷兰": "Niederlande",
    "中国": "China",
  },
  fr: {
    "西班牙": "Espagne",
    "丹麦": "Danemark",
    "奥地利": "Autriche",
    "瑞士": "Suisse",
    "荷兰": "Pays-Bas",
    "中国": "Chine",
  },
  es: {
    "西班牙": "España",
    "丹麦": "Dinamarca",
    "奥地利": "Austria",
    "瑞士": "Suiza",
    "荷兰": "Países Bajos",
    "中国": "China",
  },
  it: {
    "西班牙": "Spagna",
    "丹麦": "Danimarca",
    "奥地利": "Austria",
    "瑞士": "Svizzera",
    "荷兰": "Paesi Bassi",
    "中国": "Cina",
  },
  ru: {
    "西班牙": "Испания",
    "丹麦": "Дания",
    "奥地利": "Австрия",
    "瑞士": "Швейцария",
    "荷兰": "Нидерланды",
    "中国": "Китай",
  },
  pt: {
    "西班牙": "Espanha",
    "丹麦": "Dinamarca",
    "奥地利": "Áustria",
    "瑞士": "Suíça",
    "荷兰": "Países Baixos",
    "中国": "China",
  },
};

const categories = {
  de: {
    "p1:name": "Holzkamin",
    "p2:name": "Gaskamin",
    "p3:name": "Alkoholkamin",
    "p4:name": "Nebelkamin",
    "p7:name": "Elektrokamin",
    "p6:name": "Kundenspezifischer Kamin",
    "p88:name": "Außenfeuerstelle",
    "p8:name": "Zubehör",
  },
  fr: {
    "p1:name": "Cheminée à Bois",
    "p2:name": "Cheminée à Gaz",
    "p3:name": "Cheminée à Alcool",
    "p4:name": "Cheminée à Brume",
    "p7:name": "Cheminée Électrique",
    "p6:name": "Cheminée Sur Mesure",
    "p88:name": "Foyer Extérieur",
    "p8:name": "Accessoires",
  },
  es: {
    "p1:name": "Chimenea de Leña",
    "p2:name": "Chimenea de Gas",
    "p3:name": "Chimenea de Alcohol",
    "p4:name": "Chimenea de Niebla",
    "p7:name": "Chimenea Eléctrica",
    "p6:name": "Chimenea Personalizada",
    "p88:name": "Fuego Exterior",
    "p8:name": "Accesorios",
  },
  it: {
    "p1:name": "Caminetto a Legna",
    "p2:name": "Caminetto a Gas",
    "p3:name": "Caminetto ad Alcol",
    "p4:name": "Caminetto a Nebbia",
    "p7:name": "Caminetto Elettrico",
    "p6:name": "Caminetto Personalizzato",
    "p88:name": "Fuoco all'Aperto",
    "p8:name": "Accessori",
  },
  ru: {
    "p1:name": "Дровяной камин",
    "p2:name": "Газовый камин",
    "p3:name": "Спиртовой камин",
    "p4:name": "Тумановый камин",
    "p7:name": "Электрический камин",
    "p6:name": "Камин на заказ",
    "p88:name": "Уличный огонь",
    "p8:name": "Аксессуары",
  },
  pt: {
    "p1:name": "Lareira a Lenha",
    "p2:name": "Lareira a Gás",
    "p3:name": "Lareira a Álcool",
    "p4:name": "Lareira de Névoa",
    "p7:name": "Lareira Elétrica",
    "p6:name": "Lareira Personalizada",
    "p88:name": "Fogo Externo",
    "p8:name": "Acessórios",
  },
};

// ─── Product translations ────────────────────────────────────
// Format: [id, localized name, localized description]

const prods = {
  de: [
    ["p1_71", "Lacunza Altea Freistehender Holzofen mit Backofen", "Spanischer Lacunza Altea freistehender Holzofen mit Backofen, vereint Kochen und Heizen in einem klassischen Design."],
    ["p1_1", "Lacunza Stelar 93 Freistehender Holzkamin", "Spanischer Lacunza Stelar 93 freistehender Holzkamin, elegantes Design mit hervorragender Heizeffizienz."],
    ["p1_45", "Lacunza Sara Einbau-Holzkamin", "Spanischer Lacunza Sara Einbau-Holzkamin, platzsparendes minimalistisches Design."],
    ["p1_44", "Lacunza Oslo Freistehender Holzofen", "Spanischer Lacunza Oslo freistehender Holzofen mit Kochfunktion."],
    ["p1_43", "Lacunza Nickel Doppelseitiger Einbau-Holzkamin", "Spanischer Lacunza Nickel doppelseitiger Einbau-Holzkamin, beidseitige Glasscheiben für Feuerblick von beiden Seiten."],
    ["p1_42", "Lacunza K2 800 Einbau-Holzkamin", "Spanischer Lacunza K2 800 Einbau-Holzkamin mit großer Aussichtsfläche."],
    ["p1_41", "Lacunza Itaca Einbau-Holzkamin", "Spanischer Lacunza Itaca einseitiger Einbau-Holzkamin, klassisches Design mit effizienter Heizung."],
    ["p1_39", "Lacunza CM 300R Eck-Freistehender Holzkamin", "Spanischer Lacunza CM 300R Eck-freistehender Holzkamin, entwickelt für Eckinstallation."],
    ["p1_38", "Lacunza Clasica 7T Holzofen mit Backofen", "Spanischer Lacunza Clasica 7T Holzofen mit Backofen, europäischer Landhausstil."],
    ["p1_37", "Lacunza Atlantic 603 Freistehender Holzkamin", "Spanischer Lacunza Atlantic 603 freistehender Holzkamin, elegante Optik mit leistungsstarker Heizung."],
    ["p1_36", "Lacunza Adour 700ST Einbau-Holzkamin", "Spanischer Lacunza Adour 700ST Einbau-Holzkamin, klare Linien, modernes Design."],
    ["p1_61", "Rais Q TEE 2C Freistehender Holzkamin", "Dänischer Rais Q TEE 2C freistehender Holzkamin, nordisch-minimalistisches Design, hocheffiziente Verbrennung."],
    ["p1_60", "Rais Nexo Serie Freistehender Holzkamin", "Dänischer Rais Nexo Serie freistehender Holzkamin, moderner minimalistischer Stil."],
    ["p1_59", "Rais Juno L Freistehender Holzkamin", "Dänischer Rais Juno L freistehender Holzkamin mit rundem Sichtfenster, einzigartiges Design."],
    ["p1_58", "Rais Caro 90 Freistehender Holzkamin", "Dänischer Rais Caro 90 freistehender Holzkamin, elegante zylindrische Form."],
    ["p1_28", "Rais Viva L Serie Freistehender Holzkamin", "Dänischer Rais Viva L Serie freistehender Holzkamin, dynamischer Flammeneffekt."],
    ["p1_27", "Rais Visio 3 Dreiseitiger Einbau-Holzkamin", "Dänischer Rais Visio 3 dreiseitiger Einbau-Holzkamin, 270° Panoramablick auf die Flammen."],
    ["p1_26", "Rais Q-TEE 2 Freistehender Holzkamin", "Dänischer Rais Q-TEE 2 freistehender Holzkamin, geometrisches künstlerisches Design."],
    ["p1_25", "Rais Q-BE Eckblick Freistehender Holzkamin", "Dänischer Rais Q-BE Eckblick freistehender Holzkamin, innovatives Winkeldesign."],
    ["p1_24", "Rais Pilar Freistehender Holzkamin", "Dänischer Rais Pilar freistehender Holzkamin, säulenförmiges Design, schlicht und elegant."],
    ["p1_23", "Rais Bionic Fire Doppelkammer-Holzkamin", "Dänischer Rais Bionic Fire Doppelkammer-Holzkamin, innovative Doppelverbrennungstechnologie."],
    ["p1_22", "Haas+sohn Treviso Speckstein-Holzkamin", "Österreichischer Haas+sohn Treviso Speckstein-Holzkamin, Speckstein-Wärmespeicher für langanhaltende Wärme."],
    ["p1_21", "Haas+sohn Kuopio-II Speckstein-Holzkamin", "Österreichischer Haas+sohn Kuopio-II Speckstein-Holzkamin, klassische nordische Speckstein-Handwerkskunst."],
    ["p1_20", "Haas+sohn Ficus-II-RLU Freistehender Holzkamin", "Österreichischer Haas+sohn Ficus-II-RLU freistehender Holzkamin, elegantes geschwungenes Design."],
    ["p1_2", "Haas+sohn Aruba Easy Speckstein-Holzofen", "Österreichischer Haas+sohn Aruba Easy Speckstein-Holzofen, einfache Bedienung, effiziente Wärmespeicherung."],
    ["p1_35", "Ruegg Tillia Dreiseitiger Einbau-Holzkamin", "Schweizer Ruegg Tillia dreiseitiger Einbau-Holzkamin, Schweizer Präzisionsqualität."],
    ["p1_34", "Ruegg Rondeo Einbau-Holzkamin mit gebogenem Glas", "Schweizer Ruegg Rondeo Einbau-Holzkamin mit gebogenem Glas, einzigartiges Design."],
    ["p1_33", "Ruegg RII Eck-Einbau-Holzkamin", "Schweizer Ruegg RII Eck-Einbau-Holzkamin, platzsparendes Eckdesign."],
    ["p1_18", "Ruegg Odeon 270° Gebogener Hänge-Holzkamin", "Schweizer Ruegg Odeon 270° gebogener Hänge-Holzkamin, künstlerisches Hängedesign mit Panoramablick."],
    ["p2_56", "Element4 Lucius 140 Einbau-Gaskamin", "Niederländischer Element4 Lucius 140 Einbau-Gaskamin, große Sichtfläche, moderne Gasttechnologie."],
    ["p2_55", "Element4 Tenore 140 Einbau-Gaskamin", "Niederländischer Element4 Tenore 140 Einbau-Gaskamin, lineares minimalistisches Design."],
    ["p2_54", "Element4 Summum 100F Einbau-Gaskamin", "Niederländischer Element4 Summum 100F Einbau-Gaskamin, Premium-Gaskamin-Erlebnis."],
    ["p2_53", "Element4 Sky Indoor Serie Gaskamin", "Niederländischer Element4 Sky Indoor Serie Gaskamin, nahtloses Innen- und Außendesign."],
    ["p2_31", "Element4 Trisore 140 Dreiseitiger Gaskamin", "Niederländischer Element4 Trisore 140 dreiseitiger Einbau-Gaskamin, Panorama-Flammenblick."],
    ["p2_29", "Element4 Bidore 100 Eck-Gaskamin", "Niederländischer Element4 Bidore 100 Eck-Einbau-Gaskamin, beidseitiger Eckblick."],
    ["p3_14", "Alkoholkamin (Anpassbar)", "Bioethanol-Kamin, Größe und Aussehen anpassbar, umweltfreundlich."],
    ["p4_70", "Wandmontierter geteilter Nebelkamin (Anpassbar)", "3D-Nebelkamin mit wandmontiertem geteiltem Design, anpassbare Flammeneffekte."],
    ["p4_69", "Doppelseitiger Nebelkamin (Anpassbar)", "Doppelseitiger Nebelkamin, ideal für Raumteilerinstallation."],
    ["p4_68", "Panorama-Nebelkamin (Anpassbar)", "Panorama-Nebelkamin mit extremer Breitbild-Flammenansicht."],
    ["p4_67", "Dreiseitiger Nebelkamin (Anpassbar)", "Dreiseitiger Nebelkamin mit 270° Flammenblicken."],
    ["p4_66", "Runder Nebelkamin (Anpassbar)", "Runder Nebelkamin mit einzigartigem kreisförmigem Design."],
    ["p4_65", "UFO Hänge-Nebelkamin (Anpassbar)", "UFO-förmiger Hänge-Nebelkamin mit futuristischem Design."],
    ["p4_64", "Raumteiler-Bildschirm-Nebelkamin (Anpassbar)", "Nebelkamin, der auch als Raumteiler oder Bildschirm dient."],
    ["p4_62", "Einseitiger Nebelkamin (Anpassbar)", "Einseitiger Nebelkamin, klassisches Design für Wandinstallation."],
    ["p4_11", "Intelligenter 3D-Nebelkamin (Anpassbar)", "Intelligenter 3D-Nebelkamin mit intelligenter Steuerung und 3D-Flammeneffekten."],
    ["p6_49", "Kompletter Kundenspezifischer Kaminservice", "Rundum-Service für kundenspezifische Kaminplanung und -installation für alle Kategorien."],
    ["p7_6", "Elektrokamin (Anpassbar)", "Elektrokamin mit realistischen Flammeneffekten, anpassbare Größe, einfache Installation."],
    ["p88_51", "Außenfeuerstelle (Anpassbar)", "Außenfeuerstelle für Garten und Terrasse, anpassbare Designs."],
    ["p8_52", "Kamin-Werkzeugsatz", "Dänischer Rais Kamin-Werkzeugsatz, hochwertiges Zubehör."],
  ],
  fr: [
    ["p1_71", "Lacunza Altea Poêle à Bois Autonome avec Four", "Poêle à bois autonome espagnol Lacunza Altea avec four, alliant cuisine et chauffage dans un design classique."],
    ["p1_1", "Lacunza Stelar 93 Cheminée à Bois Autonome", "Cheminée à bois autonome espagnole Lacunza Stelar 93, design élégant avec une excellente efficacité de chauffage."],
    ["p1_45", "Lacunza Sara Cheminée à Bois Encastrable", "Cheminée à bois encastrable espagnole Lacunza Sara, design minimaliste gain de place."],
    ["p1_44", "Lacunza Oslo Poêle à Bois Autonome", "Poêle à bois autonome espagnol Lacunza Oslo avec fonction de cuisson."],
    ["p1_43", "Lacunza Nickel Cheminée à Bois Encastrable Double Face", "Cheminée à bois encastrable double face espagnole Lacunza Nickel, vitres des deux côtés."],
    ["p1_42", "Lacunza K2 800 Cheminée à Bois Encastrable", "Cheminée à bois encastrable espagnole Lacunza K2 800 avec grande vitre."],
    ["p1_41", "Lacunza Itaca Cheminée à Bois Encastrable", "Cheminée à bois encastrable simple face espagnole Lacunza Itaca, design classique."],
    ["p1_39", "Lacunza CM 300R Cheminée à Bois Autonome d'Angle", "Cheminée à bois autonome d'angle espagnole Lacunza CM 300R, conçue pour installation en angle."],
    ["p1_38", "Lacunza Clasica 7T Poêle à Bois avec Four", "Poêle à bois espagnol Lacunza Clasica 7T avec four, style champêtre européen."],
    ["p1_37", "Lacunza Atlantic 603 Cheminée à Bois Autonome", "Cheminée à bois autonome espagnole Lacunza Atlantic 603, aspect imposant avec chauffage puissant."],
    ["p1_36", "Lacunza Adour 700ST Cheminée à Bois Encastrable", "Cheminée à bois encastrable espagnole Lacunza Adour 700ST, lignes épurées, design moderne."],
    ["p1_61", "Rais Q TEE 2C Cheminée à Bois Autonome", "Cheminée à bois autonome danoise Rais Q TEE 2C, design minimaliste nordique."],
    ["p1_60", "Rais Nexo Série Cheminée à Bois Autonome", "Cheminée à bois autonome danoise Rais Nexo série, style moderne minimaliste."],
    ["p1_59", "Rais Juno L Cheminée à Bois Autonome", "Cheminée à bois autonome danoise Rais Juno L avec fenêtre ronde."],
    ["p1_58", "Rais Caro 90 Cheminée à Bois Autonome", "Cheminée à bois autonome danoise Rais Caro 90, forme cylindrique élégante."],
    ["p1_28", "Rais Viva L Série Cheminée à Bois Autonome", "Cheminée à bois autonome danoise Rais Viva L série, effet de flamme dynamique."],
    ["p1_27", "Rais Visio 3 Cheminée à Bois Encastrable Trois Faces", "Cheminée à bois encastrable trois faces danoise Rais Visio 3, vue panoramique 270°."],
    ["p1_26", "Rais Q-TEE 2 Cheminée à Bois Autonome", "Cheminée à bois autonome danoise Rais Q-TEE 2, design géométrique artistique."],
    ["p1_25", "Rais Q-BE Cheminée à Bois Autonome Vue d'Angle", "Cheminée à bois autonome danoise Rais Q-BE vue d'angle, design angulaire innovant."],
    ["p1_24", "Rais Pilar Cheminée à Bois Autonome", "Cheminée à bois autonome danoise Rais Pilar, design en colonne, simple et élégant."],
    ["p1_23", "Rais Bionic Fire Cheminée à Bois Double Chambre", "Cheminée à bois danoise Rais Bionic Fire à double chambre, technologie de combustion innovante."],
    ["p1_22", "Haas+sohn Treviso Cheminée à Bois en Stéatite", "Cheminée à bois en stéatite autrichienne Haas+sohn Treviso, chaleur durable."],
    ["p1_21", "Haas+sohn Kuopio-II Cheminée à Bois en Stéatite", "Cheminée à bois en stéatite autrichienne Haas+sohn Kuopio-II, artisanat nordique."],
    ["p1_20", "Haas+sohn Ficus-II-RLU Cheminée à Bois Autonome", "Cheminée à bois autonome autrichienne Haas+sohn Ficus-II-RLU, design courbé élégant."],
    ["p1_2", "Haas+sohn Aruba Easy Poêle à Bois en Stéatite", "Poêle à bois en stéatite autrichien Haas+sohn Aruba Easy, facile à utiliser."],
    ["p1_35", "Ruegg Tillia Cheminée à Bois Encastrable Trois Faces", "Cheminée à bois encastrable trois faces suisse Ruegg Tillia, précision suisse."],
    ["p1_34", "Ruegg Rondeo Cheminée à Bois Encastrable Verre Courbé", "Cheminée à bois encastrable suisse Ruegg Rondeo au verre courbé unique."],
    ["p1_33", "Ruegg RII Cheminée à Bois Encastrable d'Angle", "Cheminée à bois encastrable d'angle suisse Ruegg RII, gain de place."],
    ["p1_18", "Ruegg Odeon 270° Cheminée à Bois Suspendue Courbée", "Cheminée à bois suspendue courbée suisse Ruegg Odeon 270°, design artistique."],
    ["p2_56", "Element4 Lucius 140 Cheminée à Gaz Encastrable", "Cheminée à gaz encastrable néerlandaise Element4 Lucius 140, grande vitre."],
    ["p2_55", "Element4 Tenore 140 Cheminée à Gaz Encastrable", "Cheminée à gaz encastrable néerlandaise Element4 Tenore 140, design linéaire minimaliste."],
    ["p2_54", "Element4 Summum 100F Cheminée à Gaz Encastrable", "Cheminée à gaz encastrable néerlandaise Element4 Summum 100F, expérience premium."],
    ["p2_53", "Element4 Sky Série Intérieure Cheminée à Gaz", "Cheminée à gaz intérieure néerlandaise Element4 Sky, design intérieur-extérieur."],
    ["p2_31", "Element4 Trisore 140 Cheminée à Gaz Trois Faces", "Cheminée à gaz trois faces néerlandaise Element4 Trisore 140, vue panoramique."],
    ["p2_29", "Element4 Bidore 100 Cheminée à Gaz d'Angle", "Cheminée à gaz d'angle néerlandaise Element4 Bidore 100, vue d'angle double face."],
    ["p3_14", "Cheminée à Alcool (Personnalisable)", "Cheminée bioéthanol, taille et apparence personnalisables, écologique."],
    ["p4_70", "Cheminée à Brume Murale Divisée (Personnalisable)", "Cheminée à brume 3D design mural divisé, effets de flamme personnalisables."],
    ["p4_69", "Cheminée à Brume Double Face (Personnalisable)", "Cheminée à brume double face, idéale pour séparation de pièces."],
    ["p4_68", "Cheminée à Brume Panoramique (Personnalisable)", "Cheminée à brume panoramique ultra-large."],
    ["p4_67", "Cheminée à Brume Trois Faces (Personnalisable)", "Cheminée à brume trois faces avec vue 270°."],
    ["p4_66", "Cheminée à Brume Ronde (Personnalisable)", "Cheminée à brume ronde au design circulaire unique."],
    ["p4_65", "Cheminée à Brume Suspendue OVNI (Personnalisable)", "Cheminée à brume suspendue en forme d'OVNI au design futuriste."],
    ["p4_64", "Cheminée à Brume Cloison (Personnalisable)", "Cheminée à brume qui sert aussi de cloison ou d'écran."],
    ["p4_62", "Cheminée à Brume Simple Face (Personnalisable)", "Cheminée à brume simple face, design classique pour installation murale."],
    ["p4_11", "Cheminée à Brume 3D Intelligente (Personnalisable)", "Cheminée à brume 3D intelligente avec contrôle intelligent."],
    ["p6_49", "Service Complet de Cheminée Personnalisée", "Service de conception et d'installation de cheminée sur mesure pour toutes catégories."],
    ["p7_6", "Cheminée Électrique (Personnalisable)", "Cheminée électrique avec effets de flamme réalistes, taille personnalisable."],
    ["p88_51", "Foyer Extérieur (Personnalisable)", "Foyer extérieur pour jardin et terrasse, designs personnalisables."],
    ["p8_52", "Kit d'Outils de Cheminée", "Kit d'outils de cheminée danois Rais, accessoires de haute qualité."],
  ],
  es: [
    ["p1_71", "Lacunza Altea Estufa de Leña Autónoma con Horno", "Estufa de leña autónoma española Lacunza Altea con horno, combinando cocina y calefacción."],
    ["p1_1", "Lacunza Stelar 93 Chimenea de Leña Autónoma", "Chimenea de leña autónoma española Lacunza Stelar 93, diseño elegante."],
    ["p1_45", "Lacunza Sara Chimenea de Leña Empotrable", "Chimenea de leña empotrable española Lacunza Sara, diseño minimalista."],
    ["p1_44", "Lacunza Oslo Estufa de Leña Autónoma", "Estufa de leña autónoma española Lacunza Oslo con función de cocina."],
    ["p1_43", "Lacunza Nickel Chimenea de Leña Empotrable Doble Cara", "Chimenea de leña empotrable doble cara española Lacunza Nickel."],
    ["p1_42", "Lacunza K2 800 Chimenea de Leña Empotrable", "Chimenea de leña empotrable española Lacunza K2 800 con gran ventanal."],
    ["p1_41", "Lacunza Itaca Chimenea de Leña Empotrable", "Chimenea de leña empotrable simple cara española Lacunza Itaca."],
    ["p1_39", "Lacunza CM 300R Chimenea de Leña Autónoma de Esquina", "Chimenea de leña autónoma de esquina española Lacunza CM 300R."],
    ["p1_38", "Lacunza Clasica 7T Estufa de Leña con Horno", "Estufa de leña española Lacunza Clasica 7T con horno, estilo campestre europeo."],
    ["p1_37", "Lacunza Atlantic 603 Chimenea de Leña Autónoma", "Chimenea de leña autónoma española Lacunza Atlantic 603, aspecto imponente."],
    ["p1_36", "Lacunza Adour 700ST Chimenea de Leña Empotrable", "Chimenea de leña empotrable española Lacunza Adour 700ST, líneas limpias."],
    ["p1_61", "Rais Q TEE 2C Chimenea de Leña Autónoma", "Chimenea de leña autónoma danesa Rais Q TEE 2C, diseño nórdico minimalista."],
    ["p1_60", "Rais Nexo Serie Chimenea de Leña Autónoma", "Chimenea de leña autónoma danesa Rais Nexo serie, estilo minimalista moderno."],
    ["p1_59", "Rais Juno L Chimenea de Leña Autónoma", "Chimenea de leña autónoma danesa Rais Juno L con ventana circular."],
    ["p1_58", "Rais Caro 90 Chimenea de Leña Autónoma", "Chimenea de leña autónoma danesa Rais Caro 90, forma cilíndrica elegante."],
    ["p1_28", "Rais Viva L Serie Chimenea de Leña Autónoma", "Chimenea de leña autónoma danesa Rais Viva L serie, efecto dinámico."],
    ["p1_27", "Rais Visio 3 Chimenea de Leña Empotrable Tres Caras", "Chimenea de leña empotrable tres caras danesa Rais Visio 3, vista 270°."],
    ["p1_26", "Rais Q-TEE 2 Chimenea de Leña Autónoma", "Chimenea de leña autónoma danesa Rais Q-TEE 2, diseño geométrico."],
    ["p1_25", "Rais Q-BE Chimenea de Leña Autónoma Vista Angular", "Chimenea de leña autónoma danesa Rais Q-BE vista angular, diseño innovador."],
    ["p1_24", "Rais Pilar Chimenea de Leña Autónoma", "Chimenea de leña autónoma danesa Rais Pilar, diseño columnar."],
    ["p1_23", "Rais Bionic Fire Chimenea de Leña Doble Cámara", "Chimenea de leña danesa Rais Bionic Fire de doble cámara, tecnología innovadora."],
    ["p1_22", "Haas+sohn Treviso Chimenea de Leña de Esteatita", "Chimenea de leña de esteatita austriaca Haas+sohn Treviso, calor duradero."],
    ["p1_21", "Haas+sohn Kuopio-II Chimenea de Leña de Esteatita", "Chimenea de leña de esteatita austriaca Haas+sohn Kuopio-II."],
    ["p1_20", "Haas+sohn Ficus-II-RLU Chimenea de Leña Autónoma", "Chimenea de leña autónoma austriaca Haas+sohn Ficus-II-RLU, diseño curvo."],
    ["p1_2", "Haas+sohn Aruba Easy Estufa de Leña de Esteatita", "Estufa de leña de esteatita austriaca Haas+sohn Aruba Easy."],
    ["p1_35", "Ruegg Tillia Chimenea de Leña Empotrable Tres Caras", "Chimenea de leña empotrable tres caras suiza Ruegg Tillia, precisión suiza."],
    ["p1_34", "Ruegg Rondeo Chimenea de Leña Empotrable Curva", "Chimenea de leña empotrable suiza Ruegg Rondeo con vidrio curvo único."],
    ["p1_33", "Ruegg RII Chimenea de Leña Empotrable de Esquina", "Chimenea de leña empotrable de esquina suiza Ruegg RII."],
    ["p1_18", "Ruegg Odeon 270° Chimenea de Leña Suspendida Curva", "Chimenea de leña suspendida curva suiza Ruegg Odeon 270°, diseño artístico."],
    ["p2_56", "Element4 Lucius 140 Chimenea de Gas Empotrable", "Chimenea de gas empotrable neerlandesa Element4 Lucius 140."],
    ["p2_55", "Element4 Tenore 140 Chimenea de Gas Empotrable", "Chimenea de gas empotrable neerlandesa Element4 Tenore 140, diseño minimalista."],
    ["p2_54", "Element4 Summum 100F Chimenea de Gas Empotrable", "Chimenea de gas empotrable neerlandesa Element4 Summum 100F, experiencia premium."],
    ["p2_53", "Element4 Sky Serie Interior Chimenea de Gas", "Chimenea de gas interior neerlandesa Element4 Sky, diseño integrado."],
    ["p2_31", "Element4 Trisore 140 Chimenea de Gas Tres Caras", "Chimenea de gas tres caras neerlandesa Element4 Trisore 140, vista panorámica."],
    ["p2_29", "Element4 Bidore 100 Chimenea de Gas de Esquina", "Chimenea de gas de esquina neerlandesa Element4 Bidore 100."],
    ["p3_14", "Chimenea de Alcohol (Personalizable)", "Chimenea de bioetanol, tamaño y apariencia personalizables, ecológica."],
    ["p4_70", "Chimenea de Niebla Montada Dividida (Personalizable)", "Chimenea de niebla 3D montada dividida, efectos personalizables."],
    ["p4_69", "Chimenea de Niebla Doble Cara (Personalizable)", "Chimenea de niebla doble cara, ideal para división de ambientes."],
    ["p4_68", "Chimenea de Niebla Panorámica (Personalizable)", "Chimenea de niebla panorámica ultra ancha."],
    ["p4_67", "Chimenea de Niebla Tres Caras (Personalizable)", "Chimenea de niebla tres caras con vista 270°."],
    ["p4_66", "Chimenea de Niebla Redonda (Personalizable)", "Chimenea de niebla redonda de diseño circular único."],
    ["p4_65", "Chimenea de Niebla Colgante OVNI (Personalizable)", "Chimenea de niebla colgante en forma de OVNI."],
    ["p4_64", "Chimenea de Niebla Divisoria (Personalizable)", "Chimenea de niebla que funciona como divisor o pantalla."],
    ["p4_62", "Chimenea de Niebla Simple Cara (Personalizable)", "Chimenea de niebla simple cara, diseño clásico."],
    ["p4_11", "Chimenea de Niebla 3D Inteligente (Personalizable)", "Chimenea de niebla 3D inteligente con control inteligente."],
    ["p6_49", "Servicio Completo de Chimenea Personalizada", "Servicio integral de diseño e instalación de chimeneas personalizadas."],
    ["p7_6", "Chimenea Eléctrica (Personalizable)", "Chimenea eléctrica con efectos de llama realistas."],
    ["p88_51", "Fuego Exterior (Personalizable)", "Fuego exterior para jardín y patio, diseños personalizables."],
    ["p8_52", "Juego de Herramientas de Chimenea", "Juego de herramientas de chimenea danés Rais, accesorios de alta calidad."],
  ],
  it: [
    ["p1_71", "Lacunza Altea Stufa a Legna Autonoma con Forno", "Stufa a legna autonoma spagnola Lacunza Altea con forno, unisce cucina e riscaldamento."],
    ["p1_1", "Lacunza Stelar 93 Caminetto a Legna Autonomo", "Caminetto a legna autonomo spagnolo Lacunza Stelar 93, design elegante."],
    ["p1_45", "Lacunza Sara Caminetto a Legna da Incasso", "Caminetto a legna da incasso spagnolo Lacunza Sara, design minimalista."],
    ["p1_44", "Lacunza Oslo Stufa a Legna Autonoma", "Stufa a legna autonoma spagnola Lacunza Oslo con funzione cottura."],
    ["p1_43", "Lacunza Nickel Caminetto a Legna Incasso Bifacciale", "Caminetto a legna incasso bifacciale spagnolo Lacunza Nickel."],
    ["p1_42", "Lacunza K2 800 Caminetto a Legna da Incasso", "Caminetto a legna da incasso spagnolo Lacunza K2 800 con ampia vetrata."],
    ["p1_41", "Lacunza Itaca Caminetto a Legna da Incasso", "Caminetto a legna da incasso unifacciale spagnolo Lacunza Itaca."],
    ["p1_39", "Lacunza CM 300R Caminetto a Legna Autonomo d'Angolo", "Caminetto a legna autonomo d'angolo spagnolo Lacunza CM 300R."],
    ["p1_38", "Lacunza Clasica 7T Stufa a Legna con Forno", "Stufa a legna spagnola Lacunza Clasica 7T con forno, stile country europeo."],
    ["p1_37", "Lacunza Atlantic 603 Caminetto a Legna Autonomo", "Caminetto a legna autonomo spagnolo Lacunza Atlantic 603."],
    ["p1_36", "Lacunza Adour 700ST Caminetto a Legna da Incasso", "Caminetto a legna da incasso spagnolo Lacunza Adour 700ST, linee pulite."],
    ["p1_61", "Rais Q TEE 2C Caminetto a Legna Autonomo", "Caminetto a legna autonomo danese Rais Q TEE 2C, design nordico minimalista."],
    ["p1_60", "Rais Nexo Serie Caminetto a Legna Autonomo", "Caminetto a legna autonomo danese Rais Nexo serie, stile moderno."],
    ["p1_59", "Rais Juno L Caminetto a Legna Autonomo", "Caminetto a legna autonomo danese Rais Juno L con finestra circolare."],
    ["p1_58", "Rais Caro 90 Caminetto a Legna Autonomo", "Caminetto a legna autonomo danese Rais Caro 90, forma cilindrica."],
    ["p1_28", "Rais Viva L Serie Caminetto a Legna Autonomo", "Caminetto a legna autonomo danese Rais Viva L serie, fiamma dinamica."],
    ["p1_27", "Rais Visio 3 Caminetto a Legna Incasso Tre Facce", "Caminetto a legna incasso tre facce danese Rais Visio 3, vista 270°."],
    ["p1_26", "Rais Q-TEE 2 Caminetto a Legna Autonomo", "Caminetto a legna autonomo danese Rais Q-TEE 2, design geometrico."],
    ["p1_25", "Rais Q-BE Caminetto a Legna Autonomo Vista Angolare", "Caminetto a legna autonomo danese Rais Q-BE vista angolare."],
    ["p1_24", "Rais Pilar Caminetto a Legna Autonomo", "Caminetto a legna autonomo danese Rais Pilar, design a colonna."],
    ["p1_23", "Rais Bionic Fire Caminetto a Legna Doppia Camera", "Caminetto a legna danese Rais Bionic Fire a doppia camera."],
    ["p1_22", "Haas+sohn Treviso Caminetto a Legna in Steatite", "Caminetto a legna in steatite austriaco Haas+sohn Treviso, calore duraturo."],
    ["p1_21", "Haas+sohn Kuopio-II Caminetto a Legna in Steatite", "Caminetto a legna in steatite austriaco Haas+sohn Kuopio-II."],
    ["p1_20", "Haas+sohn Ficus-II-RLU Caminetto a Legna Autonomo", "Caminetto a legna autonomo austriaco Haas+sohn Ficus-II-RLU, design curvo."],
    ["p1_2", "Haas+sohn Aruba Easy Stufa a Legna in Steatite", "Stufa a legna in steatite austriaca Haas+sohn Aruba Easy."],
    ["p1_35", "Ruegg Tillia Caminetto a Legna Incasso Tre Facce", "Caminetto a legna incasso tre facce svizzero Ruegg Tillia, precisione svizzera."],
    ["p1_34", "Ruegg Rondeo Caminetto a Legna Incasso Vetro Curvo", "Caminetto a legna incasso svizzero Ruegg Rondeo con vetro curvo."],
    ["p1_33", "Ruegg RII Caminetto a Legna Incasso d'Angolo", "Caminetto a legna incasso d'angolo svizzero Ruegg RII."],
    ["p1_18", "Ruegg Odeon 270° Caminetto a Legna Sospeso Curvo", "Caminetto a legna sospeso curvo svizzero Ruegg Odeon 270°."],
    ["p2_56", "Element4 Lucius 140 Caminetto a Gas da Incasso", "Caminetto a gas da incasso olandese Element4 Lucius 140."],
    ["p2_55", "Element4 Tenore 140 Caminetto a Gas da Incasso", "Caminetto a gas da incasso olandese Element4 Tenore 140."],
    ["p2_54", "Element4 Summum 100F Caminetto a Gas da Incasso", "Caminetto a gas da incasso olandese Element4 Summum 100F."],
    ["p2_53", "Element4 Sky Serie Interna Caminetto a Gas", "Caminetto a gas interno olandese Element4 Sky, design integrato."],
    ["p2_31", "Element4 Trisore 140 Caminetto a Gas Tre Facce", "Caminetto a gas tre facce olandese Element4 Trisore 140, vista panoramica."],
    ["p2_29", "Element4 Bidore 100 Caminetto a Gas d'Angolo", "Caminetto a gas d'angolo olandese Element4 Bidore 100."],
    ["p3_14", "Caminetto ad Alcol (Personalizzabile)", "Caminetto bioetanolo, dimensioni personalizzabili, ecologico."],
    ["p4_70", "Caminetto a Nebbia Sospeso Diviso (Personalizzabile)", "Caminetto a nebbia 3D sospeso diviso, effetti personalizzabili."],
    ["p4_69", "Caminetto a Nebbia Bifacciale (Personalizzabile)", "Caminetto a nebbia bifacciale, ideale per divisori."],
    ["p4_68", "Caminetto a Nebbia Panoramico (Personalizzabile)", "Caminetto a nebbia panoramico ultra-wide."],
    ["p4_67", "Caminetto a Nebbia Tre Facce (Personalizzabile)", "Caminetto a nebbia tre facce con vista 270°."],
    ["p4_66", "Caminetto a Nebbia Rotondo (Personalizzabile)", "Caminetto a nebbia rotondo dal design circolare unico."],
    ["p4_65", "Caminetto a Nebbia Sospeso UFO (Personalizzabile)", "Caminetto a nebbia sospeso a forma di UFO."],
    ["p4_64", "Caminetto a Nebbia Divisorio (Personalizzabile)", "Caminetto a nebbia che funge da divisorio o schermo."],
    ["p4_62", "Caminetto a Nebbia Unifacciale (Personalizzabile)", "Caminetto a nebbia unifacciale, design classico."],
    ["p4_11", "Caminetto a Nebbia 3D Intelligente (Personalizzabile)", "Caminetto a nebbia 3D intelligente con controllo smart."],
    ["p6_49", "Servizio Completo Caminetto Personalizzato", "Servizio completo di progettazione e installazione caminetti personalizzati."],
    ["p7_6", "Caminetto Elettrico (Personalizzabile)", "Caminetto elettrico con effetti fiamma realistici."],
    ["p88_51", "Fuoco all'Aperto (Personalizzabile)", "Fuoco all'aperto per giardino e patio, design personalizzabili."],
    ["p8_52", "Set di Utensili per Caminetto", "Set di utensili per caminetto danese Rais, accessori di qualità."],
  ],
  ru: [
    ["p1_71", "Lacunza Altea Отдельностоящая дровяная печь с духовкой", "Испанская отдельностоящая дровяная печь Lacunza Altea с духовкой, сочетает приготовление пищи и отопление."],
    ["p1_1", "Lacunza Stelar 93 Отдельностоящий дровяной камин", "Испанский отдельностоящий дровяной камин Lacunza Stelar 93, элегантный дизайн."],
    ["p1_45", "Lacunza Sara Встраиваемый дровяной камин", "Испанский встраиваемый дровяной камин Lacunza Sara, минималистичный дизайн."],
    ["p1_44", "Lacunza Oslo Отдельностоящая дровяная печь", "Испанская отдельностоящая дровяная печь Lacunza Oslo с функцией приготовления."],
    ["p1_43", "Lacunza Nickel Двусторонний встраиваемый дровяной камин", "Испанский двусторонний встраиваемый дровяной камин Lacunza Nickel."],
    ["p1_42", "Lacunza K2 800 Встраиваемый дровяной камин", "Испанский встраиваемый дровяной камин Lacunza K2 800 с большим окном."],
    ["p1_41", "Lacunza Itaca Встраиваемый дровяной камин", "Испанский односторонний встраиваемый дровяной камин Lacunza Itaca."],
    ["p1_39", "Lacunza CM 300R Угловой отдельностоящий дровяной камин", "Испанский угловой отдельностоящий дровяной камин Lacunza CM 300R."],
    ["p1_38", "Lacunza Clasica 7T Дровяная печь с духовкой", "Испанская дровяная печь Lacunza Clasica 7T с духовкой, европейский деревенский стиль."],
    ["p1_37", "Lacunza Atlantic 603 Отдельностоящий дровяной камин", "Испанский отдельностоящий дровяной камин Lacunza Atlantic 603."],
    ["p1_36", "Lacunza Adour 700ST Встраиваемый дровяной камин", "Испанский встраиваемый дровяной камин Lacunza Adour 700ST."],
    ["p1_61", "Rais Q TEE 2C Отдельностоящий дровяной камин", "Датский отдельностоящий дровяной камин Rais Q TEE 2C, скандинавский дизайн."],
    ["p1_60", "Rais Nexo Серия отдельностоящих дровяных каминов", "Датский отдельностоящий дровяной камин Rais Nexo серия, современный стиль."],
    ["p1_59", "Rais Juno L Отдельностоящий дровяной камин", "Датский отдельностоящий дровяной камин Rais Juno L с круглым окном."],
    ["p1_58", "Rais Caro 90 Отдельностоящий дровяной камин", "Датский отдельностоящий дровяной камин Rais Caro 90, элегантная цилиндрическая форма."],
    ["p1_28", "Rais Viva L Серия отдельностоящих дровяных каминов", "Датский отдельностоящий дровяной камин Rais Viva L серия."],
    ["p1_27", "Rais Visio 3 Трехсторонний встраиваемый дровяной камин", "Датский трехсторонний встраиваемый дровяной камин Rais Visio 3, обзор 270°."],
    ["p1_26", "Rais Q-TEE 2 Отдельностоящий дровяной камин", "Датский отдельностоящий дровяной камин Rais Q-TEE 2."],
    ["p1_25", "Rais Q-BE Отдельностоящий дровяной камин с угловым обзором", "Датский отдельностоящий дровяной камин Rais Q-BE."],
    ["p1_24", "Rais Pilar Отдельностоящий дровяной камин", "Датский отдельностоящий дровяной камин Rais Pilar, колоннообразный дизайн."],
    ["p1_23", "Rais Bionic Fire Двухкамерный дровяной камин", "Датский двухкамерный дровяной камин Rais Bionic Fire."],
    ["p1_22", "Haas+sohn Treviso Талькохлоритовый дровяной камин", "Австрийский талькохлоритовый дровяной камин Haas+sohn Treviso."],
    ["p1_21", "Haas+sohn Kuopio-II Талькохлоритовый дровяной камин", "Австрийский талькохлоритовый дровяной камин Haas+sohn Kuopio-II."],
    ["p1_20", "Haas+sohn Ficus-II-RLU Отдельностоящий дровяной камин", "Австрийский отдельностоящий дровяной камин Haas+sohn Ficus-II-RLU."],
    ["p1_2", "Haas+sohn Aruba Easy Талькохлоритовая дровяная печь", "Австрийская талькохлоритовая дровяная печь Haas+sohn Aruba Easy."],
    ["p1_35", "Ruegg Tillia Трехсторонний встраиваемый дровяной камин", "Швейцарский трехсторонний встраиваемый дровяной камин Ruegg Tillia."],
    ["p1_34", "Ruegg Rondeo Встраиваемый дровяной камин с изогнутым стеклом", "Швейцарский встраиваемый дровяной камин Ruegg Rondeo."],
    ["p1_33", "Ruegg RII Угловой встраиваемый дровяной камин", "Швейцарский угловой встраиваемый дровяной камин Ruegg RII."],
    ["p1_18", "Ruegg Odeon 270° Подвесной дровяной камин с изогнутым стеклом", "Швейцарский подвесной дровяной камин Ruegg Odeon 270°."],
    ["p2_56", "Element4 Lucius 140 Встраиваемый газовый камин", "Нидерландский встраиваемый газовый камин Element4 Lucius 140."],
    ["p2_55", "Element4 Tenore 140 Встраиваемый газовый камин", "Нидерландский встраиваемый газовый камин Element4 Tenore 140."],
    ["p2_54", "Element4 Summum 100F Встраиваемый газовый камин", "Нидерландский встраиваемый газовый камин Element4 Summum 100F."],
    ["p2_53", "Element4 Sky Внутренний газовый камин", "Нидерландский внутренний газовый камин Element4 Sky."],
    ["p2_31", "Element4 Trisore 140 Трехсторонний газовый камин", "Нидерландский трехсторонний газовый камин Element4 Trisore 140."],
    ["p2_29", "Element4 Bidore 100 Угловой газовый камин", "Нидерландский угловой газовый камин Element4 Bidore 100."],
    ["p3_14", "Спиртовой камин (на заказ)", "Биоэтаноловый камин, размер и внешний вид на заказ, экологичный."],
    ["p4_70", "Настенный раздельный тумановый камин (на заказ)", "3D тумановый камин настенный раздельный, эффекты на заказ."],
    ["p4_69", "Двусторонний тумановый камин (на заказ)", "Двусторонний тумановый камин, идеален для перегородок."],
    ["p4_68", "Панорамный тумановый камин (на заказ)", "Панорамный тумановый камин с широким обзором."],
    ["p4_67", "Трехсторонний тумановый камин (на заказ)", "Трехсторонний тумановый камин с обзором 270°."],
    ["p4_66", "Круглый тумановый камин (на заказ)", "Круглый тумановый камин с уникальным дизайном."],
    ["p4_65", "Подвесной тумановый камин НЛО (на заказ)", "Подвесной тумановый камин в форме НЛО."],
    ["p4_64", "Тумановый камин-перегородка (на заказ)", "Тумановый камин, служащий перегородкой или экраном."],
    ["p4_62", "Односторонний тумановый камин (на заказ)", "Односторонний тумановый камин, классический дизайн."],
    ["p4_11", "Умный 3D тумановый камин (на заказ)", "Умный 3D тумановый камин с интеллектуальным управлением."],
    ["p6_49", "Полный сервис каминов на заказ", "Полный сервис проектирования и установки каминов на заказ."],
    ["p7_6", "Электрический камин (на заказ)", "Электрический камин с реалистичными эффектами пламени."],
    ["p88_51", "Уличный огонь (на заказ)", "Уличный огонь для сада и патио, дизайн на заказ."],
    ["p8_52", "Набор инструментов для камина", "Датский набор инструментов для камина Rais, качественные аксессуары."],
  ],
  pt: [
    ["p1_71", "Lacunza Altea Fogão a Lenha Autônomo com Forno", "Fogão a lenha autônomo espanhol Lacunza Altea com forno, combinando culinária e aquecimento."],
    ["p1_1", "Lacunza Stelar 93 Lareira a Lenha Autônoma", "Lareira a lenha autônoma espanhola Lacunza Stelar 93, design elegante."],
    ["p1_45", "Lacunza Sara Lareira a Lenha Embutida", "Lareira a lenha embutida espanhola Lacunza Sara, design minimalista."],
    ["p1_44", "Lacunza Oslo Fogão a Lenha Autônomo", "Fogão a lenha autônomo espanhol Lacunza Oslo com função de cozinhar."],
    ["p1_43", "Lacunza Nickel Lareira a Lenha Embutida Dupla Face", "Lareira a lenha embutida dupla face espanhola Lacunza Nickel."],
    ["p1_42", "Lacunza K2 800 Lareira a Lenha Embutida", "Lareira a lenha embutida espanhola Lacunza K2 800 com grande vitrine."],
    ["p1_41", "Lacunza Itaca Lareira a Lenha Embutida", "Lareira a lenha embutida unilateral espanhola Lacunza Itaca."],
    ["p1_39", "Lacunza CM 300R Lareira a Lenha Autônoma de Canto", "Lareira a lenha autônoma de canto espanhola Lacunza CM 300R."],
    ["p1_38", "Lacunza Clasica 7T Fogão a Lenha com Forno", "Fogão a lenha espanhol Lacunza Clasica 7T com forno, estilo campestre."],
    ["p1_37", "Lacunza Atlantic 603 Lareira a Lenha Autônoma", "Lareira a lenha autônoma espanhola Lacunza Atlantic 603."],
    ["p1_36", "Lacunza Adour 700ST Lareira a Lenha Embutida", "Lareira a lenha embutida espanhola Lacunza Adour 700ST."],
    ["p1_61", "Rais Q TEE 2C Lareira a Lenha Autônoma", "Lareira a lenha autônoma dinamarquesa Rais Q TEE 2C, design nórdico."],
    ["p1_60", "Rais Nexo Série Lareira a Lenha Autônoma", "Lareira a lenha autônoma dinamarquesa Rais Nexo série, estilo moderno."],
    ["p1_59", "Rais Juno L Lareira a Lenha Autônoma", "Lareira a lenha autônoma dinamarquesa Rais Juno L com janela circular."],
    ["p1_58", "Rais Caro 90 Lareira a Lenha Autônoma", "Lareira a lenha autônoma dinamarquesa Rais Caro 90, forma cilíndrica."],
    ["p1_28", "Rais Viva L Série Lareira a Lenha Autônoma", "Lareira a lenha autônoma dinamarquesa Rais Viva L série."],
    ["p1_27", "Rais Visio 3 Lareira a Lenha Embutida Três Faces", "Lareira a lenha embutida três faces dinamarquesa Rais Visio 3."],
    ["p1_26", "Rais Q-TEE 2 Lareira a Lenha Autônoma", "Lareira a lenha autônoma dinamarquesa Rais Q-TEE 2."],
    ["p1_25", "Rais Q-BE Lareira a Lenha Autônoma Vista Angular", "Lareira a lenha autônoma dinamarquesa Rais Q-BE."],
    ["p1_24", "Rais Pilar Lareira a Lenha Autônoma", "Lareira a lenha autônoma dinamarquesa Rais Pilar."],
    ["p1_23", "Rais Bionic Fire Lareira a Lenha Dupla Câmara", "Lareira a lenha dinamarquesa Rais Bionic Fire de câmara dupla."],
    ["p1_22", "Haas+sohn Treviso Lareira a Lenha de Esteatito", "Lareira a lenha de esteatito austríaca Haas+sohn Treviso."],
    ["p1_21", "Haas+sohn Kuopio-II Lareira a Lenha de Esteatito", "Lareira a lenha de esteatito austríaca Haas+sohn Kuopio-II."],
    ["p1_20", "Haas+sohn Ficus-II-RLU Lareira a Lenha Autônoma", "Lareira a lenha autônoma austríaca Haas+sohn Ficus-II-RLU."],
    ["p1_2", "Haas+sohn Aruba Easy Fogão a Lenha de Esteatito", "Fogão a lenha de esteatito austríaco Haas+sohn Aruba Easy."],
    ["p1_35", "Ruegg Tillia Lareira a Lenha Embutida Três Faces", "Lareira a lenha embutida três faces suíça Ruegg Tillia."],
    ["p1_34", "Ruegg Rondeo Lareira a Lenha Embutida Vidro Curvo", "Lareira a lenha embutida suíça Ruegg Rondeo com vidro curvo."],
    ["p1_33", "Ruegg RII Lareira a Lenha Embutida de Canto", "Lareira a lenha embutida de canto suíça Ruegg RII."],
    ["p1_18", "Ruegg Odeon 270° Lareira a Lenha Suspensa Curva", "Lareira a lenha suspensa curva suíça Ruegg Odeon 270°."],
    ["p2_56", "Element4 Lucius 140 Lareira a Gás Embutida", "Lareira a gás embutida neerlandesa Element4 Lucius 140."],
    ["p2_55", "Element4 Tenore 140 Lareira a Gás Embutida", "Lareira a gás embutida neerlandesa Element4 Tenore 140."],
    ["p2_54", "Element4 Summum 100F Lareira a Gás Embutida", "Lareira a gás embutida neerlandesa Element4 Summum 100F."],
    ["p2_53", "Element4 Sky Série Interna Lareira a Gás", "Lareira a gás interna neerlandesa Element4 Sky."],
    ["p2_31", "Element4 Trisore 140 Lareira a Gás Três Faces", "Lareira a gás três faces neerlandesa Element4 Trisore 140."],
    ["p2_29", "Element4 Bidore 100 Lareira a Gás de Canto", "Lareira a gás de canto neerlandesa Element4 Bidore 100."],
    ["p3_14", "Lareira a Álcool (Personalizável)", "Lareira a bioetanol, tamanho personalizável, ecológica."],
    ["p4_70", "Lareira de Névoa Suspensa Dividida (Personalizável)", "Lareira de névoa 3D suspensa dividida, efeitos personalizáveis."],
    ["p4_69", "Lareira de Névoa Dupla Face (Personalizável)", "Lareira de névoa dupla face, ideal para divisórias."],
    ["p4_68", "Lareira de Névoa Panorâmica (Personalizável)", "Lareira de névoa panorâmica ultra-larga."],
    ["p4_67", "Lareira de Névoa Três Faces (Personalizável)", "Lareira de névoa três faces com vista 270°."],
    ["p4_66", "Lareira de Névoa Redonda (Personalizável)", "Lareira de névoa redonda com design circular único."],
    ["p4_65", "Lareira de Névoa Suspensa OVNI (Personalizável)", "Lareira de névoa suspensa em forma de OVNI."],
    ["p4_64", "Lareira de Névoa Divisória (Personalizável)", "Lareira de névoa que serve como divisória."],
    ["p4_62", "Lareira de Névoa Unilateral (Personalizável)", "Lareira de névoa unilateral, design clássico."],
    ["p4_11", "Lareira de Névoa 3D Inteligente (Personalizável)", "Lareira de névoa 3D inteligente com controle inteligente."],
    ["p6_49", "Serviço Completo de Lareira Personalizada", "Serviço completo de design e instalação de lareiras personalizadas."],
    ["p7_6", "Lareira Elétrica (Personalizável)", "Lareira elétrica com efeitos de chama realistas."],
    ["p88_51", "Fogo Externo (Personalizável)", "Fogo externo para jardim e pátio, designs personalizáveis."],
    ["p8_52", "Kit de Ferramentas para Lareira", "Kit de ferramentas para lareira dinamarquês Rais."],
  ],
};

// ─── Build files ──────────────────────────────────────────────

const langs = ["de", "fr", "es", "it", "ru", "pt"];
const dir = resolve("src/lib/lang-data");

for (const lang of langs) {
  const map = { ...categories[lang], ...install[lang], ...countries[lang] };
  for (const [id, name, desc] of prods[lang]) {
    map[`${id}:name`] = name;
    map[`${id}:description`] = desc;
  }

  const lines = [
    `const ${lang}_data: Record<string, string> = {`,
  ];
  for (const [key, val] of Object.entries(map)) {
    const escaped = val.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    lines.push(`  "${key}": "${escaped}",`);
  }
  lines.push("};", "", `export default ${lang}_data;`, "");

  writeFileSync(`${dir}/${lang}.ts`, lines.join("\n"));
  console.log(`✓ ${dir}/${lang}.ts (${Object.keys(map).length} entries)`);
}

console.log("\nDone! Now register them in lang-data/index.ts");
